### ISSUE TITLE
Use pytest for testing

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#10]
Hi @bemcdonnell for python testing we have choices, unittest which is part of standard python and py.test, which is a third party module. I prefer the latter as it is more modern, in constant development, and makes testing a breeze.

I can help moving the current test into more proper unit testing convention (with pytest)

Thoughts?

**Comment by bemcdonnell** [comment]
@goanpeca I think pytest is the best option for us to move forward with. If you want to make help with that, it would be awesome

**Comment by goanpeca** [comment]
@bemcdonnell which branch should I make the PRs against?

**Comment by bemcdonnell** [comment]
@goanpeca how many more steps would it take to update the Appveyor CI?  FYI, as of today, the only platform we have full support on is Windows.  There is a *.dylib in the repo for OS but It only has simple interfacing functions.   I will have a Linux version of SWMM5 compiled and functioning very very soon.  

Please submit a PR to the pythonic feature branch :-)

**Comment by goanpeca** [comment]
>how many more steps would it take to update the Appveyor CI?

For testing stuff on CI we (I ?) are normally using conda as the environment for bootstrapping the build process (if needed) and the environment process. So I would prefer to have the conda packages for use with this. If you have the build stuff ready for linux (which should be almost the same if not the same for OSX) then I can make those packages this week.

Once that is ready I would need to convert all stuff to pytest.... then the CI should be a couple of hours more.

**Comment by bemcdonnell** [comment]
@goanpeca, I have a few changes to make to swmm before it will *happily* compile on Linux. we can talk about workflows, milestones, and strategy tomorrow evening on the call.

**Comment by goanpeca** [comment]
@bemcdonnell are these names attached to anything meaningful `TestModel1_weirSetting.inp`?

I am reorganizing all the tests folder, plus moving them so just making sure the number (testmodel1) can be removed in favor of more standard shorter names?

**Comment by bemcdonnell** [comment]
@goanpeca Feel free to change any of those files.  They are only used in the tests scripts... We can dump all of those tests..
