### ISSUE TITLE
Add extra check on library loading

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#102]
To make this package work seamlessly with conda (when we finally make the swmm package for it) we need to update the logic that checks for the DLL etc... so that it tries/except first to load what is available on path (which is the way it should work with conda) and then it loads the bundled libraries (which is what is being used now for pip only installs)

**Comment by bemcdonnell** [comment]
As long as we can still allow the user to "pick" the engine they want to use.

**Comment by goanpeca** [comment]
>As long as we can still allow the user to "pick" the engine they want to use.

@bemcdonnell I was never convinced of this feature really, when using conda and using a dev version of SWMM we need to revamp how your development workflow works. There is no real circumstance when one needs to manually select a DLL.

**Comment by bemcdonnell** [comment]
The reality is, many of us use proprietary versions of swmm. These versions include a toolkit API but also some nice internal features. In any case, I want to be able to run my proprietary version of swmm within pyswmm. As far as how it is implemented today, I find it very handy. Perhaps there is a better way. In any event, I want to be able to pick and choose.

**Comment by bemcdonnell** [comment]
Another case for this is if I want to run a simulation with an older version of swmm to post process and compare results.

**Comment by goanpeca** [comment]
>These versions include a toolkit API but also some nice internal features.

pyswmm is an open package and it should support what is out there in the open, if you want support for your custom tweaked SWMM that is a different story. BEsides, whatever nice things you have implemented on this "closed private swmm" would not be implemented.

**Comment by goanpeca** [comment]
>Another case for this is if I want to run a simulation with an older version of swmm to post process and compare results.

Then we create conda packages for different versions of swmm, but you dont handle de dll path manually.. that is just not how things normally work

**Comment by goanpeca** [comment]
I am against adding extra code on pyswmm so it can run some private version of SWMM someone (you?) use out there. That would be a huge turndown for open source users, if there is some code on pyswmm

```python
# The code bellow is needed for the closed version of PYSWMM that emnet uses...
def nice_private_api...
```

Again, that is not how open source works.

**Comment by bemcdonnell** [comment]
Yes indeed pyswmm is an open source tool. However, I feel that it should be flexible.  The way it's implemented today is vey flexible. All I'm wanting is to point to a different engine - not to build in features that only benefit the proprietary engines. giving users flexibility is helpful. Lew himself, if he didn't agree on an approach or feature to add to swmm, he would make it possible for some user to accomplish what they needed to without compromising the entire thing. 

We've got people testing swmm on a GPUs, other companies using different groundwater routines, others with different threading approaches, some with different infiltration methods, some with variations on equations, some with conduit lengthening features for stability. As the community becomes more in tune with our open source initiative, the features will come. But until then I believe flexibility is key.

**Comment by bemcdonnell** [comment]
By the way. You mention handling the pay manually - that is not how it was finally implemented. Today the user does is 

Import pyswmm
Pyswmm.lib.use("enginename")

**Comment by goanpeca** [comment]
I guess ok then.

**Comment by bemcdonnell** [comment]
We'll find a way! :-)

**Comment by dickinsonre** [comment]
I agree with @bemcdonnell it would be great to be able to choose an alternative engine for engine development, backward and forward engine versions and feature testing.  I would also be a boon to thesis students around the world who are handicapped by time and a lack of GUI programming skills.  They have an idea to test or a feature they want to add the ability to choose is important to them.
