### ISSUE TITLE
Rpt file parser 

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#104]
@aerispaha , do you have a SWMM rpt file parser?

**Comment by dickinsonre** [comment]
@bemcdonnell a swmm rpt or text file parser is part of the SWMM 5 GUI code in Pascal

**Comment by bemcdonnell** [comment]
Right, but I'd like to integrate this functionality into pyswmm for post processing analyses. A parser in python would be ideal

**Comment by aerispaha** [comment]
@bemcdonnell, I do have a rpt parser. It's not complete but I make a lot of use of it for grabbing data from element-wise results tables. I can help port this into pyswmm if it makes sense.

**Comment by bemcdonnell** [comment]
@aerispaha, awesome! That would be great.  One of my next goals it to get post-processing fully implemented.  I have added the .out file reader but haven't had time to get it working.  The .out reader is compiled C code with a python wrapper around it.  This helps us query results much faster (since compiled code is doing the heavy lifting). 

With the .rpt parser we might go through a couple iterations on implementation.  We should make sure it is cohesive with the current pyswmm framework.  In any event, the rpt file parser will be a great addition to the tool!

**Comment by bemcdonnell** [comment]
@aerispaha, Thanks in advance! I set this issue to Milestone v0.5.0

**Comment by bemcdonnell** [comment]
@aerispaha, Can this be done without any *major* dependencies? I'm in favor of keep pyswmm pretty light weight and robust.

**Comment by aerispaha** [comment]
@bemcdonnell I was actually contemplating this last night. I make use of Pandas for some of the parsing in swmmio. Basically, I do some manual text parsing ([here](https://github.com/aerispaha/swmmio/blob/master/swmmio/utils/text.py#L156)) to get it to a point where Pandas can make sense of it with a pd.read_table() call. From that point, a lot of the manipulation leverages Pandas (I love pandas).

I would except that this can be done without Pandas, it will just be more of a lift. But, I'm on board with trying - in general I'm also in favor of keeping dependencies light.

**Comment by bemcdonnell** [comment]
Maybe I misinterpreted what @dickinsonre was saying --- Maybe the point was that we could re-write the parser in Python.

**Comment by bemcdonnell** [comment]
This begs the question - Incorporate the RPT parser in PySWMM or write a separate package?

**Comment by dickinsonre** [comment]
@bemcdonnell Yes, that was my intention.  I am not sure how transportable PAS code is but you can see how Lew Rossman parses the RPT file in this Delphi routine  Fresults.pas

**Comment by bemcdonnell** [comment]
I have provided a link to the file (had to change the extension for Github) -> [Fresults.txt](https://github.com/OpenWaterAnalytics/pyswmm/files/1055935/Fresults.txt)

**Comment by bemcdonnell** [comment]
There might be a clean way to work this straight into the existing infrastructure that PySWMM has today.  For example (the stats functions haven't been incorporated yet but..) 

```python
    @property
     def conduit_flow_stats(self):
         """
         Conduit Flow Stats. The stats returned are rolling/cumulative.
         Indeces are as follows:
 
         +---------------+---+
         | Max Flow Rate | 0 |
         +---------------+---+
         | Max Velocity  | 1 |
         +---------------+---+
         | Max Depth     | 2 |
         +---------------+---+
 
         :return: Group of Stats
         :rtype: list
         """
         if model_was_or_is_running_gather_stats_here!
                 return self._model.link_statistics(self.linkid,
                                            LinkStats.link_flow_stats.value)
         else: gather_stats_from_the_rpt_file
```

**Comment by bemcdonnell** [comment]
So I think functional access into the RPT file is the best strategy.  Calling a function to get a value would be better than parsing out the entire file and storing it into a data model.

**Comment by aerispaha** [comment]
That makes sense to me. If I understand correctly, I this is similar to the model in swmmio: when data is needed, I call a function that reads the text directly from the .rpt.

After some more thought though, I'm not entirely understanding the end goal of parsing the rpt within the PySWMM project. Doesn't PySWMM already have access to the SWMM data model, and wouldn't it be easier to retrieve results in that way, rather than parsing output text? 

I even thought that swmmio may someday depend on PySWMM so that I can avoid parsing the rpts altogether. What am I overlooking here?

**Comment by bemcdonnell** [comment]
It's a fair question.  Post-processing results is a domain that would fit the *spirit* of pyswmm.  If I have a model that takes 15 hrs to run, and I want to generate some quick plots (assuming I have access to the rpt and out files), I'd rather not run the model again.

**Comment by bemcdonnell** [comment]
It just seems that if there was a seamless way to get at data, it would be really nice.  If the user initialized a node object, and can then pluck out results from it would be great.  Same point - if the user wants to use pyswmm to simply "load" a model and get parameters out, they can do that without running it.  Results, if available, would be a great addition to this toolbox.

**Comment by aerispaha** [comment]
Understood - that makes sense to me now after sleeping on it. 

In general, I'm interested in being able to model comprehensive suites of scenarios (for a number of reasons). And, being able to store the results of all these scenarios and easily interpret them when needed is definitely something that is useful. 

Its a big part of how we're doing flood mitigation planning in Philadelphia. For example, we have a "data explorer" web interface that allows the end user to click through any of a set of 100s of scenarios and get a summary report and visualizations. To build that, I used swmmio to parse the rpts of any queried scenario on the fly (i.e. without having to rerun the model).

**Comment by bemcdonnell** [comment]
I Met the illustrious @lucashtnguyen at the EWRI Conference in May and just found his Python-based SWMM rpt file parser on Github: https://github.com/lucashtnguyen/swmmreport.  I'd like to see this utility find its way into PySWMM as part of a post-processing tool if possible.  

This can probably use a lot of the infrastructure that we currently have in PySWMM.  So today we have `Simulation` class.  I think we can create a new class called `Report`.  Once instantiated, it could leverage the existing classes we have (`Node`, `Link`, `Subcatchment`, `Outfall`, `Storage`, `Pump`). These classes currently have statistics available (but are accessed during a simulation).  I feel that they can be re-tooled a bit to allow for consistent user-experience whether they are streaming results during a simulation or reading results from the report files.

@goanpeca, what are your thoughts on my proposed implementation approach?
@lucashtnguyen, welcome to OWA!

**Comment by goanpeca** [comment]
Sure @bemcdonnell I think there is value in it!

**Comment by lucashtnguyen** [comment]
Hi gang, glad to be here! I've checked out PySWMM a few times, but haven't had a deep dive into depths :ocean: of it's code base. I am familiar with Tim Cera's .out parser and have hacked around with that in years past. My .rpt parser has a fairly complete (though light weight) frame work, but it still missing several of the SWMM data streams. Right now it does depth and surcharge.

**Comment by goanpeca** [comment]
@lucashtnguyen we can take it from there :-) an expand, pyswmm is still young but we have plans to conquer the world 😈

**Comment by lucashtnguyen** [comment]
I suppose I should give a little introduction:
I'm a scientist at Geosyntec. I work mainly in water resources, but my python and data analysis skills get brought into a lot of different work in different client sectors. These days I deploy and run a lot of models on Amazon Web Services, write internal tools, data wrangle files that make Microsoft (e.g. Excel) products :cry:

**Comment by bemcdonnell** [comment]
@lucashtnguyen, there is no shame in being a data plumber! :-)

So I'd like for you to get the credit for your work.  Therefore, I think the cleanest way to start this process out would be for you to essentially commit your code directly to the repo (instead of someone else committing it on your behalf).  This way when I run the `update-authors.sh` script, you will be added to the AUTHORS list.

I realize that this is not normally the *open source way* where we ask people to bring their code to us... Moreover, I also understand that this is probably not in your immediate workflow.  So I think for starters you can drop `swmmreport.py` right into the pyswmm folder.  Once in place, I can work on getting this to mesh into the framework.  

When/If you have capacity, down the road, we can always grow the utility!

For this work, I went ahead and added a branch to the main repo called `rptparser`.  I suggest adding your code into PySWMM then submitting your Pull Request back to the `rptparser` branch.  Once there, I can try some things out.  How does this sound?

**Comment by lucashtnguyen** [comment]
@bemcdonnell Haha agree! The emoji was signifying MS Excel crying. I'd like to get a better understanding on how you want to mesh this with the current code base so that I can help you integrate my tool as well. I have a project kicking off in about a week that I _need_ to use `swmmreport.py` and will _need_ to build more functionality. Maybe it makes sense for me to build that out first? This workflow you've described sounds fine, though I do plan to maintain `swmmreport` as it's own repo (for now) because it is so light weight.

**Comment by bemcdonnell** [comment]
@lucashtnguyen, you raise a really good point.  If you are going to maintain this in a separate repo (for now), then maybe we can take this in a slightly different direction.  Would you be interested in some support over there? Once it reaches a stable place, we can migrate it into pyswmm.  If you want to raise some issues over there as a to-do list, we can begin collaborating there.  How does that sound?

**Comment by lucashtnguyen** [comment]
@bemcdonnell I've got project budget to update this tool, but if you have free time on your hands great! I think what would be most helpful is for you to submit an issue to the repo on what you would need to integrate this to pyswmm.

**Comment by bemcdonnell** [comment]
@lucashtnguyen, I will work on a GithubGist as an example of how this might be integrated.

**Comment by bemcdonnell** [comment]
@lucashtnguyen, Here is the Gist I put together. It is not ready to drag and drop, but it should illustrate the concept.  The theme of this is to expose iterators for all objects in the report file.  This should touch on almost all items that are stored in the file. 

https://gist.github.com/bemcdonnell/a1c1231f1dd81480e0bfb9f8f4d7d951 

There are three scripts:

1. `user_script.py`,
2. `report.py`, and
3. `swmmreport.py`

`swmmreport.py` is the low-level file that will do the heavy lifting. This should contain similar methods to what you will find in `swmm5.py`.  This will keep object IDs and counts.  

Next, `report.py` is a thin layer that allows the opened file to be treated just like a `Simulation` class.  When opened using the `with` statement, you can pass the handle to the Report object to `Nodes`, `Links` and etc classes.  You can then take advantage of the iterators available within those classes. 

The example I put together is in the `user_script.py`.  

What are you thoughts?

**Comment by lucashtnguyen** [comment]
@bemcdonnell I read through your Gist and the concepts seem clear to me. I should have `swmmreport`  built out to where I need for my current project by Tuesday. Then I'll be able to think more carefully about this integration.

**Comment by bemcdonnell** [comment]
@lucashtnguyen, Thanks!  Also just to be clear, you might have a better approach once you get into the integration.  Please don't feel any way restricted by my proposed integration strategy.
