### ISSUE TITLE
Orifice opening limits

### ISSUE THREAD

**Issue by abhiramm7** [OpenWaterAnalytics/pyswmm#108]
Orifice opening percent beyond 100 percent(>1.0) seems to significantly effect the performance of the hydrograph(below plot). I think we should have the function implement restrictions on the percent opening. 
![wier_opening_error](https://user-images.githubusercontent.com/14915561/28206479-a9fdd16e-68a3-11e7-9d23-5e71d2fef098.png)

```python
from pyswmm import Links, Simulation
import matplotlib.pyplot as plt

with Simulation("aa_orifices_v3_scs_0360min_025yr.inp") as sim:
    link_weir = Links(sim)
    flow1 = []
    for steps in sim:
        link_weir["OR48"].target_setting = 10.0 
        flow1.append(link_weir["OR48"].flow)
    print(sim.runoff_error)

flow = []
with Simulation("aa_orifices_v3_scs_0360min_025yr.inp") as sim:
    link_weir = Links(sim)
    for steps in sim:
        link_weir["OR48"].target_setting = 1.0 
        flow.append(link_weir["OR48"].flow)
    print(sim.runoff_error)
plt.plot(flow1, label="Unrealistic orifice opening")
plt.plot(flow, label="Fully open orifice")
plt.legend()
plt.show()

```

**Comment by dickinsonre** [comment]
@abhiramm7 If you make this change it will change the results for existing models and make it very hard for PID controllers to work.   IMO, if you want to add this it would be better to add another Control Rule to never let the setting go beyond 1.0

**Comment by abhiramm7** [comment]
@dickinsonre Oh, I wasn't aware of it. By PID controller being effected, do you mean that we need the flexibility of orifice setting being > 1 ?

I was thinking of a slight change in the current implementation, where the function checks whether the link is an orifice and if the opening is > 1 raises a error. Is that what you meant by adding a control rule ?

**Comment by bemcdonnell** [comment]
@abhiramm7, do you mind raising this issue on the SWMM REPO? Whether copy or reference this, I don't mind either way. It's worth a discussion for sure.

**Comment by bemcdonnell** [comment]
@dickinsonre, I feel that for pumps we can have uncapped settings [0, inf).  If we allow an orifice to go "uncapped", it seems to me that it could exhibit unrealistic behavior.  This might be something we could do for PySWMM (and not update in SWMM).

**Comment by goanpeca** [comment]
@bemcdonnell a first step would be to print a warning!

```
import warnings

class PySWMMWarning(Warning):
    pass


class OpeningLimitsWarning(PySWMMWarning):
    pass


warnings.warn("Orifice opening higher than X. Simulation could exhibit unrealistic behavior!", OpeningLimitsWarning)
```

**Comment by dickinsonre** [comment]
I can think this is needed for bendable weirs and in ICM we have a VCWEIR RTC that allows weirs and orifice to grow and shrink.  I think I had this in XP-SWMM as well.   If there is way to do something then people will use that means as a workaround.  Taking away engine capabilities for a one off problem may not be the best option.  IMO, again.

**Comment by bemcdonnell** [comment]
@dickinsonre, that's an excellent point. It's much hard to take away things than it is to add

**Comment by dickinsonre** [comment]
@bemcdonnell   @abhiramm7 my example of a PID is bogus as Lew Rossman has code to not allow the setting to be greater than 1 for a non pump is controls.c
    // --- check that new setting lies within feasible limits
    if ( setting < 0.0 ) setting = 0.0;
    if (Link[a->link].type != PUMP && setting > 1.0 ) setting = 1.0;

**Comment by bemcdonnell** [comment]
@dickinsonre, thanks for pulling tha code out! So the API allows us to bypass this currently and make a setting or an orifice or weir [0, inf). It looks like this needs to be fixed in the API so orifrces and weirs should be limited to [0,1]

**Comment by bemcdonnell** [comment]
@abhiramm7, are you interested in making this API change in SWMM?

**Comment by abhiramm7** [comment]
@bemcdonnell I can give it a shot

**Comment by bemcdonnell** [comment]
Addressed this issue in SWMM. Closing it here.
