### ISSUE TITLE
Release process / Workflow

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#11]
I will be devoting some time to this project starting this week, so I propose some workflow to organize the work and give information to future developers.

I have some info from other projects I work on, and I can start adding that to the wiki, but I would need some access for that.

@bemcdonnell do you want to schedule a hangout/skype to go over the workflow and what you think?

**Comment by bemcdonnell** [comment]
@goanpeca I added you as a collaborator to the project
