### ISSUE TITLE
Linux python3 compatibility

### ISSUE THREAD

**Issue by ggerber** [OpenWaterAnalytics/pyswmm#110]
Hi,
Is pyswmm expected to work straight out of the box with python3?
I had to change swmm_run in swmm.py (lines 222-224) to following to make it run
```python
        self.SWMMlibobj.swmm_run(
            ctypes.c_char_p(inpfile.encode()),
            ctypes.c_char_p(rptfile.encode()), ctypes.c_char_p(binfile.encode()))
```

Otherwise I had this error:
TypeError: bytes or integer address expected instead of str instance

My script:
```python
from pyswmm import Simulation

infile='/home/user/Desktop/test.inp'
rptfile='/home/user/Desktop/test.rpt'
outfile='/home/user/Desktop/test.out'
sim = Simulation(inputfile=infile, reportfile=rptfile, outputfile=outfile)
sim.execute()
```

**Comment by bemcdonnell** [comment]
@ggerber, what platform are you working on?  So far we have had limited support for Linux / MacOS.  Windows should be ok

**Comment by ggerber** [comment]
linux; ubuntu 16.04.

**Comment by bemcdonnell** [comment]
Ok I think I see the issue here. 

If you look at the function `swmm5.py` function `swmm_open`, we are actually using the `six` library to encode this:

```python 
errcode = self.SWMMlibobj.swmm_open(
            ctypes.c_char_p(six.b(inpfile)),
            ctypes.c_char_p(six.b(rptfile)), ctypes.c_char_p(six.b(binfile)))
```

Just to satisfy my curiosity, do you mind encoding API function call in `swmm_run` like I have above? I'm interested in see if this works for you.

**Comment by ggerber** [comment]
Exact code above doesnt appear to start the simulation, unfortunately.
FYI, I am running linux on a windows machine using the free virtualbox,
should you in future think of a linux test environment.

**Comment by bemcdonnell** [comment]
@ggerber,

we have testing for linux but we are working on an automated building strategy for SWMM.  

As for my code suggestions above, let me clarify.  I am not suggesting using the `swmm_open` function in place of `swmm_run`. I am suggesting that you use the `six` package to encode the three function arguments. Is this how you incorporated my suggestions? This strategy did not work?

```python

    def swmm_run(self, inpfile=None, rptfile=None, binfile=None):
        """# TODO:."""
        if inpfile is None:
            inpfile = self.inpfile

        if rptfile is None:
            if self.rptfile != '' and self.rptfile is not None:
                rptfile = self.rptfile
            else:
                rptfile = self.inpfile.replace('.inp', '.rpt')

        if binfile is None:
            if self.binfile != '' and self.binfile is not None:
                binfile = self.binfile
            else:
                binfile = self.inpfile.replace('.inp', '.out')

        self.SWMMlibobj.swmm_run(ctypes.c_char_p(six.b(inpfile)),
            ctypes.c_char_p(six.b(rptfile)), ctypes.c_char_p(six.b(binfile)))
```

**Comment by bemcdonnell** [comment]
@ggerber, I'm also curious - did you build SWMM yourself or are you using the version that was delivered with the package?

**Comment by bemcdonnell** [comment]
Addressed this issue.
