### ISSUE TITLE
[Error 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jsadler2** [OpenWaterAnalytics/pyswmm#124]
Hi. I just installed pyswmm through pip. When I run this code:
```Python
from pyswmm import Simulation
sim = Simulation('example.inp')
```
I get the following error:
`WindowsError: [Error 193] %1 is not a valid Win32 application`
I am running Windows 10 64 bit. Python 2.7 64 bit
I thought maybe the problem is that it can't find the SWMM execution files so I added the directory where I have SWMM on my system to the environmental variable path. But it didn't change anything. Any suggestions?

**Comment by bemcdonnell** [comment]
@jsadler2, SWMM has not been fully tested on a 64 bit architecture yet which is why we are currently only compatible with py 32-bit.  However, if you want to use it 64bit version of SWMM, get it from here: [OWA Lib SWMM](https://anaconda.org/owa/libswmm ).

If you replace the swmm5.dll with this one `site-packages/pyswmm/lib/windows` with the dll from conda, it should run.  If it doesn't run, let me know!

**Comment by bemcdonnell** [comment]
@jsadler2, by the way - we are working on 64-bit compatibility for SWMM.  We are building a complete regression testing framework and we're a few weeks out.  You can watch our progress here: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model

**Comment by jsadler2** [comment]
That makes sense. Thanks for the help, @bemcdonnell. Switching out the dll file worked. Cool work here, both with the PySWMM and the 64-bit compatibility.

**Comment by bemcdonnell** [comment]
@jsadler2, glad to hear it worked.  I think the Python error `WindowsError: [Error 193] %1 is not a valid Win32 application` is a bit dated and doesn't reflect 64-bit python.  Anyways - Thanks for using PySWMM!

**Comment by anneliesesytsma** [comment]
@bemcdonnell 

I am having this same issue; can you describe what dll to replace the swmm5.dll with? I found the swmm5.dll in my site-packages/pyswmm/lib/windows folder but I'm not sure what to replace it with.

Thanks!

> If you replace the swmm5.dll with this one site-packages/pyswmm/lib/windows with the dll from conda, it should run. If it doesn't run, let me know!

**Comment by bemcdonnell** [comment]
@anneliesesytsma check this link out: https://github.com/OpenWaterAnalytics/pyswmm/issues/153

**Comment by bemcdonnell** [comment]
@anneliesesytsma you just need to have VCOMP120.DLL either installed to your machine or sitting in your working directory

**Comment by anneliesesytsma** [comment]
@bemcdonnell It looks like I do already have that on my machine, but am still getting the error. I get the error with Windows 10 64 bit Python 2.7 64 bit but have also tried using Python 2.7 32 bit environment.

**Comment by bemcdonnell** [comment]
Try copying the VCOMP120.DLL into your working directory (next to your script).  pyswmm works on any 32-bit python > 2.5... I use py3.6-x86

**Comment by anneliesesytsma** [comment]
Ok, I think that worked (I am no longer getting this error) but now I'm not sure if it's running simulations at all...

`sim = Simulation(r'C:\Users\annel\Desktop\SWMMModel\square.inp','C:\Users\annel\Desktop\SWMMModel\square.rpt')
sim.execute()`
`... SWMM Version 5.2.0.dev1
... Run Complete`

But I don't see a report file or anything in the folder, and it executed so quickly I don't think it actually did anything. Am I missing something? I'm totally new to pcswmm but am excited to use it!

**Comment by mebiusvista** [comment]
Hi, I ran into the same problem as people previously reported, and following your suggestion I'm looking up the SWMM5.dll but can't locate it. I'm running on a Win64 laptop with SWMM and PySWMM installed. I also tried put the line **pyswmm.lib.use("swmm5")** into my code but still not working. Any specific guidance would be appreciated!
