### ISSUE TITLE
pollutant buildup addition to subcatchment stats

### ISSUE THREAD

**Issue by katmratliff** [OpenWaterAnalytics/pyswmm#125]
Proposing to add a new entry to the subcatchment `statistics` dict. Corresponding changes are in the process of being pulled into OWA/SWMM.

**Comment by katmratliff** [comment]
@bemcdonnell trying to follow your author contributions checklist, albeit a little out of order :)

**Comment by katmratliff** [comment]
@bemcdonnell for the purposes of adding additional for subcatchment buildup, would you rather me create a separate test script or include it as part of test_subcatchments.py?

I have a test model and script that I've been using myself, but it uses both matplotlib and numpy. If I were to add my own buildups test script, would it be better to strip the extra libraries?

**Comment by bemcdonnell** [comment]
@katmratliff, I suggest a new test script for pollutnats `test_pollutants.py`

**Comment by bemcdonnell** [comment]
@katmratliff, and I would keep the plotting dependencies out for now. Simple tests are good using `assert`
