### ISSUE TITLE
Add x-coord and y-coord as property to node object

### ISSUE THREAD

**Issue by jsadler2** [OpenWaterAnalytics/pyswmm#126]
I would like the node object to include x and y coordinates as object properties. The most straightforward way to do this in my mind is to write a Python parser to extract this info from the .inp file. 

Note: I am new to the pyswmm world so I'm not exactly sure what this would involve. I was about to write some code to parse the .inp on my local machine as I need this functionality personally, but I thought that it might be of use more generally and maybe I could just make it part of pyswmm.

**Comment by bemcdonnell** [comment]
@jsadler2, I suggest you write a Github Gist with the framework that you have in mind.  I think we will have a lower level input file meta data reader, and the higher level nodes objects will call down and get the coordinates.  

The high level API, the coordinates would become a property of a Node object so:

```python
from pyswmm import Simulation, Nodes

with Simulation(*.inp) as sim:
    node1 = Nodes(sim)['node-name-in-inp']
   
    print(node1.xcoord, node1.ycoord)
```

**Comment by lucashtnguyen** [comment]
@jsadler2 I've actually just recently written something to do this, see: https://github.com/lucashtnguyen/hymo/blob/master/hymo/swmminp.py#L503

**Comment by lucashtnguyen** [comment]
@bemcdonnell if this is functionality you guys want in pyswmm, I can see about adding that in with the report parser. My availability will be opening up soon

**Comment by bemcdonnell** [comment]
@lucashtnguyen, I think coordinates would be nice to support within pyswmm.  One of the things I want to be thinking of is that as time goes on; pyswmm will hopefully touch the entire SWMM5 Data model and have access to `add item` and `remove item`.  I like the functionality you bring to surface the contents of the input file to a user and with such capability, I want to be careful in that the user will not expect to be able to `set` all parameters at this time.

**Comment by lucashtnguyen** [comment]
@bemcdonnell I agree. The reason pyswmm is powerful is because it interacts with the data model opposed to just viewing it. 

@jsadler2 if you need a quick fix, hymo should let you query the coordinates pretty easily by doing something like:

```python
from hymo import SWMMInpFile

inp = SWMMInpFile("my_inp.inp")

coords = inp.coordinates.query("Node == 'node1'")
x = coords.X_Coord
y = coords.Y_Coord
```

**Comment by jsadler2** [comment]
@lucashtnguyen that's great. That's pretty much exactly what I was looking for. I cloned your repo and instantiated the `SWMMInpFile` object, but when I try to access the coordinates property, it threw an error: 
![image](https://user-images.githubusercontent.com/6943441/32388645-b640f7be-c09e-11e7-8230-0df57933b321.png)

Any idea what I could have done wrong or if there is a fix?

**Comment by bemcdonnell** [comment]
@jsadler2, i raised an issue related to that on @lucashtnguyen's project https://github.com/lucashtnguyen/hymo/issues/24

**Comment by jsadler2** [comment]
Thanks, @bemcdonnell that makes more sense to have it there. I'm fine moving the whole comment to keep things cleaner if you prefer.

**Comment by lucashtnguyen** [comment]
@jsadler2 let's move the conversation over there. Thanks @bemcdonnell
