### ISSUE TITLE
Pyswmm on Windows, OSError [WinError 126]

### ISSUE THREAD

**Issue by gregjewi** [OpenWaterAnalytics/pyswmm#153]
Hey All,

I'm having trouble using pyswmm on Windows. I've tried running it outside of Anaconda with 64bit python 3.6, inside Anaconda (64 bit, 3.6), with a 32 bit python 3.6 build in an environment. I even downloaded and am running a separate Anaconda 32bit as well. (For all attempts I used pip install pyswmm.)

When I am using either of the 32 bit python builds (my 32 bit env or the standalone Anaconda 32 bit) I get the same error when trying to instantiate a simulation:

>>> sim = Simulation('GDRSS_simple3_ISD_Rework.inp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Rain\Anaconda32bit\lib\site-packages\pyswmm\simulation.py", line 68, in __init__
    self._model = PySWMM(inputfile, reportfile, outputfile, swmm_lib_path)
  File "C:\Users\Rain\Anaconda32bit\lib\site-packages\pyswmm\swmm5.py", line 132, in __init__
    self.SWMMlibobj = ctypes.WinDLL(swmm_lib_path)
  File "C:\Users\Rain\Anaconda32bit\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Searching online about this error, it seems to be associated with the .dll file.  I swapped out the .dll that comes with pyswmm for the .dll that comes with EPA SWMM 5.1 (tried versions both 5.1.011 & .012.) This resolved the error on instantiation, but created other errors. In a side conversation, Abhi coached me not to switch the .dll, so I'm back to trying to resolve the error above.

Thanks for the help/patch.

-Greg

**Comment by bemcdonnell** [comment]
Search the web for VCOMP120.DLL. This is the multithreadinng library. Depending on your platform, you might need this dll placed in your working directory.  This dependency issue will be going away in a couple weeks (I promise). If that doesn’t work, there are a few more tricks to solve it.

**Comment by bemcdonnell** [comment]
Ok any event, pyswmm only works with 32bit python

**Comment by gregjewi** [comment]
Perfect! Working now. Thanks for the quick fix.

**Comment by bemcdonnell** [comment]
No prob!

**Comment by ngg-osu** [comment]
Thanks to Bryant. Another way that seems to work is to install  Visual C++ Redistributable Packages for Visual Studio 2013, directly from Microsoft website. Choose "vcredist_x86.exe" version.

**Comment by bemcdonnell** [comment]
I think this approach will solve our dependency issue. We can distribute VCOMP120.dll with SWMM5.dll in the next release and update the system path from Python. 

https://stackoverflow.com/a/35403780

**Comment by bemcdonnell** [comment]
Reference #124
