### ISSUE TITLE
ctypes LP_c_double question

### ISSUE THREAD

**Issue by katmratliff** [OpenWaterAnalytics/pyswmm#156]
Hi PySWMMers, I am hoping someone can clarify a ctypes question... when passing arrays of pollutant values (e.g., totalLoad in the outfall statistics) from SWMM, there are many more values than I would have expected. For example, in swmm5.py: 

https://github.com/OpenWaterAnalytics/pyswmm/blob/fe33a3f289dd29ba17dc75db7eb908b466469370/pyswmm/swmm5.py#L1234-L1251

The LP_c_double object pol_stats_array has many values, whereas I would have expected there to just be one value per pollutant type. Although I realize only first value(s) get passed to the stats dict, I am wondering why these arrays have so many values. Should a size be specified when it is created here?:

https://github.com/OpenWaterAnalytics/pyswmm/blob/fe33a3f289dd29ba17dc75db7eb908b466469370/pyswmm/toolkitapi.py#L196

I'm currently having issues with passing additional pollutant arrays around and things crashing after a few timesteps, so I'm curious if this could be part of the problem.

**Comment by dickinsonre** [comment]
Is the array for the number of landuses per Subcatchment>  Each landuse has its own pollutant buildup/washoff options.

**Comment by katmratliff** [comment]
@dickinsonre there are many many more values in this array than the number of landuses

**Comment by dickinsonre** [comment]
Okay, i will try to help these weekend.  Lew did have a programmers guide at one time (2004?) to SWMM5 but LID changes post 2008 made everything more complex in subcatch.c

**Comment by jennwuu** [comment]
Is the array for the number of pollutants? The stats I see from outfall_statistics are average_flowrate (value), peak_flowrate (value), pollutant_loadings (another dictionary for pollutants), total_periods (value).

**Comment by dickinsonre** [comment]
totalload is for all of the pollutants so it is an array

            // --- print load of each pollutant for outfall
            for (p=0; p<Nobjects[POLLUT]; p++)
            {
                x = OutfallStats[k].totalLoad[p] * LperFT3 * Pollut[p].mcf;

**Comment by bemcdonnell** [comment]
We don’t need to be too comfortable with ctypes for much longer. In a couple weeks we will deprecate out SWMM5.py and toolkitAPI.py completely when we integrate SWIG support.  :-)

**Comment by katmratliff** [comment]
@bemcdonnell what I'm testing with currently has one pollutant

**Comment by bemcdonnell** [comment]
What is the name of it? And how many items is it iterator unpacking? 

For fun, try adding another pollutant and see what happens. Should be two. I wonder if it is iterating over the number of characters in the string array of your first pollutant. Then it seg faults.  

(Full disclosure; I am on an iPhone so I didn’t dig into the code before coming up with this hair brained idea so if it sounds stupid, that’s why :-) )

**Comment by jennwuu** [comment]
@katmratliff I'd happy to look at your test model too to check out the pollutant arrays if you want!

**Comment by katmratliff** [comment]
@jennwuu yes, the intention is to print these values at every timestep (so you can make a timeseries, for example). It's working if you only print the subc stats at the end of a run. The crashing issue comes when you call for the subcatchment stats to be printed at every timestep, which is why I think those pollutant arrays are blowing up for some reason that I can't identify.

**Comment by katmratliff** [comment]
Since I've got this getter working at the end of a simulation, but things crash after a few time steps if I'm trying to extract SubcatchStats repeatedly throughout a simulation, I'm thinking (although could be totally wrong here) that the issue lies with the swmm_freeSubcatchStats() function in SWMM's toolkitAPI.c. After seeing the addition of this function to the API:

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/8413a8619c1b46b64c4151ed0f404fb6987a9f0f/src/toolkitAPI.c#L1540-L1549

I wonder if both swmm_freeOutfallStats() and swmm_freeSubcatchStats() (https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/8413a8619c1b46b64c4151ed0f404fb6987a9f0f/src/toolkitAPI.c#L1265-L1273) are not structured correctly to free up the arrays for each pollutant.

I tried just iterating over the pollutants to free the arrays individually that way, but this doesn't seem to work:
```
void DLLEXPORT swmm_freeSubcatchStats(SM_SubcatchStats *subcatchStats)
//
// Return:  API Error
// Purpose: Frees Subcatchment Stats
// Note:    API user is responsible for calling swmm_freeSubcatchStats
//          since this function performs a memory allocation.
{
    int p;
    
    for (p = 0; p < Nobjects[POLLUT]; p++)
    {
        FREE(subcatchStats->surfaceBuildup[p]);
        FREE(subcatchStats->cPonded[p]);
    }
}
```
My plan is still to restructure the pollutant getters to their own functions (and migrate to SWIG), but I still need/want to have a handle on what's going on with these arrays!

**Comment by bemcdonnell** [comment]
@katmratliff, so I suspect we are seg faulting with this.  Currently we are allocating the memory for the struct in PySWMM, then we are allocating the rest of the memory for the Pollutant array within SWMM.  The helper functions are then created to free the pollutant array.  The original idea of allocating the memory within pyswmm and passing the struct by reference worked well before we were dealing with variable sized arrays (like pollutants in your case).  

The more I think about this, the more I think we should remove the pollutant getters from the stats structures and give them a home of their own.  I am thinking of functions like:

- `swmm_getNodePollut(index, type, **array)`
- `swmm_getLinkPollut(index, type, **array)`
- `swmm_getSubcatchPollut(index, type, **array)`

So what I am thinking resembles the new `swmm_getGagePrecip()` function:

See Example: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/toolkitAPI.c#L980-L1017

here's how it works:
0. (pyswmm) create an array and call the `swmm_getxxxxxxPollut` function passing the array byref
1. We are allocating the memory in SWMM and returning the array populated, 
2. unpacking the array (if needed)
3. then we have a helper function that we call to free the memory (https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/toolkitAPI.c#L1540)

If we adopt this workflow, it will be ready to SWIG wrap right out of the box.

**Comment by bemcdonnell** [comment]
Cross Referencing Issue from SWMM: 
https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/issues/182

**Comment by katmratliff** [comment]
@bemcdonnell makes sense! I'll get to work on restructuring the subcatchment loading/ponding getters and then add others moving forward. Seems I've made a mess of the issues related to this, so feel free to reorganize however makes the best sense or let me know what you'd prefer :)
