### ISSUE TITLE
PySWMM Logo

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#159]

**Comment by bemcdonnell** [comment]
@stroutm @abhiramm7 

Do you like this as a logo? :-D

![image](https://user-images.githubusercontent.com/6105134/44739821-b656b500-aaad-11e8-9328-de75baebd955.png)

**Comment by michaeltryby** [comment]
The snake coming out of the toilet is a definite possibility.

-Michael

**Comment by aerispaha** [comment]
Spent a few months crafting this, one of my best works: 

![pyswmm_logo](https://user-images.githubusercontent.com/6521360/44804567-aa432400-ab8f-11e8-9ac1-d047657f84eb.png)
_"py or die swmm" mspaint / mixed media on canvas_

**Comment by bemcdonnell** [comment]
Hahaha!!!!

@stroutm and @abhiramm7, we might have a winner here!

**Comment by stroutm** [comment]
Perfect! How long til we can get this circulating?

**Comment by bemcdonnell** [comment]
![image](https://user-images.githubusercontent.com/6105134/44808683-b7591680-ab81-11e8-8886-fcac5e36fd27.png)
![image](https://user-images.githubusercontent.com/6105134/44808690-bf18bb00-ab81-11e8-8ace-9a41626d7fa5.png)

**Comment by bemcdonnell** [comment]
Does anyone have anymore ridiculous non-professional ideas for this? :-) (I'm looking at you @michaeltryby and @katmratliff )

**Comment by katmratliff** [comment]
![image](https://user-images.githubusercontent.com/12630578/44809953-36f4de80-ab9e-11e8-8e50-684c71f2d1d7.png)

**Comment by jennwuu** [comment]
![img_0196](https://user-images.githubusercontent.com/28812156/44827378-daff7980-abe0-11e8-8770-566f1f4db628.JPG)

**Comment by bemcdonnell** [comment]
@stroutm, What's the logo looking like?!?! :-) I'm dying to know!

**Comment by DJHostetler** [comment]
Here is the start of an idea for a logo... I am far from a graphic artist. The idea of using the seasnake as a logo ticks both boxes of merging python and swmm.

**Comment by DJHostetler** [comment]
Here is a possible idea for a logo (warning - not a graphic artist). I like the idea of the sea snake logo that merges both python and swmm into one...

![pyswmm_possiblelogo2](https://user-images.githubusercontent.com/6156981/52142245-2c93b080-2626-11e9-97bc-edb98dbd28f1.png)

**Comment by dokzai** [comment]
Hey guys! Here's me and my friend Philip's (@micropipette) attempt at the logos
![Pyswmm Text logo](https://user-images.githubusercontent.com/38355190/81030094-88666e00-8e55-11ea-99d4-99626b3c2262.png)
![Pyswmm Logo](https://user-images.githubusercontent.com/38355190/81030132-aa5ff080-8e55-11ea-8d14-b0fa4c3c1566.png)
![Pyswmm Artboard](https://user-images.githubusercontent.com/38355190/81030134-ac29b400-8e55-11ea-8fd2-52dd72b855a1.png)
![Pyswmm App Logo](https://user-images.githubusercontent.com/38355190/81030137-ad5ae100-8e55-11ea-9a49-b8c311609d10.png)

**Comment by michaeltryby** [comment]
Wow! Nice work!

**Comment by bemcdonnell** [comment]
@dokzai, Nice work! I like the versions that explicitly say "PySWMM" a lot.  I wonder what it would look like if some details were added to show simple aspects of the water cycle.  Maybe rain, then runoff, then pipe networks? :-) Just an idea
