### ISSUE TITLE
Add scrutinizer and quantified code

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#16]
@bemcdonnell could I have admin access to start activating the CI services plus other things things like https://www.quantifiedcode.com/app/project/new and scrutinizer?

**Comment by bemcdonnell** [comment]
@goanpeca This issue has been completed, right?

**Comment by goanpeca** [comment]
@bemcdonnell could you add quantifiedcode.com ?

I could not do it as the organization openwater analytics is not listed. Maybe you can?

**Comment by goanpeca** [comment]
awesome thanks :-)

**Comment by bemcdonnell** [comment]
Should I be adding you as a maintainer to all these third-party tools?

**Comment by goanpeca** [comment]
sure

**Comment by bemcdonnell** [comment]
Done done
