### ISSUE TITLE
Pass friendly error message to user when SWMM engine halts with error

### ISSUE THREAD

**Issue by rkertesz** [OpenWaterAnalytics/pyswmm#160]
This is the error message that I occasionally get in pyswmm:

`Warning (from warnings module):
  File "c:\projectcode\pyswmm\pyswmm\swmm5.py", line 167
    warnings.warn(self._error_message(errcode))
UserWarning: `

On more than one occasion (actually, on two occasions to be exact), I try to figure out what is wrong with my script. Then I realize that there is a problem with my input file and I run the model in EPA SWMM or PC-SWMM and then I fix the problem.

Is it possible to read the error from the report file and present that to the user or to provide the error number to the user or to tell the user "there is a problem with the engine, please check your report file for errors"?

**Comment by dickinsonre** [comment]
That would be nice, but the error messages from the SWMM5 engine can come from many places.  Most fatally when reading  or parsing a line of data. Is it possible to have the whole RPT file come back to the user of PySWMM?

**Comment by bemcdonnell** [comment]
Great ideas! Yes and yes

**Comment by bemcdonnell** [comment]
We have some error handling functions in swmm already that pipe the error number and error message. The problem is is how I filter errors and warnings now. Take a look at SWMM5.py. The error handling checks the error index from swmms enumerated error type... then I fetches the message. It wasn’t thoughtful from the beginning. Truth be told, if something precludes the simulation from starting, and it wasn’t “fatal” in pyswmm’s eyes it will keep going into an infinite loop. This totally needs to be fixed

**Comment by lrntct** [comment]
I do not know exactly how pyswmm does it now, but there is a way to translate the C error codes into a python exception. See this [example](https://bitbucket.org/itzi-model/itzi/src/master/itzi/swmm/swmm_error.py).

**Comment by bemcdonnell** [comment]
@ltntct, we will soon start working on SWIG which incorporates a nice workflow for throwing a python error.  when this is done, it will be much cleaner to throw exceptions!!!

**Comment by bemcdonnell** [comment]
Here’s the error throwing landscape right now for pyswmm  
https://github.com/OpenWaterAnalytics/pyswmm/blob/master/pyswmm/swmm5.py#L142-L167

**Comment by rkertesz** [comment]
Just bumping to keep the thread alive. I can't say that I have any solutions however

**Comment by bemcdonnell** [comment]
It’s coming :-) you just wait!!!

**Comment by dickinsonre** [comment]
Friendly error messages are very important, especially the parser errors which commonly confuse newer users of SWMM5.
