### ISSUE TITLE
Typo in System.py Module 

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#162]
Two errors in System.py module:

In line 22, pyswmm package doesn't include the SystemFlowRouting. In this way,  the syntax of "from pyswmm import Simulation,  SystemFlowRouting" is suggested to be "from pyswmm import Simulation, SystemStats" if we want to extract system statistics.

In line 27,‘’Simulation' has been demonstrated as ‘’sim”. Thus,  the syntax of  "for step in simulation" should be "for step in sim".

**Comment by bemcdonnell** [comment]
@Jiadalee, thanks for spotting the issues in the docs!
