### ISSUE TITLE
pump_statistics['max_flowrate'] gives zero division error

### ISSUE THREAD

**Issue by mehmetbercan** [OpenWaterAnalytics/pyswmm#164]

**Comment by mehmetbercan** [comment]
MaxFlowRate = link.pump_statistics['max_flowrate']
  File "c:\projectcode\pyswmm\pyswmm\links.py", line 960, in pump_statistics
    return self._model.pump_statistics(self.linkid)
  File "c:\projectcode\pyswmm\pyswmm\swmm5.py", line 1334, in pump_statistics
    object_stats, attr) / object_stats.totalPeriods
ZeroDivisionError: float division by zero

**Comment by bemcdonnell** [comment]
Thanks @mehmetbercan.  We can circle back to this bug before making out next release

**Comment by maeehart** [comment]
I also ran into this problem. Are there any suggested workarounds? 

What I currently did was just to add a check if `object_stats.totalPeriods > 0` on line 1334 before dividing by this value and assigning a 0 value to the out_dict if this happens. I do not know if this breaks the whole logic, but at least this does not crash any more.

**Comment by bemcdonnell** [comment]
@maeehart, you proposed a good work around for now. It shouldn't break the logic either.  We're working on the SWMM-API again so I think this problem will be addressed very soon
