### ISSUE TITLE
Building a getter for "StartDryDays" - 

### ISSUE THREAD

**Issue by ngg-osu** [OpenWaterAnalytics/pyswmm#168]
Hi all, I'm new to Git, and this C-Python ctypes wrapper concept

I'm trying to make a getter for the antecedent dry weather period "StartDryDays". Right now, I'm setting up my workflow,  Here are the steps I took.

- Forked my own repository.
- Did "pip uninstall pyswmm" (as advised). 
- download locally onto my laptop (using Github Desktop) into my python folder \lib\site-packages
- Ran "python setup.py develop" (as advised).

But when I ran my own pyswmm-test script, I encountered "Import Error: no module named pyswmm". 

Somehow, pyswmm is not in module list. I'm using miniconda2. It seems pip is the "default" to install packages, but wouldn't it override the developer version? Really hope for help. Thanks!

**Comment by katmratliff** [comment]
Hi @ngg-osu, did you check to be sure hat the correct version of pyswmm is in your path?

**Comment by ngg-osu** [comment]
so, i uninstalled everything and stick to Python 2.7.15 (32bits) on my laptop. Finally worked after I went to window's System Properties > Advanced tab > Environment Variables > Paths for User and system , and entered C:\Python27\ for both. The repository is simply in my C:\Python27\Github...  Now, even a test script on an external USB drive works. Seems like path is the issue. Thanks @katmratliff !

**Comment by bemcdonnell** [comment]
Just so you know, we are not going to guarantee support for py2.7 much longer. Most people are using py3.6 today

**Comment by ngg-osu** [comment]
@bemcdonnell Thanks for the notice. I re-do everything with Python 3.7-32 bits now. With 3.7 installer, there was an option for setting Python into system path , which wasn't available with 2.7 installer. So, I guess that was the issue.

**Comment by bemcdonnell** [comment]
@ngg-osu, I think the steps are documented pretty well in the wiki for contributing:

For running tests locally:
https://github.com/OpenWaterAnalytics/pyswmm/wiki/Author-Contribution-Checklist

For submitting your code for review:
https://github.com/OpenWaterAnalytics/pyswmm/wiki/Dev-Github-Workflow

You'll need to push to your fork and submit a pull request back to here
