### ISSUE TITLE
Is the C source code for compiling SWMM executables available ? 

### ISSUE THREAD

**Issue by NikoZHAI** [OpenWaterAnalytics/pyswmm#171]
Hello people,

I am using the pyswmm api recently. I wonder how the `swmm_getNodeStats` method works in the api. It appears to me that you wrote this method in your own version of C source code and compiled it for the executable. Because I cannot find this method in the latest dev brunch of SWMM on [GitHub](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model). And your swmm executable version is **5.2.0-dev3** of which i cannot find the source code online.

I post this question because I found that the unit of flood volume derived by `swmm_getNodeStats` is cubic meter (I am using SI metrics). And in the generic method `writeNodeFlooding()`, the total flood volume is reported like this: `NodeStats[j].volFlooded * Vcf` [see here](https://github.com/USEPA/Stormwater-Management-Model/blob/e48febe88aa0abfff46390320e4ab2b383e2a2c1/src/statsrpt.c#L482), where Vcf is the volume conversion factor ` Vcf = 28.317 / 1.0e6;` in my case to convert the volume to megalitters. So I think there must be some conversion mechanisms in your `swmm_getNodeStats` method, otherwise the unit would have been wrong...

So I just wish that you could also make your C source code available on github. That will help alot for people like me! I hope that my question is clear enough. Sorry for my broken English. Looking forward to your reaction!

All the best

Niko

**Comment by michaeltryby** [comment]
@NikoZHAI  The source code is available you just need to know where to look 😄 

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/develop/src/toolkitAPI.c#L1019

**Comment by NikoZHAI** [comment]
@michaeltryby Thx! Sorry for the trouble! I got retarded!

**Comment by michaeltryby** [comment]
No problem! Happy to help :smile:
