### ISSUE TITLE
set area

### ISSUE THREAD

**Issue by anneliesesytsma** [OpenWaterAnalytics/pyswmm#176]
I am using PySWMM to look at run-on/ run-off patterns of impervious to pervious catchments. I'm trying to write code that loops through different catchment areas and reports the runoff stats for each combination of catchment areas.  

I'm working on just updating the area for one catchment:
```
with Simulation('data\test4.inp') as sim:
    s1 =  Subcatchments(sim)["S1"]
    print s1.area
    s1.area = 50
    print s1.area
```

Which gives the following error: 

> exception: access violation reading 0x0075CB0C

When I 'read' the file in, it works, but obviously doesn't update the inp file.
```
with Simulation(r'data\test4.inp') as sim:
    s1 =  Subcatchments(sim)["S1"]
    print s1.area
    s1.area = 50
    print s1.area
```

> 100
50

I've made sure the sim is closed (i.e., sim.close()). I checked the docs and it looks like the code I used should work, so I don't know what's causing the block. 

Thanks for any help !
Anneliese

**Comment by bemcdonnell** [comment]
@jennwuu, can you take a look and see if you get the “access violation error”?

@anneliesesytsma, I’m not sure if it is clear- pyswmm doesn’t update the INP file itself. It only updates a parameter in swmms data model

**Comment by jennwuu** [comment]
@bemcdonnell I tested with python 3.7 and v0.4.9dev and I wasn't able to replicate the access violation error.
```
from pyswmm import Subcatchments, Simulation

with Simulation('./model_full_features.inp') as sim:
    s1 =  Subcatchments(sim)["S1"]
    print(s1.area)
    s1.area = 50
    print(s1.area)

**Comment by jennwuu** [comment]
@anneliesesytsma you should see the updated area in the .rpt file that SWMM generates. thanks!

**Comment by anneliesesytsma** [comment]
@jennwuu Got it! Yes, it's updating. Just didn't realize it wasn't updating the inp file...:) Thanks!
