### ISSUE TITLE
Cannot import name DLL_SELECTION

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#177]
Hi:

I'm running the entire Pyswmm simulation by using outside control approach. However,  the error shows that the 'line 26' of swmm5.py cannot import name DLL_SELECTION. Does anyone know how to fix it?
 
![image](https://user-images.githubusercontent.com/30839207/51857157-cf7ac080-22ee-11e9-98c7-bf7c7efa8000.png)

**Comment by abhiramm7** [comment]
Hey can you open a issue in the storm swarm repo.

**Comment by Jiadalee** [comment]
I thought this might be a problem because of Pyswmm engine code. I have posted another specific problem describing it in the swarm repo. Thanks

**Comment by abhiramm7** [comment]
No, it is an error with how I've set up the import. @bemcdonnell can you close this issue.
