### ISSUE TITLE
How to use conduit_statistics?

### ISSUE THREAD

**Issue by adriariu** [OpenWaterAnalytics/pyswmm#179]
Please anybody can tell how to use this feature, I spend all day and only getting a warning and 0 in all parameters. 

This is my code:

```
sim = Simulation('test.inp')
    for stem in sim:
        link = Links(sim)['T1019']
            if link.is_conduit():
                print link.conduit_statistics
```
And the result is:

```
 API Key Error: Object Type Outside Bonds
{'time_capacity_limited': 0.0, 'flow_turns': 0, 'time_in_flow_class': {}, 'peak_flow_date': 0.0, 'time_normal_flow': 0.0, 'time_surcharged': 0.0, 'peak_flow': 0.0, 'flow_turn_sign': 0, 'time_full_upstream': 0.0, 'time_full_flow': 0.0, 'peak_velocity': 0.0, 'peak_depth': 0.0, 'time_courant_crit': 0.0, 'time_full_downstream': 0.0, 'time_inlet_control': 0.0}
```

Anybody can show me an example or tell what I'm doing wrong?

Thanks

**Comment by Jiadalee** [comment]
'for stem in sim:' should be 'for step in sim:'

Also,  can you try'print link.statistics' ?

**Comment by bemcdonnell** [comment]
@adriariu, what version of pyswmm are you using?

**Comment by bemcdonnell** [comment]
@adriariu, also.. 

What Platform and Arch are you running this on?

could you please zip your project files and drop them in this issue? I'd like to recreate your issue

**Comment by adriariu** [comment]
Hi @bemcdonnell,

The versión of pyswmm is:
`pyswmm==0.4.8`
I'm dev Platform and Arch is macOS x64 but it must be deployed on a Ubuntut x64.

Sorry but I'm not allowed to share the data of the project, safty rules... 
If you can share any test file, I will check the difference and tell.

Thanks!

**Comment by abhiramm7** [comment]
Closed due to inactivity.
