### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by morecfd** [OpenWaterAnalytics/pyswmm#186]
Hey 

Would you mind please letting me know how to start using Pyswmm?
I am a new python user.
Seems like pyswmm only works on python 32 bit. So, I just installed python 3.8 32-bit, downloaded Pyswmm, created a python file "ok.py", put an INP file "testmodel.inp" in the same folder, and tried to run this: 
from pyswmm import Simulation

sim = Simulation('./testmodel.inp')
sim.execute()

But it is giving this error : 

Traceback (most recent call last):
  File "E:/Installed/Python38-32bit/ok.py", line 3, in <module>
    sim = Simulation('./testmodel.inp')
  File "E:\Installed\Python38-32bit\lib\site-packages\pyswmm\simulation.py", line 68, in __init__
    self._model = PySWMM(inputfile, reportfile, outputfile, swmm_lib_path)
  File "E:\Installed\Python38-32bit\lib\site-packages\pyswmm\swmm5.py", line 132, in __init__
    self.SWMMlibobj = ctypes.WinDLL(swmm_lib_path)
  File "E:\Installed\Python38-32bit\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

I have also tried miniconda
and tries to run "conda install pyswmm" but unlike what is mentioned in pyswmm.pdf, there is no pyswmm package on conda.

BTW, my OS is win 7 64 bit, but my python version is 32-bit

Can you please advice?
Cheers

**Comment by bemcdonnell** [comment]
See issue #153. And comment

https://github.com/OpenWaterAnalytics/pyswmm/issues/153#issuecomment-392102847

It’s a SWMM openMP dependency issue

**Comment by morecfd** [comment]
**Thank you very much for your reply.** 
This is how things went on:
Try 1. installed Visual C++ Redistributable Packages for Visual Studio 2013: not working
Try 2. installed Visual C++ Redistributable Packages for Visual Studio 2017: not working
Try 3: put vcomp120.dll in my working directory, works fine.

**Comment by bemcdonnell** [comment]
@morecfd This dependency problem will go away in a future version of PySWMM.

**Comment by sjhabedin** [comment]
I am also having the issue. Previously I successfully ran Pyswmm couple of months back. Later I uninstalled Python 3.6 32 bit. Two to three weeks back I reinstalled Python 3.6 32 bit and Pyswmm 0.5 (latest) version. But now I am having the following error while trying to execute an inp file. Any help would be really appreciated. Thanks

Traceback (most recent call last):
  File "C:\Research_SWMM\swmm_execute.py", line 3, in <module>
    sim = Simulation(swmminputfile)
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\simulation.py", line 68, in __init__
    self._model = PySWMM(inputfile, reportfile, outputfile, swmm_lib_path)
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswmm\swmm5.py", line 133, in __init__
    self.SWMMlibobj = ctypes.WinDLL(swmm_lib_path)
  File "C:\Users\JOY\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: [WinError 193] %1 is not a valid Win32 application**

**Comment by bemcdonnell** [comment]
@sjhabedin   Well darn! I thought we fixed this. Let me look into it today when I have a minute. Sorry for the bug. Do you want to try With python 3.7 64bit?

**Comment by sjhabedin** [comment]
@bemcdonnell I haven't tried with Python 3.7 64 bit. Also I don't want to at this moment. If the problem is with Python version or bit size then definitely I will try. So please let me know after you check on the problem. Many thanks for your time

**Comment by bemcdonnell** [comment]
@sjhabedin 

Sorry for the delay here: Install this the Visual C++ Redistributable for Visual Studio 2015. 

https://www.microsoft.com/en-ca/download/details.aspx?id=48145

**Comment by floriandorre** [comment]
Is there any solution for this issue ? I would like to open results generated using pyswmm 0.6.2 but when I load the INP file the flag at the bottom of EPA SWMM software is not green so I can't visualise the results with it. Not sure if my problem is linked to this issue but the difference with both .rpt files is the engine used to execute the simulation

EPA SWMM .rpt file : EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.1.015)
pyswmm .rpt file : EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.3.0.dev0)

I'm running the simulation using Python 3.7 with pyswmm 0.6.2 on Windows 10

**Comment by bemcdonnell** [comment]
@floriandorre I think your comment belongs here: https://github.com/OpenWaterAnalytics/pyswmm/issues/224
