### ISSUE TITLE
Water quality simulation output

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#188]
Is there any way like 'J1.water quality' to get the water quality simulation results for each node? I didn't find any variable for water quality in PySWMM.

**Comment by katmratliff** [comment]
HI @Jiadalee, you can currently access pollutant loading as part of the `outfall_statistics` dict (see [here](https://pyswmm.readthedocs.io/en/stable/reference/nodes.html) for more information. I am planning to write getters/setters for the pollutant load at junctions in the future, if someone doesn't beat me to it!

**Comment by dickinsonre** [comment]
SWMM5 does have pollutant load node and link tables as well.  How are summary tables used in the very useful PySWMM?

**Comment by dickinsonre** [comment]
Hello @Jiadalee is my summary of your main complaint on the SWMM list server the fact that SWMM5 does not have a nice summary OUTFLOW output variable for Storage Nodes as we do for Total Inflow?

Here for reference is my List Server comment 

Hello JIada,
You can graph and make a table of the node water quality and link water quality in SWMM5 by just clicking on the element  Now back to you overflow question, SWMM5 is a link node visual model and we assume the user can see the links into and out of a storage nodes and make the appropriate summing of the outflows. We do show you the Total Inflow to a Node but I think you have a good suggestion,  we should also show the user the sum of the outflows from a storage node as that is a common modeling or modelling need.  Good idea!
Regards,
Robert Dickinson
SWMMinformatics at NCIMM

**Comment by Jiadalee** [comment]
Hi @katmratliff Thanks for your guidance. I tried 'outfall_statistics' but this function doesn't fit want I need. What I need is the TSS time-series data of storage units.

I'm very interested in writing getters/setters for pollutant load at junctions and storage. Can I learn from you and do this work with you together?

**Comment by Jiadalee** [comment]
Hi @dickinsonre Gotta! Thank you for your updates. I appreciate it.

**Comment by katmratliff** [comment]
Hi @Jiadalee, that is great! To give you a sense of how to get started, take a look at these PR's: #170 for PySWMM, and https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/191 for OWA SWMM.

@michaeltryby has been working on developing a new SWIG wrapper for SWMM, which you can take a look at [here](https://github.com/OpenWaterAnalytics/swmm-python). This is the direction where things are headed, so if you are up for it, it makes sense to work on the getters/setters with the SWIG interface file in mind.

**Comment by katmratliff** [comment]
> SWMM5 does have pollutant load node and link tables as well. How are summary tables used in the very useful PySWMM?

@dickinsonre the [node](https://pyswmm.readthedocs.io/en/stable/reference/nodes.html#pyswmm.nodes.Node.statistics) and [link](https://pyswmm.readthedocs.io/en/stable/reference/links.html#pyswmm.links.Conduit.conduit_statistics) statistics contain a lot of useful information, but no pollutant load/water quality reporting at the moment.

**Comment by dickinsonre** [comment]
Okay, @katmratliff I may try my hand at the other tables in the near future after listening to a good PySWMM demo by @Jennifer Wu last week.

**Comment by Jiadalee** [comment]
> Hi @Jiadalee, that is great! To give you a sense of how to get started, take a look at these PR's: #170 for PySWMM, and [OpenWaterAnalytics/Stormwater-Management-Model#191](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/191) for OWA SWMM.
> 
> @michaeltryby has been working on developing a new SWIG wrapper for SWMM, which you can take a look at [here](https://github.com/OpenWaterAnalytics/swmm-python). This is the direction where things are headed, so if you are up for it, it makes sense to work on the getters/setters with the SWIG interface file in mind.

Thanks, I will take a look.

**Comment by katmratliff** [comment]
@Jiadalee, I have this (tentatively) working in [my branch](https://github.com/katmratliff/pyswmm).

You can access current node quality values using, e.g.,
`J1.quality`
and current link quality values with
`C1.quality`

Cumulative link load also accessible with
`C1.totalLoad`

I need to do some additional testing/add documentation/add unit tests before submitting a PR but wanted to share this with you in case it is useful and/or you're interested in testing it as well.

**Comment by dickinsonre** [comment]
It might be also nice to have J1.Load for node loads and the treatment values for each node.

**Comment by katmratliff** [comment]
@dickinsonre agreed.

**Comment by bemcdonnell** [comment]
@katmratliff,

CamelCase is not the most pythonic. Also, “Load” carries other meaning is software. How about something like:

.total_loading
.pollut_quality 

I know I’m late to the game here and I’m sure you’re using this code in your workflow so take my suggestions with a grain of salt. :-)

**Comment by katmratliff** [comment]
@bemcdonnell nope, not too late! Just developing this now so I can use it in my workflows, so now is the perfect time to suggest any and all changes.

**Comment by Jiadalee** [comment]
> @Jiadalee, I have this (tentatively) working in [my branch](https://github.com/katmratliff/pyswmm).
> 
> You can access current node quality values using, e.g.,
> `J1.quality`
> and current link quality values with
> `C1.quality`
> 
> Cumulative link load also accessible with
> `C1.totalLoad`
> 
> I need to do some additional testing/add documentation/add unit tests before submitting a PR but wanted to share this with you in case it is useful and/or you're interested in testing it as well.

**Comment by Jiadalee** [comment]
@katmratliff  Thanks!  I'm working on a new swmm5.dll library which can be used to get the node and link quality for PySWMM. It meets my requirements now but this work looks more complex than what you did.  I'd like to test yours as well.

**Comment by Jiadalee** [comment]
I prefer:
.pollut_loading
.pollut_concentration
