### ISSUE TITLE
Final Water Level

### ISSUE THREAD

**Issue by mebiusvista** [OpenWaterAnalytics/pyswmm#189]
Hi, I have a question about whether we can acquire data about the final water level after each round of simulation.
I see there are commands for accessing the initial volume and average volume after running
`sim.execute()`, is that possible that we can access the final volume as well? I'm trying to use the final volume after each round of simulation as the initial volume for the next iteration, such that I can solve a continuous problem. Thanks!

**Comment by jennwuu** [comment]
Hi @mebiusvista, you can step through the simulation in a for loop and access the node depth information each simulation time step. 

Check out this example: https://pyswmm.readthedocs.io/en/latest/tutorial/tutorial.html#nodes

**Comment by Jiadalee** [comment]
It seems your goal is not to use the volume of the last step as the input to the next step. so you want to use use the final volume of the last simulation as the input to next simulation?

If so, just use `with simulation as sim` to run your model and then, save your first simulation volume as a np.array. and then call this np.array to run you next round simulation.
