### ISSUE TITLE
latest version of v0.4.9.dev0 seems unstable

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/pyswmm#192]
I tried a SWMM model run and it produced a very large high routing error. More info to follow.

**Comment by dickinsonre** [comment]
do you have a copy of the model that you can show @jennwuu here?

**Comment by jennwuu** [comment]
@dickinsonre It seems like the simulation setters for start_time and end_time are not being set properly 
[pyswmm_testing_july12_2019.zip](https://github.com/OpenWaterAnalytics/pyswmm/files/3386432/pyswmm_testing_july12_2019.zip)

**Comment by bemcdonnell** [comment]
@jennwuu I have the fix for this! 
![image](https://user-images.githubusercontent.com/6105134/61128701-4a3c3000-a478-11e9-86f2-351dc869e149.png)
