### ISSUE TITLE
Library crashes when INP file has the option RULE_STEP defined as 00:00:00

### ISSUE THREAD

**Issue by antviro** [OpenWaterAnalytics/pyswmm#205]
**Describe the bug**
I was having crashes (segmentation fault) in inp files which were running in SWMM without problems. And I have detected that the option RULE_STEP was the one causing the segmentation faults. That option was added as default value by the SWMM and it was defined as 00:00:00
RULE_STEP 00:00:00

Removing or commenting it (with ;;) makes the library work without any problem.

**To Reproduce**
import pyswmm
inpFile="Example1_cop.inp"
with pyswmm.Simulation(inpFile) as sim:
      nodes = pyswmm.Nodes(sim)
      for iN in nodes:
            print iN.nodeid

**Expected behavior**
I upload a swmm inp based on one of the official examples if the line ;;RULE_STEP is uncommented the error hapens, otherwise it runs properly:
With the line commented:
9
10
13
14
15
16
17
19
20
21
22
23
24
18
Uncommenting such line:
/home/username/.local/lib/python2.7/site-packages/pyswmm/swmm5.py:167: UserWarning: 
  warnings.warn(self._error_message(errcode))
Segmentation fault

I report it not only to be solved but so that other users know that they can go on just commenting such line...

**Desktop (please complete the following information):**
 - OS: Linux (Debian)
 - Python Version: Python 2.7.13 inside of ipython 5.8.0
 - PySWMM Version: (0.4.8)

[Example1_cop.inp.gz](https://github.com/OpenWaterAnalytics/pyswmm/files/3471084/Example1_cop.inp.gz)

**Comment by bemcdonnell** [comment]
Pyswmm-0.4.8 uses SWMM 5.1.12. SWMM 5.1.12 did not have support for RULESTEP. Try upgrading to pyswmm-0.5.0.

**Comment by bemcdonnell** [comment]
Also, @antviro, we are no longer guaranteeing support for python 2!
