### ISSUE TITLE
Node and link water quality features

### ISSUE THREAD

**Issue by katmratliff** [OpenWaterAnalytics/pyswmm#206]
Build out the node and link access to pollutant/water quality values. I am actively working on this.

**Comment by bemcdonnell** [comment]
@katmratliff, how is this going? Should we try to couple this into a new pyswmm release?

**Comment by katmratliff** [comment]
@bemcdonnell that sounds great. I've got the code working and ready to go in my [branch](https://github.com/katmratliff/pyswmm), just need to add some tests. I was waiting to submit a PR until this SWMM [PR](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/262) was merged. Also, how are you an @jennwuu building the x64 binaries?

**Comment by jennwuu** [comment]
@katmratliff the x64 and x32 binaries for mac and linux are uploaded under draft release for successful build on the develop branch. The x64 and x32 binaries for windows are under artifacts on appveyor.

**Comment by katmratliff** [comment]
@jennwuu cool, as in I don't need to compile them locally? I'll just need to pull out what gets built and stick them in my pyswmm branch?

**Comment by jennwuu** [comment]
@katmratliff exactly! :D
