### ISSUE TITLE
files share same names

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#210]
Hi, I'm running over 10-year continuous simulation by using pyswmm on Colab.  I  simply typed the codes below:

with Simulation("gdrive/My Drive/SH Models/Model.INP") as sim:
    print("System units: {}".format(sim.system_units))
    for step in sim:
      pass
    sim.report()

However, it always gives me an error showing 'files share the same names'. Does anyone know how to fix it? thanks

**Comment by bemcdonnell** [comment]
@jiadalee, please post the trace back error so we can see it

**Comment by Jiadalee** [comment]
here is the screenshot for error
![image](https://user-images.githubusercontent.com/30839207/65286843-41ae4880-dafe-11e9-80f9-460002380d12.png)

**Comment by Jiadalee** [comment]
I copied the same codes to Pycharm and run it on Pycharm. This still gives me an error. My model has 10-year precipitation inputs. I can run my model in SWMM GUI but doesn't work on PySWMM. I'm wondering if PySWMM can run a long-term continuous simulation or not. Does anyone have the same issue? Or, anyone has tried long-term continuous simulation by using PySWMM? I will appreciate your comments

![image](https://user-images.githubusercontent.com/30839207/65376999-088fe880-dc64-11e9-9e8c-131f53352242.png)

**Comment by bemcdonnell** [comment]
What version of python / pyswmm are you using on what platform?

**Comment by Jiadalee** [comment]
I'm using pyswmm 5.0.1 on Win 10 @bemcdonnell

**Comment by bemcdonnell** [comment]
```python
with Simulation("gdrive/My Drive/SH Models/Model.INP",
                "gdrive/My Drive/SH Models/Model_test.rpt",
                "gdrive/My Drive/SH Models/Model_test.out") as sim:
    print("System units: {}".format(sim.system_units))
    for step in sim:
        pass
```
@Jiadalee, try this

**Comment by bemcdonnell** [comment]
@Jiadalee, it looks like you have the RPT/OUT files open already in write mode and SWMM can't re-open them.

**Comment by Jiadalee** [comment]
Can you close this issue? I already fixed it. Thanks @bemcdonnell
