### ISSUE TITLE
python 64-bit still not working

### ISSUE THREAD

**Issue by BrianN92** [OpenWaterAnalytics/pyswmm#216]
I was excited to hear your announcement of pyswmm [0.5.0](https://www.openswmm.org/Topic/19798/pyswmm-0-5-0-released-owa-swmm-5-2-0-dev5-released) so I went to download the latest version. However, after I ran the code with 64-bit python, the same problem was still there: "%1 is not a valid Win32 application". What do I need to do to fix it? 

Thank you!

Desktop :
 - OS:  Windows
 - Python 3.6-x86

**Comment by bemcdonnell** [comment]
@BrianN92 https://github.com/OpenWaterAnalytics/pyswmm/issues/186

**Comment by BrianN92** [comment]
Thanks for replying. I don't think the vcomp140.dll works for me. I still ran into the same issue after downloading the dll file...

**Comment by BrianN92** [comment]
Well I think I have solved this issue after placing vcomp140.dll in the same work directory and changing the pyswmm engine to 'swmm5-x64'. Thanks for help! :)

**Comment by jennwuu** [comment]
@BrianN92 out of curiosity, is there a reason why you're using v0.5.0 instead of v0.6.0?
