### ISSUE TITLE
Cumulative inflow only available for outfalls

### ISSUE THREAD

**Issue by kmmacro** [OpenWaterAnalytics/pyswmm#218]
This function is a property of outfalls, but node_inflow could be applied to any type of node https://github.com/OpenWaterAnalytics/pyswmm/blob/028fc9a2c731bed4129ee100e295900d989867fd/pyswmm/nodes.py#L756-L767

**Comment by dickinsonre** [comment]
Cumulative flow at any node would be a very useful graph or statistic.  Outfalls are not the only important component of a network - except for loading to creeks, rivers or lakes.
