### ISSUE TITLE
For rewriting swmm inp files

### ISSUE THREAD

**Issue by wujinshi** [OpenWaterAnalytics/pyswmm#220]
Hi, all
I'm a new user of pyswmm, I want to know if pyswmm can rewrite inp files by a template file.

**Comment by bemcdonnell** [comment]
Pyswmm is used mostly for communicating with a running simulation and talking to SWMM’s data model directly. You can update parameters before a simulation is started but it doesn’t save results back to the file. If you want to save an INP file, check out the SWMMIO project.
