### ISSUE TITLE
Get current timeseries value

### ISSUE THREAD

**Issue by bdb3m** [OpenWaterAnalytics/pyswmm#223]
Is there a way to get the current/past/future values from timeseries (e.g. rainfall) while stepping through a simulation? For background, I'm using pyswmm as an environment for reinforcement learning and would like to pass values from the timeseries as part of the model state. Right now I'm using the current timestamp to get the timeseries value from a separate csv file, but would like to get that directly from pyswmm if possible. Thanks!

**Comment by Jiadalee** [comment]
@bdb3m When you step through your simulation, what about temporarily storing time-series data as an array and then passing them to your agent?

**Comment by bdb3m** [comment]
Thanks @Jiadalee. That works for something like the current depth of a node but not for input time series values. As far as I know, time series values from the input table are not available through pyswmm. There may not be a clean way to get them from pyswmm. In that case my work around is ok. I think it would be convenient/useful to have some pyswmm functionality like raingage.current_value which would return the value from a time series at the current time step in the simulation.

**Comment by bemcdonnell** [comment]
@bdb3m, this sounds like a really cool application using pyswmm combined with reinforcement learning. I’d love to learn more!

At the moment there are no getters for the SWMM timeseries objects in SWMM’s data model. I might encourage you at this time to parse the timeseries from the INP and store them in your own data model for now. This way you could access past/present/future values by means of interpolation for whatever you choose. Does this help?

**Comment by bdb3m** [comment]
Thanks for the reply @bemcdonnell! pyswmm has been working really well as a custom openai gym environment for reinforcement learning because of the ability to run a simulation step-by-step. The overall idea is to get an RL agent to learn how to control the orifices, pumps, etc. in a SWMM model in order to manage flows, flooding, or water quality. 

I like the idea of parsing and storing the timeseries from the input file. Sounds a little cleaner than using the timestamp to read them from a separate csv. Thanks!

**Comment by bemcdonnell** [comment]
@bdb3m, awesome! I am going to close this issue.  If you feel compelled to share more in the domain of RL, feel free to send me an email at bemcdonnell(aaattt)gmail.com.  I think this field is fascinating!
