### ISSUE TITLE
How to change Build 5.3.0.dev0 to 5.1.013 to make it consistant with SWMM GUI

### ISSUE THREAD

**Issue by zxyzmbc1030** [OpenWaterAnalytics/pyswmm#224]
Hi everyone,

I run the simulation in pyswmm environment and in EPA SWMM GUI. The results (e.g., flow routing error, volume, etc) are somehow different. I check the .rpt files for both and find that the first line in one is "EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.3.0.dev0)" for pyswmm and the other is "EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.1.013)". 
Do you think it is the reason for the different results or is there any other possibility?

Thanks a lot.

**Comment by bemcdonnell** [comment]
@zxyzmbc1030, do you mind zipping your files you and sharing there here in the issue?

**Comment by zxyzmbc1030** [comment]
> @zxyzmbc1030, do you mind zipping your files you and sharing there here in the issue?

Hi bemcdonnell, thanks for the reply. Sorry I now cannot provide the data source due to some privacy issues. But I test it again and find the differences become small as the model errors get  the same (to say, below 2%). Also, the time step is somewhat strange in pyswmm. I set the sim.step_advance as 60 and I print sim.current_time. It shows that the simulation step is not exactly 60 sec.

Thank you very much.

**Comment by katmratliff** [comment]
@zxyzmbc1030, what platform are you using to run pyswmm?

**Comment by zxyzmbc1030** [comment]
> @zxyzmbc1030, what platform are you using to run pyswmm?

Spyder for Python 3.7.4

**Comment by katmratliff** [comment]
@zxyzmbc1030 on Windows?

**Comment by bemcdonnell** [comment]
@zxyzmbc1030,

I'm assuming you are allowing a variable time step.  At this time PySWMM does not "add" timesteps to the process. Therefore, if you use `sim.step_advance(...)` it will intervene on or just after the next overlapping routing step.  If you step advance is set to 300 seconds and your routing step is 30 seconds (but you are allowing variable step) your model might not be solving on a 13 second timestep.  If this is the case your model might stop 305 seconds after your last intervening step.

**Comment by zxyzmbc1030** [comment]
> @zxyzmbc1030 on Windows?
Yes

**Comment by zxyzmbc1030** [comment]
> @zxyzmbc1030,
> I'm assuming you are allowing a variable time step.  At this time PySWMM does not "add" timesteps to the process. Therefore, if you use sim.step_advance(...) it will intervene on or just after the next overlapping routing step.  If you step advance is set to 300 seconds and your routing step is 30 seconds (but you are allowing variable step) your model might not be solving on a 13 second timestep.  If this is the case your model might stop 305 seconds after your last intervening step.

Sorry, I did not get your idea. I also find that for 13 hours' duration with 1 min time step, I only got a series of 728 records (depth, volume, etc) in pyswmm. However, in SWMM we should get 13h*60min=780 records for a node.

**Comment by zxyzmbc1030** [comment]
Hi, I can use the cumulative_inflow for the total volume, so avoid the time step problem. But I still have no solution for changing the engine version in pyswmm. When I change the swmm5.dll file in pyswmm package, it gives the error as:
OSError: [WinError 126] The specified module could not be found.
I think it's because the useful module is the swmm5-x64.dll, but I don't have the one with 5.1.013 engine version. Do you have any solutions for this problem? Thanks a lot. It confused me for a really long time...

**Comment by bemcdonnell** [comment]
You upgraded pyswmm and it’s looming for VCOMP*.dll 

Try this https://github.com/OpenWaterAnalytics/pyswmm/issues/186

**Comment by zxyzmbc1030** [comment]
> You upgraded pyswmm and it’s looming for VCOMP*.dll
> Try this #186

I think the version I use is the latest one: pyswmm 0.6.0.
So which part should I update? Thanks

**Comment by zxyzmbc1030** [comment]
> You upgraded pyswmm and it’s looming for VCOMP*.dll
> Try this #186

Also, where can I download vcomp.dll. Thanks.

**Comment by bemcdonnell** [comment]
@zxyzmbc1030 https://github.com/OpenWaterAnalytics/pyswmm/issues/186#issuecomment-533308936

**Comment by bemcdonnell** [comment]
@dickinsonre Do you think there are any options for releasing the EPA-GUI with a drop down box allowing people to open their results in the UI from a different model?  We aren't maintaining that here at all so @floriandorre, I'm not sure what to tell you at the moment.  There are some libraries available to open your results in Python if those would be helpful.

**Comment by floriandorre** [comment]
Thanks @bemcdonnell, for now, I will just use the python solution since there is no way to open the results with EPA GUI but this improvement could be really useful

**Comment by michaeltryby** [comment]
@bemcdonnell The general consensus is that users want their results to be compatible with the "EPA" version of SWMM. I would argue that numbering OWA SWMM "5.3.0.dev0" is aspirational on your part. You and I both know all about semantic versioning. Users don't seem to understand what your version numbering is indicating. 

For better or worse, the body of work here is more of a patch to EPA SWMM than anything else. I think we should just treat it that way -- all other things being equal OWA SWMM is EPA SWMM with an extended API. This is advantageous because users get flexibility of the extended API while getting the "correct" results that they trust.

**Comment by floriandorre** [comment]
> Thanks @bemcdonnell, for now, I will just use the python solution since there is no way to open the results with EPA GUI but this improvement could be really useful

Just fount out that this was possible by putting the results ini value to 1.

Steps:
- open the inp used for the pyswmm simulation
- save it with the GUI
- edit the ini generated
Replace those settings
```ini
[Results]
Saved=0
Current=1
```
by those ones
```ini
[Results]
Saved=1
Current=1
```
- re-open the inp

Then the GUI detects the results
