### ISSUE TITLE
get the system flooding volume and total infow

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#225]
Hi, does anyone know how to get the system flooding volume and system total inflow?

**Comment by Jiadalee** [comment]
Sorry, I already fixed this problem. However, I got a new question. I'm wondering about the difference between the 'external_inflow' and  'II_inflow' in the stats output?

**Comment by dickinsonre** [comment]
RDII flow is called I and I or Infiltration and Inflow.  External Inflow comes from a Time Series or External inflow to a node.  It is not Dry Weather flow, runoff or RDII flow.

**Comment by Jiadalee** [comment]
Thanks. I found the 'external_inflow' variable is from the system routing_stats in pyswmm, but not from the node statistics . Does this mean the  'external_inflow' of pyswmm is the same as the system inflow?

**Comment by Zeeck972** [comment]
Hi, can you tell me how to get these values?

**Comment by Jiadalee** [comment]
@Zeeck972 Pls try these codes  below:
`sys_flooding_volume = [ ]  # create an empty list for flooding volume`
`sys_flooding_volume. append(system_routing.routing_stats['flooding'])  #store flooding volume to the list`
`print(sys_flooding_volume)  #print the data`

Doing the same for accessing the accumulative system inflow. Pls note this only gives you the accumulative system flooding volume or inflow. You might need to manually calculate the relative flooding volume for each timestep.

I don't think this is an issue for the current PySWMM version. It is just a leftover discussion. Can you close this problem @bemcdonnell
