### ISSUE TITLE
set-up the LID catchment area

### ISSUE THREAD

**Issue by Jiadalee** [OpenWaterAnalytics/pyswmm#226]
Hi:

My SWMM model has over 1000 catchment. I wanna assign the LID area to each catchment as an iterative step-wise. However, I found there is no LID area in the control parameters of pyswmm.  Can anyone direct me to fix this issue? Thanks

**Comment by jennwuu** [comment]
@Jiadalee are you modifying lid unit area for existing predefined lids? If so, you can update unit_area within LidGroup. https://pyswmm.readthedocs.io/en/stable/reference/lidgroups.html

**Comment by Jiadalee** [comment]
@Jiadalee Not really. I just want to use the setter and getter functions for lid unit area. They seem enabled in this link. Thank you for sharing.
