### ISSUE TITLE
Get Unit of Measurement of results and statistics

### ISSUE THREAD

**Issue by tscheuch** [OpenWaterAnalytics/pyswmm#228]
Hi! Does anyone know how to get the units of results values? Specially the ones that are cumulative (statistics)!

Thanks a lot,

**Comment by katmratliff** [comment]
hi @tscheuch, values are reported from pyswmm are the measurement units as defined in the .inp file. You can also use the Simulation module to retrieve flow units and system units. See the following examples below.

``` python
>>> from pyswmm import Simulation
>>>
>>> with Simulation('swmm_model.inp') as sim:
...     print("The flow units are " + sim.flow_units)
>>>
>>> The flow units are CFS
```
and
``` python
>>> from pyswmm import Simulation
>>>
>>> with Simulation('swmm_model.inp') as sim:
...     print("The system units are " + sim.system_units)
>>>
>>> The system units are US
```
