### ISSUE TITLE
Pollutant treatment enhancements

### ISSUE THREAD

**Issue by bemason** [OpenWaterAnalytics/pyswmm#230]
Currently in SWMM you are limited by the math functions, treatment equation format, hydraulic parameters, etc. when you want to run treatment in a simulation. I want to create a new toolbox that will allow more flexibility and options when running treatment. For example, allowing you to use whatever treatment equation you want and then perhaps providing different Python solvers to solve those equations.  Along with the new setters that Katherine made, I want to either use some kind of pollutant setter, or create a new custom_treat() function that when called, bypasses SWMM's treatmnt_treat() equation and uses the user-defined treatment instead. I am still not exactly sure which is the best method yet, I am combing through the comb to determine that. This will probably be the first chapter of my dissertation, so I am committed to figuring this out!

**Comment by bemcdonnell** [comment]
@bemason, great idea! Can you imagine up a flow diagram that shows how your propose to interact with the running simulation? Are you proposing to manage mass balances outside of swmm?

**Comment by bemason** [comment]
@bemcdonnell @katmratliff No, I plan to let SWMM do mass balances and routing. Talking with @jennwuu, she suggested we create an API function to do something similar to treatment_treat function call where one of the parameter input is user specified removal rate. Setting this removal rate would be similar to the target_setting function.

To help me follow this potential option, I wrote some example code (see bottom of message). I think we would want to hide some of that code and not expect users to write all of that, but for now, this is my thought process! Pros and cons for this approach:

_Pros:_ 
1. Allows SWMM to still route pollutants
2. Allows SWMM to do other pollutant accumulations/mass balance
3. Don’t have any tilmestep issues
4. Don’t need setter for pollutant concentration
5. Bypasses SWMM’s mathexpr_eval() function which limits the math functions available

_Cons:_
1. Doesn’t allow you to directly set pollutant concentration if you know it (but could add a separate setter for that if that’s someone’s goal, for example, if they have pollutant data already for their network?)
2. Only works for nodes.

I do want to be able to deal with subcatchments as well, so that we can do more treatment for LIDs (so that treatment is more than percent removal). I plan to come up with some ideas for the subcatchments and links as well. For the links, I was also wanting to be able to add pollutants to the network from erosion.

Example code:
`## Example 1:
from pyswmm import Simulation, Nodes

with Simulation('test.inp') as sim:
	n1 = Nodes(sim)["N1"]
    for step in sim:
        n1.removal_setting  = 0.8   #simple case with contant percent removal

## Example 2:
from pyswmm import Simulation, Nodes

with Simulation('test.inp') as sim:
    n1 = Nodes(sim)["N1"]
    for step in sim:
        dt = swmm_getCurrentTimestep()   #does this exist?
        cO = swmm_getNodePollut("N1", 1) #get current conc.
        cOut = cO - 0.1*(cO**2.2)*dt     #nth order reaction
        cOut = max(0.0, cOut)
        R = 1.0 - cOut/cO
        n1.removal_setting  = R 

"""Example Output:
1. dt = 1 seconds
2. cO = 5 mg/L
3. cOut = 1.55
4. R = 0.69"""`

**Comment by dickinsonre** [comment]
Great ideas @bemason However, I would caution against going against the mass balance routines of SWMM5 - it is very easy to get the wrong masses if you do not follow LAR's mass balance recipes.

There are already 31math expressions in the code in MATHEXPR.C though some of the trig functions seem less than useful.  You can actually add functions to MATHEXPR.C so IMO, starting from scratch is not 

What is would like to see is more process variable types - PVMAX is currently 5.

More interaction between water quality constituents would be super.  For example, more complex nutrients, dissolved oxygen, temperature effects.   See this recent paper by Dirk et all at ICWMM 2020  https://www.icwmm.org/Archive/2020-C029-07/kathea-development-of-a-model-based-risk-and-potential-map-for-the-use-of-thermal-energy-in-wastewa on you can add temperature to the SWMM5 code.

Math functions in SWMM5  
char *MathFunc[] =  {"COS", "SIN", "TAN", "COT", "ABS", "SGN",
                     "SQRT", "LOG", "EXP", "ASIN", "ACOS", "ATAN",
                     "ACOT", "SINH", "COSH", "TANH", "COTH", "LOG10",
                     "STEP", NULL};

**Comment by bemason** [comment]
@dickinsonre I understand that. I did not plan to bypass SWMM's mass balance or routing. I just want to be able to do other treatment equations, like differential equations (which I do not think would work in mathexpr.c nor does SWMM have the solvers to solve them to my knowledge) , and more complex treatment that is not supported currently. So the thought is that that will run in Python and then provide the new removal number for SWMM to use for the math balancing.  Do you think that still would not work?

**Comment by dickinsonre** [comment]
Yes, that will work.  Good luck.  You might need more hydraulic information to go to your external gerRemoval.  Volume, velocity?

**Comment by bemason** [comment]
With the help of @jennwuu and @abhiramm7, I have developed a method to provide enhanced pollutant treatment capabilities for utilization in PySWMM. Now, in PySWMM, users can run their own external treatment and set the pollutant concentration in SWMM for SWMM to do mass balance and route the pollutant. This method allows the user to do that during any timestep or for the entire simulation. 

This method requires only a few changes to the PySWMM Python code, most of the changes are in the SWMM C code. This method results in the following changes to the PySWMM Python code:
-Adds a function in swmm5.py: setNodePollutant() which allows the user to set the pollutant concentration they want SWMM to use as Node[j].externalQual[p].
-Adds a variable in toolkitapi.py: externalTreatment = 5 under the Class NodeParams

Some simple tests shows this method works. I am going to start rigorous testing this week. You can find my edits to the PySWMM code on my Github here: https://github.com/bemason/pyswmm. To see the changes needed in the C code, see this post: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/issues/277. I am open to feedback and suggestions. Thanks all.

**Comment by bemason** [comment]
@bemcdonnell which branch should I make a pull request on? Thanks!

**Comment by bemcdonnell** [comment]
@bemason `develop` please!

**Comment by abhiramm7** [comment]
Addressed in https://github.com/OpenWaterAnalytics/pyswmm/pull/357
