### ISSUE TITLE
Swmm5.py update example in docs 

### ISSUE THREAD

**Issue by Argantonio65** [OpenWaterAnalytics/pyswmm#231]
When using the pyswmm5 simulation routine from pyswmm, the simulation seems to be successful, and provides the same report file as running directly with the SWMM gui. However, when trying to open the binary output file with swmmtoolbox, the following error appears:

```
ValueError: 
*
*   There are zero time periods in the output file.
*
```
See the code here with attached exp1.inp
```python
from pyswmm import swmm5
import swmmtoolbox.swmmtoolbox as tb

#%% SIMULATION
swmm_model = swmm5.PySWMM(r'exp1.inp', r'exp1.rpt', r'exp1.out')
swmm_model.swmm_open()
swmm_model.swmm_start()

while True:
    time = swmm_model.swmm_step()
    if (time <= 0.0):
        break
swmm_model.swmm_end()
swmm_model.swmm_report()
swmm_model.swmm_close()
#%%
var = tb.listvariables(r'exp1.out')
```

On the contrary, when using:
```python
import pyswmm as pys
import swmmtoolbox.swmmtoolbox as tb

with pys.Simulation(r'exp1.inp') as sim: 
    for step in tqdm(sim):
        continue 

var = tb.listvariables(r'exp1.out')
```
The generated binary output file exp1.out, can be successfully queried by swmmtoolbox.

Did anybody encounter the same error? What could be the reason for this difference?

[exp1.zip](https://github.com/OpenWaterAnalytics/pyswmm/files/4377229/exp1.zip)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python Version [Python 3.7-x86]
 - PySWMM Version [v0.6.0]

**Comment by bemcdonnell** [comment]
@Argantonio65, I don't typically suggest people run PySWMM with the lower-level api (by importing swmm5).  

I suggest one of the methods found in the Simulation: https://pyswmm.readthedocs.io/en/stable/reference/simulation.html

But if you want to, what happens if you comment out

```python
#%% SIMULATION
swmm_model = swmm5.PySWMM(r'exp1.inp', r'exp1.rpt', r'exp1.out')
swmm_model.swmm_open()
swmm_model.swmm_start()

while True:
    time = swmm_model.swmm_step()
    if (time <= 0.0):
        break
swmm_model.swmm_end()
#swmm_model.swmm_report() # <------- COMMENT ME OUT!
swmm_model.swmm_close()
```

**Comment by Argantonio65** [comment]
@bemcdonnell Thanks for the answer. With the .swmm_report() commented the same error is generated. Also, I could check that the file .rpt is still generated.

**Comment by bemcdonnell** [comment]
@Argantonio65, i wonder if the OUT file is being closed properly.  Just for a quick test - can you run it with the swmmtoolbox reader in a separate script?

**Comment by Argantonio65** [comment]
Running the swmmtoolbox from a different script does not change the issue.

Only, when running the swmm model from the Simulation approach, the .out can be successfully accessed. 

Nevertheless, I think you are right, the .out and .rpt files are not being closed properly with ```swmm_model.swmm_close()```
If I try to delete the files with the Ipython console (spyder) still open I get a: "files are being used". 

However, the error seems to come from how the .out file is written, the output file generated from the Simulation approach is different from the swmm5 approach. Find attached an example for both (with the same model):
[BinaryOutputExamples.zip](https://github.com/OpenWaterAnalytics/pyswmm/files/4387888/BinaryOutputExamples.zip)

**Comment by bemcdonnell** [comment]
Here are the lines of code called when you instantiate the Simulation object (either using the `with` context manager or as normal.  When you start an iterator on the simulation object, it starts and ends your sim.  It does the cleanup for you as well so the user does not need to.  Is it possible for you to simply use the context manager?

https://github.com/OpenWaterAnalytics/pyswmm/blob/d3b7e79d97e68dc35ab828e135152ff569d0fc8a/pyswmm/simulation.py#L63-L152

**Comment by michaeltryby** [comment]
@Argantonio65 Have you tried this? 

`swmm_start(true);`

**Comment by bemcdonnell** [comment]
> @Argantonio65 Have you tried this?
>
>swmm_start(true)

@michaeltryby I think that will do it... That's how the `Simulation` object manages it itself:

https://github.com/OpenWaterAnalytics/pyswmm/blob/d3b7e79d97e68dc35ab828e135152ff569d0fc8a/pyswmm/simulation.py#L114

**Comment by Argantonio65** [comment]
Indeed, the use of 

``` .swmm_start(True) ```

made it work. I see that this is shown in the context manager of simulation.py, apologies.

We can then close the issue. @bemcdonnell mentioned that the use of swmm5.py is discouraged in favor of simulation.py, so people might not use it. However, I think it would be better if the small description at swmm5.py for the PySWMM class is updated with .swmm_start(True):

```python
class PySWMM(object):
    """
    Wrapper class to lead SWMM DLL object.
    This allow performing operations on the SWMM object that is created when
    the file is being loaded.
    PySWMM can be run in two different modes:
    Mode 1: Execute simulation without any intervention
    * Open the Input file using swmm_open()
    * Execute the simlation without intervening swmmExec()
    * then close calling swmm_close()
    Examples:
    >>> swmm_model = PySWMM(r'\\.inp',r'\\.rpt',r'\\.out')
    >>> swmm_model.swmm_open(True)
    >>> swmm_model.swmmExec()
    >>> swmm_model.swmm_close()
```

Thanks

**Comment by bemcdonnell** [comment]
@Argantonio65, we can update the docs to have True. I’ll leave this issue open until then
