### ISSUE TITLE
Differences on Final Stored (Routing Continuity)

### ISSUE THREAD

**Issue by tscheuch** [OpenWaterAnalytics/pyswmm#234]
Hi!
I am working on two SWMM models, one with groundwater and one without.
When I study the continuity analysis I obtain different values for the Final Stored from those reported by the .rpt file than those obtained using system_routing.routing_stats.

Does anyone have the same problem or know why I get different values?

**Comment by bemcdonnell** [comment]
@tscheuch Could  you post some numbers for us to look at?  I'm interested in knowing what kind of magnitude difference there could be.

**Comment by tscheuch** [comment]
**For the model without groundwater:**

On the .rpt file:

**************************        Volume         Depth
  Runoff Quantity Continuity     hectare-m            mm
  **************************     ---------       -------
  Total Precipitation ......         0.293       266.000
  Evaporation Loss .........         0.012        10.614
  Infiltration Loss ........         0.067        60.455
  Surface Runoff ...........         0.214       194.775
  Final Storage ............         0.000         0.163
  Continuity Error (%) .....        -0.002
  
  
  **************************        Volume        Volume
  Flow Routing Continuity        hectare-m      10^6 ltr
  **************************     ---------     ---------
  Dry Weather Inflow .......         0.000         0.000
  Wet Weather Inflow .......         0.214         2.143
  Groundwater Inflow .......         0.000         0.000
  RDII Inflow ..............         0.000         0.000
  External Inflow ..........         0.000         0.000
  External Outflow .........         0.000         0.000
  Flooding Loss ............         0.000         0.000
  Evaporation Loss .........         0.000         0.000
  Exfiltration Loss ........         0.104         1.043
  Initial Stored Volume ....         0.000         0.000
  Final Stored Volume ......         0.110         1.100
  Continuity Error (%) .....         0.000

With system_routing.runoff_stats 

{'drains': 0.0,
 'evaporation': 116.76731270162246,
 'final_snow_cover': 0.0,
 'final_storage': 0.16302658543985385,
 'infiltration': 665.0743417845243,
 'init_snow_cover': 0.0,
 'init_storage': 0.0,
 'routing_error': -0.24969199845736867,
 'rainfall': 266.0000000000004,
 'runoff': 2142.7650244959523,
 'runon': 0.0,
 'snow_removed': 0.0}

Everything OK so for, but with the routing stats:

With system_routing.routing_stats:

{'dry_weather_inflow': 0.0,
 'evaporation_loss': 0.0,
 'external_inflow': 0.0,
 'final_storage': 67601.63662630794,
 'flooding': 0.0,
 'groundwater_inflow': 0.0,
 'II_inflow': 0.0,
 'initial_storage': 0.0,
 'outflow': 0.0,
 'routing_error': 9.999999999999999e-05,
 'reacted': 0.0,
 'seepage_loss': 1043.0898303873662,
 'wet_weather_inflow': 2142.7650244958913}

**Comment by tscheuch** [comment]
For the model with groundwater:

The .rpt file:

**************************        Volume         Depth
  Runoff Quantity Continuity     hectare-m            mm
  **************************     ---------       -------
  Total Precipitation ......         0.293       266.000
  Evaporation Loss .........         0.012        10.579
  Infiltration Loss ........         0.067        60.455
  Surface Runoff ...........         0.214       194.775
  Final Storage ............         0.000         0.198
  Continuity Error (%) .....        -0.002
  
  
  **************************        Volume         Depth
  Groundwater Continuity         hectare-m            mm
  **************************     ---------       -------
  Initial Storage ..........         5.810      5810.000
  Infiltration .............         0.067        66.500
  Upper Zone ET ............         0.000         0.044
  Lower Zone ET ............         0.000         0.000
  Deep Percolation .........         0.007         6.825
  Groundwater Flow .........        -0.021       -21.018
  Final Storage ............         5.891      5890.656
  Continuity Error (%) .....        -0.000
  
  
  **************************        Volume        Volume
  Flow Routing Continuity        hectare-m      10^6 ltr
  **************************     ---------     ---------
  Dry Weather Inflow .......         0.000         0.000
  Wet Weather Inflow .......         0.214         2.143
  Groundwater Inflow .......        -0.021        -0.210
  RDII Inflow ..............         0.000         0.000
  External Inflow ..........         0.000         0.000
  External Outflow .........         0.000         0.000
  Flooding Loss ............         0.000         0.000
  Evaporation Loss .........         0.000         0.000
  Exfiltration Loss ........         0.000         0.000
  Initial Stored Volume ....         0.000         0.000
  Final Stored Volume ......         0.193         1.932
  Continuity Error (%) .....         0.000

With system_routing.runoff_stats

{'drains': 0.0,
 'evaporation': 116.3831551772913,
 'final_snow_cover': 0.0,
 'final_storage': 0.19794609301561145,
 'infiltration': 665.0743417845243,
 'init_snow_cover': 0.0,
 'init_storage': 0.0,
 'routing_error': -0.24969199845736867,
 'rainfall': 266.0000000000004,
 'runoff': 2142.7650244959523,
 'runon': 0.0,
 'snow_removed': 0.0}

With system_routing.routing_stats:

{'dry_weather_inflow': 0.0,
 'evaporation_loss': 0.0,
 'external_inflow': 0.0,
 'final_storage': 53313.46802368025,
 'flooding': 0.0,
 'groundwater_inflow': -210.15797750380523,
 'II_inflow': 0.0,
 'initial_storage': 0.0,
 'outflow': 0.0,
 'routing_error': 9.999999999999999e-05,
 'reacted': 0.0,
 'seepage_loss': 0.0,
 'wet_weather_inflow': 2142.7650244958913

**Comment by bemcdonnell** [comment]
@tscheuch, I believe the `system_routing.runoff_stats` is showing you the final volume on your subcatchments.  The `system_routing.routing_stats` is showing you the final volume within your hydraulic network.

**Comment by bemcdonnell** [comment]
@dickinsonbob, can you confirm?

**Comment by dickinsonre** [comment]
@bemcdonnell The final volume on the sub-catchments is from the area and final runoff depth of the sub-catchments.  The final routing volume is the volume in storage nodes, nodes, and links so they are not the same.

**Comment by tscheuch** [comment]
Quite so!
The problem is that studying in both cases the final routing volume, different values are obtained in the .rpt file (1.100 10^6 ltr) and using the pyswmm command system_routing.routing_stats (67601.63 (I am not sure of the measurement units, I supose that is m3 like the rest of the variables)).

**Comment by karosc** [comment]
This should be addressed by [OWA SWMM #354](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/issues/354). The numbers output by `routing_stats` and `runoff_stats` functions use internal SWMM units of feet. Volume is ft3, flow is ft3/s, and length is ft, you will need to manually convert them to get them to match up to the numbers in the rpt file.
