### ISSUE TITLE
Flow_routing_error & runoff_error

### ISSUE THREAD

**Issue by Nils-TalTech** [OpenWaterAnalytics/pyswmm#236]
**Describe the bug**
Functions flow_routing_error and runoff_error seem to yield no result (output = 0.0)

**To Reproduce**
this code is not returning relevant errors: 
sim = Simulation(file)
    sim.execute()
    print(sim.flow_routing_error)
    print(sim.runoff_error)

although error numbers can be obtained with lower level API:

mod = PySWMM(input_file)
    mod.swmm_open()
    mod.swmm_start()
    while True:
        time = mod.swmm_step()  # or swmm_stride()
        if time <= 0.0:
            break
    mod.swmm_end()
    print('\n', mod.swmm_getMassBalErr())
    mod.swmm_close()

has anyone encountered the same error?

**Desktop**
 - OS: [Windows]
 - Python Version [Python 3.7]
 - PySWMM Version [0.6.0]

**Comment by bemcdonnell** [comment]
@Nils-TalTech,

When you use:
```python
sim = Simulation(file)
sim.execute()
```
`sim.execute()` closes and clear the swmm data model

However, I believe if you use

```python
with Simulation('<inp>') as sim:
    for step in sim:
        pass
    
    # Simulation handle is still live within the "with" context manager
    print(sim.flow_routing_error)
    print(sim.runoff_error)
```

Try this and let me know if it works

**Comment by Nils-TalTech** [comment]
@bemcdonnell thank you for the hint. Sounds logical. Unfortunately this method returns 0.0 value for both routing and runoff. Checking from SWMM GUI these should be -1.15% and -12.73% respectively. 

Maybe there is an issue with new release of SWMM? I'm using the version 5.1.014. I don't know if also DLL have been updated with this release.

**Comment by Nils-TalTech** [comment]
@abhiramm7 thank you for the hint! This solution works!
