### ISSUE TITLE
Line endings is CRLF in pypi

### ISSUE THREAD

**Issue by lrntct** [OpenWaterAnalytics/pyswmm#240]
**Describe the bug**
The line endings in the pyswmm pacjage on PyPI are CRLF (the Windows format). This is a source of headaches when trying to patch a file installed from PyPI. (See for example https://github.com/conda/conda-build/issues/1973)

**To Reproduce**
1. Clone the repository
2. Modify a file
3. Create a patch
4. Try to patch the file from PyPI

**Expected behavior**
All source files should use LF line endings.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version 3.7.6
 - PySWMM Version 0.6.0

**Additional context**

**Comment by bemcdonnell** [comment]
@lrntct, after the next release I will update all project files to `LF`.  Can this wait until the next release?

**Comment by lrntct** [comment]
@bemcdonnell For now, this issue is blocking the pyswmm conda package. If it waits for another release, I can simply make a PR to integrate the changes upstream instead of patching from PyPI.
This is the patch I struggle to apply:
https://github.com/conda-forge/pyswmm-feedstock/blob/master/recipe/__init__.py.patch
Please let me know if you would consider a PR on the matter.

**Comment by bemcdonnell** [comment]
Ok Good to know! I'll do it right now ;-)

**Comment by michaeltryby** [comment]
There is a setting in git that automatically handles line endings for you. Here is a link to an article about it. https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by lrntct** [comment]
@michaeltryby Surprisingly, if I git clone the repository, the lines endings are LF. But the line endings in the PyPI package are CRLF. That is why a patch which work on my computer based on the git repository no longer works on the PyPI package.

**Comment by bemcdonnell** [comment]
This command "git config --global core.autocrlf input" i think fixed it.. i should have a PR in a second.

**Comment by bemcdonnell** [comment]
@lrntct, when i started the project I was doing dev on Windows and therefore committed the first batch of files as CRLF. I am trying to fix that now.. believe it or not, it's not straightforward!

**Comment by lrntct** [comment]
@bemcdonnell I reported the issue exactly because it is a pain in the neck ;)
Thank you for paying attention.

**Comment by lrntct** [comment]
@bemcdonnell Do you plan to update the 0.6.0 packages on PyPI?
If not, I think of hosting a patched package for the conda package to depend on, but it is not ideal.

**Comment by bemcdonnell** [comment]
I tried to fix this the other day.  It's not straightforward to do so.  I'm curious @goanpeca, have you dealt with this before?

**Comment by goanpeca** [comment]
I have, but proceed as you suggested, changing the git config but also changing all files "manually"

**Comment by bemcdonnell** [comment]
@goanpeca, it seems like when i try to do this, the files changes do not have any results with GitHub. I believe when this repo was setup originally i pushed Windows line endings (this is almost 8 years ago now).  So as I understand this, when we check in the files, the endings are always converted to `CRLF`.

**Comment by goanpeca** [comment]
See https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by michaeltryby** [comment]
@bemcdonnell and @lrntct I think the solution is to prepare two packages. With each having appropriate line endings for the intended platform. Github does this when you create a tag it creates .zip and a .tar.gz archives. Likewise, we should have a version of PySWMM for Windows and a version for Linux/Unix. 

Anyhow, this is one potential solution.

**Comment by lrntct** [comment]
@michaeltryby the Windows version does not need to have Windows line endings in the git repo.
