### ISSUE TITLE
(JOSS Paper) Missing Contributor Information

### ISSUE THREAD

**Issue by nickrsan** [OpenWaterAnalytics/pyswmm#242]
Hi all,

I'm one of the reviewers for the pyswmm paper with JOSS (https://github.com/openjournals/joss-reviews/issues/2292) - I've almost completed my review and everything seems great, but one thing that seems to be missing that's on the JOSS checklist is contributor guidelines in the documentation - I see the code of conduct in the repository, but JOSS requires the following:

```
There should be clear guidelines for third-parties wishing to:

    Contribute to the software
    Report issues or problems with the software
    Seek support
```

**Comment by bemcdonnell** [comment]
@nickrsan 

Thanks for taking time to review! We have put a lot of this info in our wiki - would it make more sense to canonicalize these in the repo itself?

- Contribute to the software

https://github.com/OpenWaterAnalytics/pyswmm/wiki/Author-Contribution-Checklist 
https://github.com/OpenWaterAnalytics/pyswmm/wiki/Dev-Github-Workflow

- Report issues or problems with the software / Seek support

Our main README has the following info

Bugs
Our issue tracker is at https://github.com/OpenWaterAnalytics/pyswmm/issues. Please report any bugs that you find. Or, even better, fork the repository on GitHub and create a pull request. All changes are welcome, big or small, and we will help you make the pull request if you are new to git (just ask on the issue).

Can you share an example repository we can model this after? Thanks!

**Comment by nickrsan** [comment]
Hi @bemcdonnell - thanks for the details! I'm sorry I missed it in the wiki - I should have thought to check there, but maybe a link from the README would help? 

The info in the wiki is sufficient for the paper, as far as I'm concerned. I had been looking for a link in the documentation (which I don't think it needs), in the README, or for a [CONTRIBUTING.md file](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) in the repository's root. I personally like the CONTRIBUTING.md files since GitHub prompts people to check it when making pull requests like it does with the code of conduct, but I think it's just one option. For the paper, I think we're set since you have guidelines in a place I think many people would often check, and which you can link people to - I'll go mark this part as complete on the review.

**Comment by katmratliff** [comment]
@nickrsan thank you for the suggestion! I opened up a PR #244 to add the link to the Wiki in the README.
