### ISSUE TITLE
PID control in PySWMM

### ISSUE THREAD

**Issue by zxyzmbc1030** [OpenWaterAnalytics/pyswmm#254]
Hi,

Does anyone have experience on how to use PID control in pyswmm? Or to say, is it possible to use PID rules in changing weir or orifice setting dynamically?

thx.

**Comment by jennwuu** [comment]
Hello @zxyzmbc1030,

Check out this section https://pyswmm.readthedocs.io/en/latest/tutorial/tutorial.html#pyswmm-controls for example of changing target setting of a link.

**Comment by bemcdonnell** [comment]
@zxyzmbc1030, is this question resolved?

**Comment by zxyzmbc1030** [comment]
> @zxyzmbc1030, is this question resolved?

Yes, thanks
