### ISSUE TITLE
Interacting with a storage unit

### ISSUE THREAD

**Issue by s154024** [OpenWaterAnalytics/pyswmm#257]
Hi, I'm trying to automate some simulations for different detention ponds using SWMM and pySWMM.

Therefore, the storage curve is crucial to my project. I've created a code which automatically creates
storage curves as .dat files, which is then imported into SWMM. The idea was that the generated storage curve should overwrite the previous (same file name) between simulations, however, this is not the case.
So-far I have to reload it manually everytime, which is not very time efficient.

Is it somehow possible to load or set the storage curve within the script?

I found some similiar issues regarding storage curves (167,  187, 189), however as far as I understand, it is fixed using EPANET and not pyswmm?

**Comment by bemcdonnell** [comment]
@s154024, could you provide more detail on the scripted process you are using? PySWMM doesn't "save" or edit an INP file.

**Comment by s154024** [comment]
I’m trying to run a loop where I change the volume of a storage unit in a simple system created in SWMM (containing a subcatchment and a storage unit with an outlet link and weir).

The storage unit is created in SWMM and the volume is depended on a tabular curve. This curve is defined under the storage curve tab and is then loaded from a data file. For this purpose, I’ve created the beforementioned script, which generates .dat files (depths and areas). 

From here, I wanted to shut down SWMM, and manipulate the model only using python. 
However, when I create a new .dat file which overwrites the previous and run a new simulation using pySWMM, the volume of the storage unit does unfortunately not change (I’m tracking the volume using pySWMM by simulating a great rain event, which I know will fill storage unit). 

As this approach doesn’t work, I would instead like to define the storage curve / the storage unit properties in pySWMM.

I hope it makes sense :)

**Comment by dickinsonre** [comment]
in native SWMM5 you can graph or make a table of the volume in a storage unit - do the graphs make sense.

**Comment by s154024** [comment]
I've copied some of my code (no loop here):

#Initiates simulation
sim = Simulation(r"./SWMM_System.inp")

#Defines start and end time of simulation and reporting
sim.start_time = data['Date_Time'].iloc[1710000-1600] #start of the event of interest
sim.report_start = data['Date_Time'].iloc[1710000-1600] #start of the event of interest
sim.end_time = data['Date_Time'].iloc[1710000-1400]+timedelta(minutes=20) #end of the event

# Manipulate subcatchment
S1 = Subcatchments(sim)["S1"]
S1.area = 1 #ha

 #Defines the storage unit properties
SU1=Nodes(sim)["SU1"]
SU1.invert_elevation= 17 #meters
SU1.initial_depth=1.5 meters

### Here I would also like to control the storage curve ###
SU1.StorageCurve = tabular

#Create a list which can contain simulation results
SU1Vol=[]
SU1Depth=[]

#Run the simulation
for step in sim:    
    SU1Vol.append(SU1.volume)
    SU1Depth.append(SU1.depth)

**Comment by bemcdonnell** [comment]
@s154024 how are you ending/closing your simulation?  I normally suggest people use the context manager:

```python
with Simulation('inp') as sim:
    for step in sim:
        pass
```

**Comment by s154024** [comment]
Thanks @dickinsonre - Though, I do know that I can load the curve directly in SWMM, but I'm trying to do it through pySWMM as I want do run a simulation of lots (!) of different storage curves (I'm trying to assess how the shape and size of detention ponds affects the overflow frequency). The above script will be put inside a few for loops, which modifies the shape of the pond depended on e.g. the different slopes and depths of the pond :)

**Comment by s154024** [comment]
And @bemcdonnell thanks, I just forgot the "pass" statement.

**Comment by bemcdonnell** [comment]
@s154024 i just want to be totally clear - so you are are manually calling `sim.close()`?  The `with` context manager does this for you.  I'm curious about how you have embedded pyswmm in your loop.

**Comment by s154024** [comment]
@bemcdonnell I  just double checked the code - and I don't have a pass or close statement. The relevant pySWMM results  from one simulation are stored in a sql database, which is updated after each iteration (sorry, I just assumed I forgot to copy some code when you asked).

**Comment by s154024** [comment]
But back to the topic: Does anybody know if it is somehow possible to manipulate the volume of a storage unit through pySWMM (... by defining the wanted storage curve?)

**Comment by Leslay-wang** [comment]
Hello,is it convenient to consult some questions? I am a student in university and recently,I am conducting a research on detention ponds with SWMM and pyswmm.

**Comment by Husnain2244** [comment]
@bemcdonnell @s154024
Hi, Thanks for your above discussion. I also read previous posts related to getting/setting storage node parameters. Please let me know if the current version of pyswmm can access/modify the storage unit's parameters (especially its storage volume) by pyswmm. Or If there is any other tool that can be used for this purpose. Thank you!
