### ISSUE TITLE
How can I edit the time series of rainfall?

### ISSUE THREAD

**Issue by nantekoto** [OpenWaterAnalytics/pyswmm#259]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.  Good to place code here with support files.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - Python Version [e.g. Python 3.6-x86]
 - PySWMM Version [e.g. v0.4.8]

**Additional context**

**Comment by bemcdonnell** [comment]
@nantekoto, you’re reporting a bug?

**Comment by nantekoto** [comment]
the system module offer the stats of rainfall time series, however how should I edit the data and rerun the model

**Comment by michaeltryby** [comment]
Seem to be some confusion. Issues are being used for support requests. Upside is that we have users! So perhaps we need to setup a better support channel and "communicate" it to them.

**Comment by bemcdonnell** [comment]
@nantekoto, you should just write a process to edit your INP file if you want to adjust a timeseries there.
