### ISSUE TITLE
ERROR 307: cannot open binary results file.

### ISSUE THREAD

**Issue by BrianN92** [OpenWaterAnalytics/pyswmm#261]
**Describe the bug**
The inp file was able to be run without issue for several times until it suddenly broke. I did not modify the inp file. Does anyone ever run into this error?

**Screenshots**
![image](https://user-images.githubusercontent.com/21299740/102274196-78396580-3ef1-11eb-91b9-cd331753ce01.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Python Version [Python 3.6-x86]
 - PySWMM Version [v0.6.2]

**Comment by bemcdonnell** [comment]
@BrianN92 did you by chance have the OUT file open in something else at the same time?

**Comment by BrianN92** [comment]
@bemcdonnell Thanks for replying! Unfortunately, I am not sure. I have a script which automatically and randomly runs swmm inp files one by one in a folder. Before the error occurred, that inp file had been ran by the script twice or more successfully.

**Comment by bemcdonnell** [comment]
@BrianN92 so this problem isn't consistent?

**Comment by BrianN92** [comment]
@bemcdonnell So far what seems to me is the same file is able to be opened twice but will report error at the third time. It could be the reason I did not close it properly.

**Comment by BrianN92** [comment]
@bemcdonnell Sorry I just found this error is not caused by opening a file multiple times. The script will crash after running about 4 mins every time.

**Comment by michaeltryby** [comment]
Hey @BrianN92 is the path to the binary file the same or different for each call?

**Comment by BrianN92** [comment]
Hi @michaeltryby the path is same for each call. One thing you do remind me is after each time I run the script, I always got many warnings. See the screenshot below. Could this be a reason of the error?
I have never seen this before in the Windows OS. However, I have to run pyswmm in Linux now due to my project requirements.

![image](https://user-images.githubusercontent.com/21299740/102660234-b2e90b00-4148-11eb-9238-0958d9fda41c.png)

**Comment by michaeltryby** [comment]
@BrianN92 I think what is happening is that the OS is lagging when it releases the binary file. Then when you try to make your next run it can't open the file because it hasn't been released yet. So what you need to do is make the path to the binary file unique for each subprocess call you make. This is usually done by creating a folder with a unique name in the temp files directory, copying the input file there, and then running the model. 

I have no idea why you are getting that other error.  Looks like something related to a cmake build which you aren't doing. Or are you? Why would it be looking for /home/kratliff on your machine? No idea what is going on there ... sorry.

**Comment by michaeltryby** [comment]
@BrianN92 Another quick question for you . Are you building SWMM yourself or are you using pyswmm from pypi?

**Comment by BrianN92** [comment]
@michaeltryby Thank you, I think I get your points. 

Btw, I install the pyswmm on Linux from pypi. Could be some default settings come alone with the installation, but I have no idea where to modify them. One thing to note is I got those warnings when executing scripts in command line. However, when I run scripts in Spyder, those warnings were just disappeared...

**Comment by Jiadalee** [comment]
@BrianN92 Which linux environment do you use? would you mind posting some sample codes so that I can help you test in my side? I used to run pyswmm simulations in my university Linux high-performance node. Hope I can be helpful.

**Comment by BrianN92** [comment]
@Jiadalee Thanks for your kindness but I am afraid I cannot share my code.

**Comment by BrianN92** [comment]
@michaeltryby I tried your way, but still got the same error. It cannot open the binary result file after 4 mins each time... Very strange thing.

**Comment by michaeltryby** [comment]
@BrianN92 how many simulations do you figure you are running in 4 minutes?

**Comment by michaeltryby** [comment]
@BrianN92 Thinking about this more ... It's likely that ERROR 307 is a side effect of the bug rather than the bug itself. Since the file fails to open after 4 minutes, perhaps there is a time out associated with the subprocess that is expiring?

**Comment by BrianN92** [comment]
@michaeltryby There are around 210 simulations has been run in 4 minutes. Sorry, but I am not quite getting the "time out" you mentioned.

**Comment by michaeltryby** [comment]
@BrianN92 The OS may have a limit on the maximum number of open files allowed at one time. Are you sure that the binary files are getting closed properly? 

A time out is a maximum time allowed for an operation before it is considered failed. Many system functions have them. So perhaps Python subprocesses have them too. Just trying to think out of the box.

**Comment by BrianN92** [comment]
Thanks @michaeltryby ! I get your point. So I guess my question is: Is there a way to manually close the binary files using pyswmm?

**Comment by BrianN92** [comment]
So I finally fixed this issue. Turns out the Linux OS have a default limit on the maximum number of open files as 1024. I set the number inside the "limit.config" to a large enough threshold as well as added the` sim.close()`. Now the code is able to run without errors. Huge thanks to @michaeltryby and @bemcdonnell !
