### ISSUE TITLE
The <conduit_statistics> and <Pump_statistics >can't use: 'Conduit' object has no attribute 'statistics'

### ISSUE THREAD

**Issue by xie-kun** [OpenWaterAnalytics/pyswmm#266]
Could you tell me how to use <conduit_statistics>and <Pump_statistics > ? I want to get the <total_volume>, but I can't get the result by the function<link.Pump_statistics>,my code as follow:

    with Simulation('new.inp') as sim:
        link_oj = Links(sim)
        node_oj = Nodes(sim)
        J56 = node_oj['J56']
        pump18 = link_oj['18']
        orif15 = link_oj['15']
        orif17 = link_oj['17']
        for link in link_oj:
            i=i+1
            link.statistics

error:AttributeError: 'Conduit' object has no attribute 'statistics'

**Comment by jennwuu** [comment]
are you looking for (conduit statistics)[https://pyswmm.readthedocs.io/en/latest/reference/links.html#pyswmm.links.Conduit]?

**Comment by jennwuu** [comment]
maybe you can try something like this?

```python
with Simulation('new.inp') as sim:
    link_oj = Links(sim)
    node_oj = Nodes(sim)
    J56 = node_oj['J56']
    pump18 = link_oj['18']
    orif15 = link_oj['15']
    orif17 = link_oj['17']
    for link in link_oj:
        i=i+1
        if link.is_conduit():
            link.conduit_statistics
        elif link.is_pump():
            link.pump_statistics
        
```

**Comment by xie-kun** [comment]
> are you looking for [conduit statistics](https://pyswmm.readthedocs.io/en/latest/reference/links.html#pyswmm.links.Conduit) ?

Yes!

**Comment by xie-kun** [comment]
> maybe you can try something like this?
> 
> ```python
> with Simulation('new.inp') as sim:
>     link_oj = Links(sim)
>     node_oj = Nodes(sim)
>     J56 = node_oj['J56']
>     pump18 = link_oj['18']
>     orif15 = link_oj['15']
>     orif17 = link_oj['17']
>     for link in link_oj:
>         i=i+1
>         if link.is_conduit():
>             link.conduit_statistics
>         elif link.is_pump():
>             link.pump_statistics
>         
> ```

I try it, but the compiler still report errors. My Python version is 3.7 on Windows 10 ，and the Integrated development tooling is Pycharm.

from pyswmm import Simulation, Links, Nodes

    with Simulation('new.inp') as sim:
        link_oj = Links(sim)
        node_oj = Nodes(sim)
        J56 = node_oj['J56']
        pump18 = link_oj['18']
        orif15 = link_oj['15']
        orif17 = link_oj['17']
        for link in link_oj:
            i = i + 1
            if link.is_conduit():
                link.conduit_statistics
            elif link.is_pump():
                link.pump_statistics

**Comment by jennwuu** [comment]
What kind of errors are you getting? Do you mind sharing the model .inp file?

**Comment by xie-kun** [comment]
> What kind of errors are you getting? Do you mind sharing the model .inp file?

The errors as following:

  File "E:\Python3\install\lib\site-packages\pyswmm\links.py", line 984, in conduit_statistics
    return self._model.conduit_statistics(self.linkid)
  File "E:\Python3\install\lib\site-packages\pyswmm\swmm5.py", line 1785, in conduit_statistics
    self._error_check(errcode)
  File "E:\Python3\install\lib\site-packages\pyswmm\swmm5.py", line 165, in _error_check
    raise SWMMException(errcode, self._error_message(errcode))
pyswmm.swmm5.SWMMException: 
 API Key Error: Simulation Not Running

**Comment by jennwuu** [comment]
ahh, I think statistics is only available at the end of the simulation. Are you trying to calculate the total volume at each simulation time step?

**Comment by xie-kun** [comment]
> What kind of errors are you getting? Do you mind sharing the model .inp
How can I sharing the inp file to you ?

> ahh, I think statistics is only available at the end of the simulation. Are you trying to calculate the total volume at each simulation time step?

**Comment by jennwuu** [comment]
@xie-kun 

Maybe you can try something like this?

```python
total_volume  = {
    '18': 0, 
    '15': 0,
    '17': 0,
}

with Simulation('new.inp') as sim:
    previous_time = sim.start_time
    link_oj = Links(sim)
    node_oj = Nodes(sim)
    J56 = node_oj['J56']
    pump18 = link_oj['18']
    orif15 = link_oj['15']
    orif17 = link_oj['17']
    for step in sim:
        delta_time = (sim.current_time - previous_time).total_seconds()
        previous_time = sim.current_time 
        
        for link in total_volume:
            total_volume[link] = links[link].flow * delta_time
```

**Comment by xie-kun** [comment]
> ahh, I think statistics is only available at the end of the simulation. Are you trying to calculate the total volume at each simulation time step?

I really want to get the volume at each time step ，and I have some confuse the total volume just represent the volume at each time step？or the volume  of the entire simulation？

**Comment by xie-kun** [comment]
> ahh, I think statistics is only available at the end of the simulation. Are you trying to calculate the total volume at each simulation time step?

And I can't use the conduit_statistics in any way ，include the volume at the end of simulation. When I write the code about conduit_statistics , the code  will display errors. I'm really  confused .

**Comment by jennwuu** [comment]
Did you try the code snippet I provided in the post above? The one with dictionary?

**Comment by xie-kun** [comment]
> @xie-kun
> 
> Maybe you can try something like this?
> 
> ```python
> total_volume  = {
>     '18': 0, 
>     '15': 0,
>     '17': 0,
> }
> 
> with Simulation('new.inp') as sim:
>     previous_time = sim.start_time
>     link_oj = Links(sim)
>     node_oj = Nodes(sim)
>     J56 = node_oj['J56']
>     pump18 = link_oj['18']
>     orif15 = link_oj['15']
>     orif17 = link_oj['17']
>     for step in sim:
>         delta_time = (sim.current_time - previous_time).total_seconds()
>         previous_time = sim.current_time 
>         
>         for link in total_volume:
>             total_volume[link] = links[link].flow * delta_time
> ```

Thank you very much！when I try it in this way I can get the result , but I still can't understand why I can't use the conduit_statistics directly?

**Comment by jennwuu** [comment]
conduits function is only available at the end of a simulation

**Comment by xie-kun** [comment]
> Did you try the code snippet I provided in the post above? The one with dictionary?



> conduits function is only available at the end of a simulation
Like the code you provided above ? But I still can't execute it.

with Simulation('new.inp') as sim:
    link_oj = Links(sim)
    node_oj = Nodes(sim)
    J56 = node_oj['J56']
    pump18 = link_oj['18']
    orif15 = link_oj['15']
    orif17 = link_oj['17']
    for link in link_oj:
        i=i+1
        if link.is_conduit():
            link.conduit_statistics
        elif link.is_pump():
            link.pump_statistics

**Comment by jennwuu** [comment]
> > Did you try the code snippet I provided in the post above? The one with dictionary?
> 
> > conduits function is only available at the end of a simulation
> > Like the code you provided above ? But I still can't execute it.
> 
> with Simulation('new.inp') as sim:
> link_oj = Links(sim)
> node_oj = Nodes(sim)
> J56 = node_oj['J56']
> pump18 = link_oj['18']
> orif15 = link_oj['15']
> orif17 = link_oj['17']
> for link in link_oj:
> i=i+1
> if link.is_conduit():
> link.conduit_statistics
> elif link.is_pump():
> link.pump_statistics

Yeah, ignore this example. I made a mistake. If the other example is usable, then I think we can close this issue. :D
