### ISSUE TITLE
Report fails to write with time series

### ISSUE THREAD

**Issue by bdb3m** [OpenWaterAnalytics/pyswmm#269]
I'm getting SWMM error 309: error writing to binary results file, when writing long time series and am not sure if it's an OS error or a pyswmm error. The report writes correctly if I don't specify any node or link time series, but hangs on an incomplete line and doesn't write the summaries if time series are included:
![image](https://user-images.githubusercontent.com/22157448/106213395-9524b200-619a-11eb-96ab-629f3f919b52.png)

I would like to save specific node/link timeseries in the report because I'm using pyswmm as an environment for reinforcement learning of real-time control policies and cannot access them unless they are directly used in the state of the RL agent. Normally I would save the results I need while stepping through a simulation, but that doesn't work with my RL setup. I'm not sure if the error is caused by the OS just timing out; I'm on Windows 10 and tried to increase the max number of files but no luck. I also tried reading the output file with SWMMOutputAPI but ran into issues with that as well.

Any thoughts or help is appreciated!
-Ben

**Comment by jennwuu** [comment]
@bdb3m Can you share code where you used pyswmm?

**Comment by jennwuu** [comment]
@bdb3m 

I ran your code with my own model .inp file successfully. I used pyswmm==1.0.1.

Reviewing the code you shared, I noticed one minor thing:

```
with Simulation(swmm_inp) as sim:  # rpt without time series
    for step in sim:
        # print(step_count)
        if sim.percent_complete * 100 % 5 == 0:
            print(sim.percent_complete)

        if sim.current_time == sim.start_time:
            R1.target_setting = 1
            R2.target_setting = 1
            R3.target_setting = 1

        # calculate GW exchange
        # current_gwl = gwl_df.iloc[gwl_df.index.get_loc(sim.current_time, method='nearest')]["IDW"]
        # # print(sim.current_time, current_gwl)
        # St1_gwq = calc_gwl(St1.depth - abs(St1.invert_elevation), current_gwl, St1_rad)
        # St2_gwq = calc_gwl(St2.depth - abs(St2.invert_elevation), current_gwl, St2_rad)
        # St3_gwq = calc_gwl(St3.depth - abs(St3.invert_elevation), current_gwl, St3_rad)
        # print(St1_gwq)

        # print("pregwl", St1.total_inflow)
        # add (or subtract) gw volume to storage unit
        # St1.generated_inflow(St1_gwq)
        # St2.generated_inflow(St2_gwq)
        # St3.generated_inflow(St3_gwq)
        # print("post gwl", St1.total_inflow)

    sim.report()
sim.close()
```

Note that you do not need to close Simulation object when you use context manager. `with` will close your simulation object once you're done with it.

----

I tested again with pyswmm v0.6.0, and I saw the error as described. Can you try your code with pyswmm==1.0.1 instead? 

Note before you upgrade to pyswmm=v1.0.1:
- make sure your Python is 64 bit for v1.0.1
- make sure your aenum package is v2.2.6 during your pyswmm upgrade

**Comment by bdb3m** [comment]
I am using pyswmm v0.6.0; I'll try with v1.0.1. Seems like that will fix my issue, but I will let you know if not.

Thanks for your help and sharing the Output module PR! Looks like a great addition!

**Comment by bdb3m** [comment]
@jennwuu I had a chance to upgrade to pyswmm 1.0.1 and the report wrote correctly and we can close this issue. Thanks again for your help!!

Out of curiousity, do you have any ideas why 0.6.0 had that issue?

**Comment by jennwuu** [comment]
> @jennwuu I had a chance to upgrade to pyswmm 1.0.1 and the report wrote correctly and we can close this issue. Thanks again for your help!!
> 
> Out of curiousity, do you have any ideas why 0.6.0 had that issue?

I think in v0.6.0, swmm_end() cannot be called after swmm_report(). This does not seem to be an issue with pyswmm v1.0.1.
