### ISSUE TITLE
Opening project using external timeseries files

### ISSUE THREAD

**Issue by attilabibok** [OpenWaterAnalytics/pyswmm#273]
Hi,

I was running some project of mine using the toolkit and the toolkit gives me the following error when I try to open a project with external time-series files:

>   File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python37\lib\site-packages\pyswmm\simulation.py", line 69, in __init__
>     self._model.swmm_open()
>   File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python37\lib\site-packages\pyswmm\swmm5.py", line 267, in swmm_open
>     self._error_check(errcode)
>   File "C:\Users\Bibok Attila\AppData\Local\Programs\Python\Python37\lib\site-packages\pyswmm\swmm5.py", line 165, in _error_check
> The thread 'MainThread' (0x1) has exited with code 0 (0x0).
>     raise SWMMException(errcode, self._error_message(errcode))
> pyswmm.swmm5.SWMMException: 
>   ERROR 361: could not open external file used for Time Series %s.

The problem can be reproduced easily. Just add an external time-series to the model with a relative path. Put them in the same folder with the project, giving just the filename of the text file containing the series as the path.

If you open the project file from a subfolder of the folder from which you run the python code, eg. data subfolder:
`with Simulation('data/example_swmm.inp') as sim:`
The source of the problem is that the toolkit looks for the time-series files relative to the path from which the python script is running instead of relative to the project path.

The workaround is easy, I just moved the time series to the folder in which the python script is or run the python script from the project's folder. It is not a major issue, although a bit inconvenient.

**Comment by jennwuu** [comment]
@attilabibok Can you share the error you are seeing in the .rpt file? Also, can you share the relative path within the inp file?
