### ISSUE TITLE
DELETING MY SWMM RESULTS. This library is a virus

### ISSUE THREAD

**Issue by openSourcerer9000** [OpenWaterAnalytics/pyswmm#278]
I installed pyswmm to see if it was a better alternative for grabbing time series data than PCSWMM's pcpy package. Big mistake. I tried out the recipe for getting depth timeseries of a single node. 

```
with Simulation(scenpath) as sim:
    j1 = Nodes(sim)['J1']
    ts = [j1.depth for step in sim]
```

And it hangs. Oh boy does it hang. In fact it still is, 30 min later. "Retrieving project data" it says. Well let's see how all that project data is doing...

![image](https://user-images.githubusercontent.com/61931826/114212152-1d57ce00-9927-11eb-848c-413be0b2b668.png)

WTF???? 18 hrs worth of simulation results- deleted. All I wanted was a little timeseries graph to show for Monday's client meeting. 

Will be uninstalling this virus before it deletes any more files.

**To Reproduce**
Step 1:
Spend a lot of your valuable time building a large model (.out file ~2.5GB), run the above hello world recipe and watch as pyswmm tries to load the whole thing into memory, fail, then delete all your data. 

Step 2:
Spend your weekend at the office redoing the work.

**Expected behavior**
NOT DELETE MY PROJECT FILES!

**Desktop (please complete the following information):**
Windows
Python 3.8
pyswmm 0.6.2

**Comment by bemcdonnell** [comment]
@openSourcerer9000, have you ever considered the possibility that you just don't know how to use this package?

**Comment by bemcdonnell** [comment]
@openSourcerer9000, why don't you try this:

```python
with Simulation(<INP>) as sim:
    j1 = Nodes(sim)["J1"]
    ts = []
    jun_vals = []
    for step in sim:
        ts.append(sim.current_time)
        jun_vals.append(ji.depth)
```

Next time you want to write rude comments on a community open source project, maybe read the documentation first.  Lots of people have come together to make this project happen.

**Comment by jennwuu** [comment]
If you're trying to read .out file from an existing model result, do not iterate your simulation object:

```
for step in sim:
     pass
```

This will re-run your model because the code will iterate your simulation object per routing time step.  If you're trying to access your model output result for an existing model run, you need to check out (swmm-python)[https://github.com/OpenWaterAnalytics/swmm-python] or wait for the new PR which expands pyswmm to read existing model output.

**Comment by michaeltryby** [comment]
@openSourcerer9000 I'm sorry that you are experiencing problems with pyswmm and are frustrated. It is not acceptable to post belligerent  comments on the issue boards. I know all too well; I've made the same mistake many times myself. 

Take the time to cool down and then we will try to help you and make pyswmm better.

**Comment by bemcdonnell** [comment]
@openSourcerer9000, here is a link to our Code of Conduct:

https://github.com/OpenWaterAnalytics/pyswmm/wiki/Contributor-Covenant-Code-of-Conduct

**Comment by michaeltryby** [comment]
If I understand this issue. I think the user wants to pull time series out of an existing binary output file. So the most straight forward approach would be to use the output API.

**Comment by jennwuu** [comment]
This feature should be helpful with this request: https://github.com/OpenWaterAnalytics/pyswmm/pull/275

**Comment by bemcdonnell** [comment]
@michaeltryby Yes, that was my observation too.  What I suppose we should do is clearly spell that out in the ReadTheDocs when we get the auto-build working again.
