### ISSUE TITLE
How to get the statistics information for pump?

### ISSUE THREAD

**Issue by xie-kun** [OpenWaterAnalytics/pyswmm#282]
Is there any way to get the switching times of the pump station by statistical function in PYSWMM ?
 This function（'number_startup'） is available on the official website, as follows,  but I don't know how to use this function to get the number of pump switch.

Statistical function in PYSWMM:
classpyswmm.links.Pump[source]
Bases: pyswmm.links.Link
--
min_flowrate
average_flowrate
max_flowrate
total_volume
energy_consumed
off_curve_low
off_curve_high
number_startups
total_periods

**Comment by abhiramm7** [comment]
Closed due to inactivity. @xie-kun let us know if you still want this answered.
