### ISSUE TITLE
Lidunits

### ISSUE THREAD

**Issue by KrushilM** [OpenWaterAnalytics/pyswmm#283]
I was trying to access lid units. the tutorial example posted has shown lidgroups example. can anyone help me with these?

**Comment by jennwuu** [comment]
Hey @KrushilM, check out this example for accessing lid units.

https://github.com/OpenWaterAnalytics/pyswmm/blob/f6edd28f97a52b67018981f64f311d7a005e23e7/pyswmm/tests/test_lid.py#L39-L51

**Comment by KrushilM** [comment]
Thank you @jennwuu
