### ISSUE TITLE
Abnormal termination during the loop simulation with PYSWMM

### ISSUE THREAD

**Issue by xie-kun** [OpenWaterAnalytics/pyswmm#284]
**Describe the bug**
In the process of invoking the model simulation for several times, an error will be reported suddenly. However, what is strange is that the error will not be reported when the number of cycles is small, and the first runs can be normal. But once the number of cycles increases, the error will be happen and interrupted around the 10th cycle. (the errors as following)

**To Reproduce**

for ii in range(2000):
    newfile = open("new.inp", "w")
    for newline in lines:
        newfile.write(newline)
    newfile.close()
    sim = Simulation('F:\\DORIM\\sensitive\\inp\\new.inp')
    sim.execute()

**Expected behavior**
ERROR following :
Traceback (most recent call last):
  File "F:/DORIM/sensitive/sobol.py", line 112, in <module>
    sim = Simulation('F:\\DORIM\\sensitive\\inp\\new.inp')
  File "E:\Python3\install\lib\site-packages\pyswmm\simulation.py", line 69, in __init__
    self._model.swmm_open()
  File "E:\Python3\install\lib\site-packages\pyswmm\swmm5.py", line 267, in swmm_open
    self._error_check(errcode)
  File "E:\Python3\install\lib\site-packages\pyswmm\swmm5.py", line 165, in _error_check
    raise SWMMException(errcode, self._error_message(errcode))
pyswmm.swmm5.SWMMException: 
  ERROR 305: cannot open report file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Python Version [e.g. Python 3.7]

**Additional context**

**Comment by xie-kun** [comment]
I found the problem was that the report file was not generated, but I don't know the reason, why the first few simulations can generate a report but the later ones can't.

**Comment by jennwuu** [comment]
@xie-kun, interesting bug. It looks like there is a lock on the input file after several iterations. Is it possible that you are running the models in parallel with the same input file?

sim.execute should open, run, and close simulation. 

One thing you could try is to run simulation using a context manager which will close your Simulation for you.

```
with Simulation(r'path.inp') as sim:
    for step in sim:
        pass
```

**Comment by xie-kun** [comment]
Thank you very much.
I'm not doing parallel computation.
I will try it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
@xie-kun, interesting bug. It looks like there is a lock on the input file after several iterations. Is it possible that you are running the models in parallel with the same input file?
 
sim.execute should open, run, and close simulation.
 
One thing you could try is to run simulation using a context manager which will close your Simulation for you.
 with Simulation(r'path.inp') as sim:     for step in sim:         pass

**Comment by bemcdonnell** [comment]
@xie-kun, can you look at the *RPT file that SWMM outputs to see a list of reasons the simulation failed?

**Comment by michaeltryby** [comment]
@bemcdonnell The simulation failed with Error: 305 Unable to open report file. Is `Simulation.execute()` a good citizen that cleans up after itself by closing all open files?

**Comment by bemcdonnell** [comment]
@michaeltryby it's entirely possible that it isn't closing things properly.  Not many people have used the `execute` feature.  I think it calls a low-level swmm entry point.  Needs to be investigated for sure.  

@xie-kun, did the workaround that @jennwuu proposed work okay for you?

**Comment by xie-kun** [comment]
I didn't try that, because that approach was too slow, need too much running time, and wasn't very friendly for 1000 iterations




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 凌晨0:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
@michaeltryby it's entirely possible that it isn't closing things properly.  Not many people have used the execute feature.  I think it calls a low-level swmm entry point.  Needs to be investigated for sure.
 
@xie-kun, did the workaround that @jennwuu proposed work okay for you?

**Comment by xie-kun** [comment]
Yes, there are short of&nbsp; statistics information in the report file.
&nbsp;&nbsp;
&nbsp; *********************************************************
&nbsp; NOTE: The summary statistics displayed in this report are
&nbsp; based on results found at every computational time step,&nbsp;&nbsp;
&nbsp; not just on results from each reporting time step.
&nbsp; *********************************************************

All of the following information is missing from here.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 凌晨0:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
@xie-kun, can you look at the *RPT file that SWMM outputs to see a list of reasons the simulation failed?

**Comment by xie-kun** [comment]
I found that the main reason is the output file is not generated resulting in a lack of information in the RPT. When I've looped 126 times, it has jumped to 127 times to generate the required 127.inp.&nbsp;
(Please check the attachment）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
@xie-kun, interesting bug. It looks like there is a lock on the input file after several iterations. Is it possible that you are running the models in parallel with the same input file?
 
sim.execute should open, run, and close simulation.
 
One thing you could try is to run simulation using a context manager which will close your Simulation for you.
 with Simulation(r'path.inp') as sim:     for step in sim:         pass

**Comment by michaeltryby** [comment]
@xie-kun It’s just a hunch, but I think this is a OS latency issue as opposed to a bug in pyswmm. There is a delay releasing the files from the previous run that is why they aren’t being written. I would try changing up how you are staging the files for each run to make it more robust. The simplest way to do this would be to generate a unique filename for each task.

**Comment by xie-kun** [comment]
But my inp filename is different in each loop, and the error pattern is that it must occur after the loop has reached 126 times




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月24日(星期六) 晚上8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
@xie-kun It’s just a hunch, but I think this is a OS latency issue as opposed to a bug in pyswmm. There is a delay releasing the files from the previous run that is why they aren’t being written. I would try changing up how you are staging the files for each run to make it more robust. The simplest way to do this would be to generate a unique filename for each task.

**Comment by michaeltryby** [comment]
Every time SWMM gets executed in the example the file name is ‘new.inp’. Generate a unique filename each time SWMM gets called.

**Comment by michaeltryby** [comment]
Is it possible that the SWMM simulation fails because it is getting invalid arguments? In which case you can make your execution code more robust by handling failed jobs more gracefully

**Comment by xie-kun** [comment]
I think there should be no invalid arguments, because I changed the loop to run from the start of the interrupt this time with the same inp ('new126.inp'), it will be normal.&nbsp; If I exit the loop and run the error inp separately, it will work normally.
&nbsp;The problem is that I cannot loop more than 126 times in a row.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenWaterAnalytics/pyswmm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月25日(星期天) 凌晨2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenWaterAnalytics/pyswmm] Abnormal termination during the loop simulation with PYSWMM (#284)





 
Is it possible that the SWMM simulation fails because it is getting invalid arguments? In which case you can make your execution code more robust by handling failed jobs more gracefully

**Comment by jennwuu** [comment]
@xie-kun can you share the python script and model input file? I would like to try and recreate this issue on my machine. Thanks!

**Comment by FeiZiGe** [comment]
I'm wondering if the bug is fixed. Because this time it terminates at the 254th iteration.

**Comment by bemcdonnell** [comment]
@FeiZiGe can you please post your code so we can try to see what is going on?

**Comment by FeiZiGe** [comment]
@bemcdonnell Thank you!  I have figured it out. If I use the expression sim.execute(), it will actually terminate in the 254th iteration, but if I change the expression, such as
```
with Simulation(r'path.inp') as sim:
    for step in sim:
        pass
```
and then there are no more abnormal termination and the calculation speed will also increase.
