### ISSUE TITLE
pyswmm——FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by Leslay-wang** [OpenWaterAnalytics/pyswmm#285]
**Describe the bug**
When running the "print_runoff" example case，FileNotFoundError: [WinError 2] 系统找不到指定的文件。
: 'E:\\AppData\\Anaconda3\\lib\\site-packages\\swmm_toolkit-0.8.1-py3.8-win-amd64.egg\\swmm\\toolkit\\../../../../bin'

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm-1.0.1-py3.8.egg\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm-1.0.1-py3.8.egg\pyswmm\links.py", line 9, in <module>
    from swmm.toolkit import shared_enum

  File "E:\AppData\Anaconda3\lib\site-packages\swmm_toolkit-0.8.1-py3.8-win-amd64.egg\swmm\toolkit\__init__.py", line 39, in <module>
    os.add_dll_directory(libdir)

  File "E:\AppData\Anaconda3\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)

FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'E:\\AppData\\Anaconda3\\lib\\site-packages\\swmm_toolkit-0.8.1-py3.8-win-amd64.egg\\swmm\\toolkit\\../../../../bin'

**Desktop (please complete the following information):**
 - OS: Windows
 - Python Version ：Python 3.8
 - PySWMM Version ：v1.0.1

**Comment by michaeltryby** [comment]
@Leslay-wang did you build SWMM-toolkit package yourself from the source distribution?  It looks like it’s installed as an egg but it needs to be installed as a wheel. Eggs aren’t supported. Wheels for Windows are available on pypi.

**Comment by Leslay-wang** [comment]
> @Leslay-wang did you build SWMM-toolkit package yourself from the source distribution? It looks like it’s installed as an egg but it needs to be installed as a wheel. Eggs aren’t supported. Wheels for Windows are available on pypi.
I installed pyswmm through setup.py first . Then I uninstalled it and later installed it as a wheel on pypi——pyswmm-1.0.1-py3-none-any.whl. But in these two cases, I met the same problem as mentioned above.

**Comment by jennwuu** [comment]
@Leslay-wang Are you using python 32-bit or 64-bit?

**Comment by michaeltryby** [comment]
pyswmm / swmm-toolkit are 64 bit only. We no longer support 32 bit.

**Comment by Leslay-wang** [comment]
@jennwuu python 64-bit. Any problem?

**Comment by Leslay-wang** [comment]
@michaeltryby I use python 64 bit.

**Comment by jennwuu** [comment]
@Leslay-wang It is very odd that it is asking you to build pyswmm when you're using python 64 bit. Can you try `pip install pyswmm` as suggested by Michael?

**Comment by jennwuu** [comment]
@Leslay-wang If you use pip to download from python pypi, I would expect to see the following message:

`pip install pyswmm`

```
Collecting pyswmm
  Using cached pyswmm-1.0.1-py3-none-any.whl (88 kB)
Collecting swmm-toolkit>=0.8.1
  Using cached swmm_toolkit-0.8.1-cp37-cp37m-win_amd64.whl (906 kB)
Collecting aenum
  Using cached aenum-3.0.0-py3-none-any.whl (47 kB)
Installing collected packages: aenum, swmm-toolkit, pyswmm
Successfully installed aenum-3.0.0 pyswmm-1.0.1 swmm-toolkit-0.8.1
```

**Comment by michaeltryby** [comment]
The problem is it’s building the sdist and installing as egg. It needs to be installed  from the wheel.

**Comment by michaeltryby** [comment]
What command are you using to install it now?

**Comment by Leslay-wang** [comment]
python setup.py build
python setup.py install

**Comment by michaeltryby** [comment]
Try this instead
pip install pyswmm

**Comment by Leslay-wang** [comment]
@michaeltryby  Does it mean "from the wheel"? the following

(base) C:\Users\静怡>pip install wheel
Requirement already satisfied: wheel in e:\appdata\anaconda3\lib\site-packages (0.35.1)

(base) C:\Users\静怡>cd E:\AppData\Anaconda3\Scripts

(base) C:\Users\静怡>pip install C:\Users\静怡\Desktop\python\pyswmm\pyswmm-1.0.1-py3-none-any.whl
Processing c:\users\静怡\desktop\python\pyswmm\pyswmm-1.0.1-py3-none-any.whl
Requirement already satisfied: swmm-toolkit>=0.8.1 in e:\appdata\anaconda3\lib\site-packages\swmm_toolkit-0.8.1-py3.8-win-amd64.egg (from pyswmm==1.0.1) (0.8.1)
Requirement already satisfied: aenum in e:\appdata\anaconda3\lib\site-packages\aenum-3.0.0-py3.8.egg (from swmm-toolkit>=0.8.1->pyswmm==1.0.1) (3.0.0)
Installing collected packages: pyswmm
Successfully installed pyswmm-1.0.1

**Comment by jennwuu** [comment]
@Leslay-wang 

Write exactly this into command:

`pip install pyswmm`

**Comment by jennwuu** [comment]
> @michaeltryby Does it mean "from the wheel"? the following
> 
> (base) C:\Users\静怡>pip install wheel
> Requirement already satisfied: wheel in e:\appdata\anaconda3\lib\site-packages (0.35.1)
> 
> (base) C:\Users\静怡>cd E:\AppData\Anaconda3\Scripts
> 
> (base) C:\Users\静怡>pip install C:\Users\静怡\Desktop\python\pyswmm\pyswmm-1.0.1-py3-none-any.whl
> Processing c:\users\静怡\desktop\python\pyswmm\pyswmm-1.0.1-py3-none-any.whl
> Requirement already satisfied: swmm-toolkit>=0.8.1 in e:\appdata\anaconda3\lib\site-packages\swmm_toolkit-0.8.1-py3.8-win-amd64.egg (from pyswmm==1.0.1) (0.8.1)
> Requirement already satisfied: aenum in e:\appdata\anaconda3\lib\site-packages\aenum-3.0.0-py3.8.egg (from swmm-toolkit>=0.8.1->pyswmm==1.0.1) (3.0.0)
> Installing collected packages: pyswmm
> Successfully installed pyswmm-1.0.1

Actually this works too. Are you able to run pyswmm now?

**Comment by Leslay-wang** [comment]
@jennwuu there are still errors. Many names are not defined in shared_enum.py

  File "C:\Users\静怡\Desktop\python\GitHub\pyswmm-master\pyswmm-master\docs\source\examples\print_runoff.py", line 3, in <module>
    from pyswmm import Simulation, Subcatchments

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\links.py", line 9, in <module>
    from swmm.toolkit import shared_enum

  File "E:\AppData\Anaconda3\lib\site-packages\swmm_toolkit-0.8.1-py3.8-win-amd64.egg\swmm\toolkit\shared_enum.py", line 13, in <module>
    class UnitSystem(Enum, start=0):

  File "E:\AppData\Anaconda3\lib\site-packages\swmm_toolkit-0.8.1-py3.8-win-amd64.egg\swmm\toolkit\shared_enum.py", line 23, in UnitSystem
    US

NameError: name 'US' is not defined

**Comment by jennwuu** [comment]
please downgrade your aenum package to 2.2.6 as discussed in here: https://github.com/OpenWaterAnalytics/pyswmm/issues/272

copy this exact command:
`pip install aenum==2.2.6`

**Comment by michaeltryby** [comment]
Maybe we could update the readme to give users "Quick Start" information then direct to more detailed sources of info. 

To me a Quick Start provides the following: 
1) How do I install the pyswmm? 
2) How do I confirm my install is working? 
3) What import statement should I use with pyswmm? 
4) Where can I get more information?

**Comment by Leslay-wang** [comment]
@jennwuu Thank you so much. I will try it tomorrow. It's too late at night. If any problem, I will contact you later, thanks!

**Comment by jennwuu** [comment]
> Maybe we could update the readme to give users "Quick Start" information then direct to more detailed sources of info.
> 
> To me a Quick Start provides the following:
> 
> 1. How do I install pyswmm?
> 2. How do I confirm my install is working?
> 3. What import statement should I use with pyswmm?
> 4. Where can I get more information?

I agree with that although the installation instructions do exist in readmedocs as well. 
https://pyswmm.readthedocs.io/en/stable/install.html

@michaeltryby I think we should probably release an immediate version of swmm-toolkit that is compatible with recent version of aenum as well or lock it to aenum==2.2.6 to avoid issues like this.

**Comment by michaeltryby** [comment]
My thought is to make quick start the first thing seen on the readme after the badges. Make it impossible to miss.

**Comment by Leslay-wang** [comment]
@michaeltryby @jennwuu  I reinstalled the pyswmm using pip install pyswmm and aenum2.2.6. Previous questions are solved and there are new problem.

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\links.py", line 12, in <module>
    from pyswmm.swmm5 import PYSWMMException

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\swmm5.py", line 20, in <module>
    from swmm.toolkit import solver

  File "E:\AppData\Anaconda3\lib\site-packages\swmm\toolkit\solver.py", line 18, in <module>
    from . import _solver

ImportError: DLL load failed while importing _solver: 找不到指定的模块。

**Comment by jennwuu** [comment]
This is really odd error. I think you get that error if it is unable to locate swmm5.dll.
Can you confirm that you see `swmm5.dll` in the following folder?
E:\AppData\Anaconda3\bin\

**Comment by Leslay-wang** [comment]
@jennwuu  I can see swmm5.dll in the folder. And I reinstall everything, but the same problem.

**Comment by jennwuu** [comment]
@Leslay-wang 

I was able to replicate your error using anaconda3

```
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyswmm.links import link
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jenn\anaconda3\lib\site-packages\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links
  File "C:\Users\Jenn\anaconda3\lib\site-packages\pyswmm\links.py", line 12, in <module>
    from pyswmm.swmm5 import PYSWMMException
  File "C:\Users\Jenn\anaconda3\lib\site-packages\pyswmm\swmm5.py", line 20, in <module>
    from swmm.toolkit import solver
  File "C:\Users\Jenn\anaconda3\lib\site-packages\swmm\toolkit\solver.py", line 18, in <module>
    from . import _solver
ImportError: DLL load failed while importing _solver: The specified module could not be found.
```

@michaeltryby any idea why this would happen with anaconda python?

@Leslay-wang In the meantime, the only solution is to install pyswmm using regular python. We will have to look into this issue further for Anaconda python.

**Comment by jennwuu** [comment]
@Leslay-wang I was able to fix the issue by adding the python library path to PATH in user variables. 

For your installation of anaconda3, try adding: 
```
E:\AppData\Anaconda3\lib\bin
``` 
in your system path variable under System Environment variable.

**Comment by michaeltryby** [comment]
As part of patch I will relocate swmm5.lib to site packages folder and set up path to fix this issue.

**Comment by Leslay-wang** [comment]
@jennwuu Thanks, I added the path. But there are still many problems in the solver.py.

  File "C:\Users\静怡\Desktop\python\GitHub\pyswmm-master\pyswmm-master\docs\source\examples\print_runoff.py", line 5, in <module>
    with Simulation('swmm_example.inp') as sim:

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\simulation.py", line 69, in __init__
    self._model.swmm_open()

  File "E:\AppData\Anaconda3\lib\site-packages\pyswmm\swmm5.py", line 219, in swmm_open
    solver.swmm_open(inpfile, rptfile, binfile)

  File "E:\AppData\Anaconda3\lib\site-packages\swmm\toolkit\solver.py", line 509, in swmm_open
    return _solver.swmm_open(f1, f2, f3)

Exception: 
  ERROR 303: cannot open input file.

**Comment by michaeltryby** [comment]
Probably because of Unicode characters in the path.

**Comment by michaeltryby** [comment]
@Leslay-wang sorry you are having so much trouble with the software. It is getting late here. I started a patch to address the bugs you are encountering. Should be able to finish it tomorrow.

**Comment by Leslay-wang** [comment]
@michaeltryby @jennwuu  Thank you so much. Good night!

**Comment by michaeltryby** [comment]
@jennwuu will need to patch pyswmm for the Unicode support issue until we figure out how to handle it in the swig wrap

**Comment by jennwuu** [comment]
@Leslay-wang In the meantime, can you move your model .inp into E drive? `静怡` in `C:\Users\静怡\` is causing errors within pyswmm.

**Comment by Leslay-wang** [comment]
@jennwuu yes, get it.

**Comment by Leslay-wang** [comment]
@michaeltryby @jennwuu  Thanks a lot！The problem has been solved.
When installing pyswmm using regular python or Pycharm, I am able to run pyswmm and the example runs successfully. Sorry to disturb you so much time, maybe the issue is related to Anaconda. If I have other problem, contact you later! Thanks.

**Comment by michaeltryby** [comment]
Ok so let’s break this down and cover the issues identified.

**Comment by jennwuu** [comment]
@michaeltryby these issues should be addressed with the latest version of swmm-toolkit

**Comment by michaeltryby** [comment]
@jennwuu The above area known issues. So shouldn't be too hard to get them covered in the next release.

**Comment by abhiramm7** [comment]
Addressed.
