### ISSUE TITLE
The runoff of the simulation result is all zero

### ISSUE THREAD

**Issue by tianmaxingkong12** [OpenWaterAnalytics/pyswmm#286]
Hello, I run my code with pyswmm, but the runoff of the simulation result is all zero, while when I use SWMM software,I can get right result.

**Desktop (please complete the following information):**
 - Windows
 - Python 3.7
 - PySWMM Version 1.0.1

**Comment by jennwuu** [comment]
@tianmaxingkong12 Can you share your model inp file and the code snippet?

**Comment by tianmaxingkong12** [comment]
[TITLE]
;;Project Title/Notes

[OPTIONS]
;;Option             Value
FLOW_UNITS           LPS
INFILTRATION         HORTON
FLOW_ROUTING         DYNWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        YES
SKIP_STEADY_STATE    YES

START_DATE           07/04/2017
START_TIME           00:00:00
REPORT_START_DATE    07/04/2017
REPORT_START_TIME    00:00:00
END_DATE             07/04/2017
END_TIME             08:18:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             0
REPORT_STEP          00:01:00
WET_STEP             00:01:00
DRY_STEP             00:01:00
ROUTING_STEP         0:00:01 
RULE_STEP            00:00:00

INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  BOTH
FORCE_MAIN_EQUATION  H-W
VARIABLE_STEP        0.75
LENGTHENING_STEP     0
MIN_SURFAREA         1.167
MAX_TRIALS           8
HEAD_TOLERANCE       0.0015
SYS_FLOW_TOL         5
LAT_FLOW_TOL         5
MINIMUM_STEP         0.5
THREADS              1

[EVAPORATION]
;;Data Source    Parameters
;;-------------- ----------------
CONSTANT         0.0
DRY_ONLY         NO

[RAINGAGES]
;;Name           Format    Interval SCF      Source    
;;-------------- --------- ------ ------ ----------
1                VOLUME    0:01     1.0      TIMESERIES 7.4             

[SUBCATCHMENTS]
;;Name           Rain Gage        Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack        
;;-------------- ---------------- ---------------- -------- -------- -------- -------- -------- ----------------
1                1                2                0.000025 25       0.5      0      0                        

[SUBAREAS]
;;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted 
;;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
1                0.01       0.1        0.05       0.05       25         OUTLET    

[INFILTRATION]
;;Subcatchment   MaxRate    MinRate    Decay      DryTime    MaxInfil  
;;-------------- ---------- ---------- ---------- ---------- ----------
1                3.0        0.5        4          7          0         

[LID_CONTROLS]
;;Name           Type/Layer Parameters
;;-------------- ---------- ----------
greenroof        GR
greenroof        SURFACE    150        0.9        0.2        0          5         
greenroof        SOIL       100        0.57       0.34       0.017      165        7          25        
greenroof        DRAINMAT   20         0.5        0.1       

[LID_USAGE]
;;Subcatchment   LID Process      Number  Area       Width      InitSat    FromImp    ToPerv     RptFile                  DrainTo          FromPerv  
;;-------------- ---------------- ------- ---------- ---------- ---------- ---------- ---------- ------------------------ ---------------- ----------
1                greenroof        1       0.25       05         55         0          0          *                        *                0               

[OUTFALLS]
;;Name           Elevation  Type       Stage Data       Gated    Route To        
;;-------------- ---------- ---------- ---------------- -------- ----------------
2                0          FREE                        NO                       

[TIMESERIES]
;;Name           Date       Time       Value     
;;-------------- ---------- ---------- ----------
7.4                         0:00       0.2       
7.4                         0:01       0.2       
7.4                         0:02       0.2       
7.4                         0:03       0         
7.4                         0:04       0.2       
7.4                         0:05       0         
7.4                         0:06       0.2       
7.4                         0:07       0         
7.4                         0:08       0         
7.4                         0:09       0         
7.4                         0:10       0         
7.4                         0:11       0         
7.4                         0:12       0         
7.4                         0:13       0         
7.4                         0:14       0         
7.4                         0:15       0.4       
7.4                         0:16       0.6       
7.4                         0:17       1         
7.4                         0:18       1.2       
7.4                         0:19       1.2       
7.4                         0:20       1         
7.4                         0:21       0.4       
7.4                         0:22       0.2       
7.4                         0:23       0         
7.4                         0:24       0         
7.4                         0:25       0         
7.4                         0:26       0         
7.4                         0:27       0.2       
7.4                         0:28       0         
7.4                         0:29       0         
7.4                         0:30       0         
7.4                         0:31       0         
7.4                         0:32       0         
7.4                         0:33       0         
7.4                         0:34       0         
7.4                         0:35       0         
7.4                         0:36       0         
7.4                         0:37       0         
7.4                         0:38       0         
7.4                         0:39       0         
7.4                         0:40       0         
7.4                         0:41       0         
7.4                         0:42       0         
7.4                         0:43       0         
7.4                         0:44       0         
7.4                         0:45       0         
7.4                         0:46       0         
7.4                         0:47       0         
7.4                         0:48       0         
7.4                         0:49       0         
7.4                         0:50       0         
7.4                         0:51       0         
7.4                         0:52       0         
7.4                         0:53       0         
7.4                         0:54       0         
7.4                         0:55       0         
7.4                         0:56       0         
7.4                         0:57       0         
7.4                         0:58       0         
7.4                         0:59       0         
7.4                         1:00       0         
7.4                         1:01       0         
7.4                         1:02       0         
7.4                         1:03       0         
7.4                         1:04       0         
7.4                         1:05       0         
7.4                         1:06       0         
7.4                         1:07       0         
7.4                         1:08       0         
7.4                         1:09       0         
7.4                         1:10       0         
7.4                         1:11       0         
7.4                         1:12       0         
7.4                         1:13       0         
7.4                         1:14       0         
7.4                         1:15       0         
7.4                         1:16       0         
7.4                         1:17       0         
7.4                         1:18       0         
7.4                         1:19       0         
7.4                         1:20       0         
7.4                         1:21       0         
7.4                         1:22       0         
7.4                         1:23       0         
7.4                         1:24       0         
7.4                         1:25       0         
7.4                         1:26       0         
7.4                         1:27       0         
7.4                         1:28       0         
7.4                         1:29       0         
7.4                         1:30       0         
7.4                         1:31       0         
7.4                         1:32       0         
7.4                         1:33       0         
7.4                         1:34       0         
7.4                         1:35       0         
7.4                         1:36       0         
7.4                         1:37       0         
7.4                         1:38       0         
7.4                         1:39       0         
7.4                         1:40       0         
7.4                         1:41       0         
7.4                         1:42       0         
7.4                         1:43       0         
7.4                         1:44       0         
7.4                         1:45       0         
7.4                         1:46       0         
7.4                         1:47       0         
7.4                         1:48       0         
7.4                         1:49       0         
7.4                         1:50       0         
7.4                         1:51       0         
7.4                         1:52       0         
7.4                         1:53       0         
7.4                         1:54       0         
7.4                         1:55       0         
7.4                         1:56       0         
7.4                         1:57       0         
7.4                         1:58       0         
7.4                         1:59       0         
7.4                         2:00       0         
7.4                         2:01       0         
7.4                         2:02       0         
7.4                         2:03       0         
7.4                         2:04       0         
7.4                         2:05       0         
7.4                         2:06       0         
7.4                         2:07       0         
7.4                         2:08       0         
7.4                         2:09       0         
7.4                         2:10       0         
7.4                         2:11       0         
7.4                         2:12       0         
7.4                         2:13       0         
7.4                         2:14       0         
7.4                         2:15       0         
7.4                         2:16       0         
7.4                         2:17       0         
7.4                         2:18       0         
7.4                         2:19       0         
7.4                         2:20       0         
7.4                         2:21       0         
7.4                         2:22       0         
7.4                         2:23       0         
7.4                         2:24       0         
7.4                         2:25       0         
7.4                         2:26       0         
7.4                         2:27       0         
7.4                         2:28       0         
7.4                         2:29       0         
7.4                         2:30       0         
7.4                         2:31       0         
7.4                         2:32       0         
7.4                         2:33       0         
7.4                         2:34       0         
7.4                         2:35       0         
7.4                         2:36       0         
7.4                         2:37       0         
7.4                         2:38       0         
7.4                         2:39       0         
7.4                         2:40       0         
7.4                         2:41       0         
7.4                         2:42       0         
7.4                         2:43       0         
7.4                         2:44       0         
7.4                         2:45       0         
7.4                         2:46       0         
7.4                         2:47       0         
7.4                         2:48       0         
7.4                         2:49       0         
7.4                         2:50       0         
7.4                         2:51       0         
7.4                         2:52       0         
7.4                         2:53       0         
7.4                         2:54       0         
7.4                         2:55       0         
7.4                         2:56       0         
7.4                         2:57       0         
7.4                         2:58       0         
7.4                         2:59       0         
7.4                         3:00       0         
7.4                         3:01       0         
7.4                         3:02       0         
7.4                         3:03       0         
7.4                         3:04       0         
7.4                         3:05       0         
7.4                         3:06       0         
7.4                         3:07       0         
7.4                         3:08       0         
7.4                         3:09       0         
7.4                         3:10       0         
7.4                         3:11       0         
7.4                         3:12       0         
7.4                         3:13       0         
7.4                         3:14       0         
7.4                         3:15       0         
7.4                         3:16       0         
7.4                         3:17       0         
7.4                         3:18       0.2       
7.4                         3:19       0         
7.4                         3:20       0.2       
7.4                         3:21       0.2       
7.4                         3:22       0.6       
7.4                         3:23       0.4       
7.4                         3:24       0.2       
7.4                         3:25       0         
7.4                         3:26       0         
7.4                         3:27       0.2       
7.4                         3:28       0.2       
7.4                         3:29       0         
7.4                         3:30       0.2       
7.4                         3:31       0.2       
7.4                         3:32       0         
7.4                         3:33       0.2       
7.4                         3:34       0         
7.4                         3:35       0         
7.4                         3:36       0         
7.4                         3:37       0         
7.4                         3:38       0         
7.4                         3:39       0         
7.4                         3:40       0         
7.4                         3:41       0         
7.4                         3:42       0         
7.4                         3:43       0         
7.4                         3:44       0         
7.4                         3:45       0         
7.4                         3:46       0         
7.4                         3:47       0         
7.4                         3:48       0         
7.4                         3:49       0         
7.4                         3:50       0         
7.4                         3:51       0         
7.4                         3:52       0         
7.4                         3:53       0         
7.4                         3:54       0         
7.4                         3:55       0         
7.4                         3:56       0.2       
7.4                         3:57       0         
7.4                         3:58       0.2       
7.4                         3:59       0         
7.4                         4:00       0         
7.4                         4:01       0.2       
7.4                         4:02       0         
7.4                         4:03       0         
7.4                         4:04       0         
7.4                         4:05       0         
7.4                         4:06       0         
7.4                         4:07       0         
7.4                         4:08       0         
7.4                         4:09       0         
7.4                         4:10       0         
7.4                         4:11       0         
7.4                         4:12       0         
7.4                         4:13       0         
7.4                         4:14       0         
7.4                         4:15       0         
7.4                         4:16       0         
7.4                         4:17       0         
7.4                         4:18       0         
7.4                         4:19       0         
7.4                         4:20       0         
7.4                         4:21       0         
7.4                         4:22       0         
7.4                         4:23       0         
7.4                         4:24       0         
7.4                         4:25       0         
7.4                         4:26       0         
7.4                         4:27       0         
7.4                         4:28       0         
7.4                         4:29       0         
7.4                         4:30       0         
7.4                         4:31       0         
7.4                         4:32       0         
7.4                         4:33       0         
7.4                         4:34       0         
7.4                         4:35       0         
7.4                         4:36       0         
7.4                         4:37       0         
7.4                         4:38       0         
7.4                         4:39       0         
7.4                         4:40       0         
7.4                         4:41       0         
7.4                         4:42       0         
7.4                         4:43       0         
7.4                         4:44       0         
7.4                         4:45       0         
7.4                         4:46       0         
7.4                         4:47       0         
7.4                         4:48       0         
7.4                         4:49       0         
7.4                         4:50       0         
7.4                         4:51       0         
7.4                         4:52       0         
7.4                         4:53       0         
7.4                         4:54       0         
7.4                         4:55       0         
7.4                         4:56       0         
7.4                         4:57       0         
7.4                         4:58       0         
7.4                         4:59       0         
7.4                         5:00       0         
7.4                         5:01       0         
7.4                         5:02       0         
7.4                         5:03       0         
7.4                         5:04       0         
7.4                         5:05       0         
7.4                         5:06       0         
7.4                         5:07       0         
7.4                         5:08       0         
7.4                         5:09       0         
7.4                         5:10       0         
7.4                         5:11       0         
7.4                         5:12       0         
7.4                         5:13       0         
7.4                         5:14       0         
7.4                         5:15       0         
7.4                         5:16       0         
7.4                         5:17       0         
7.4                         5:18       0         
7.4                         5:19       0         
7.4                         5:20       0         
7.4                         5:21       0         
7.4                         5:22       0         
7.4                         5:23       0         
7.4                         5:24       0         
7.4                         5:25       0         
7.4                         5:26       0         
7.4                         5:27       0         
7.4                         5:28       0.2       
7.4                         5:29       0         
7.4                         5:30       0         
7.4                         5:31       0         
7.4                         5:32       0         
7.4                         5:33       0.2       
7.4                         5:34       0         
7.4                         5:35       0         
7.4                         5:36       0         
7.4                         5:37       0         
7.4                         5:38       0         
7.4                         5:39       0         
7.4                         5:40       0.2       
7.4                         5:41       0         
7.4                         5:42       0         
7.4                         5:43       0         
7.4                         5:44       0         
7.4                         5:45       0         
7.4                         5:46       0.2       
7.4                         5:47       0         
7.4                         5:48       0         
7.4                         5:49       0         
7.4                         5:50       0.2       
7.4                         5:51       0.2       
7.4                         5:52       0.6       
7.4                         5:53       0.6       
7.4                         5:54       0.6       
7.4                         5:55       0.8       
7.4                         5:56       0.6       
7.4                         5:57       0.6       
7.4                         5:58       0.8       
7.4                         5:59       0.8       
7.4                         6:00       0.6       
7.4                         6:01       0.6       
7.4                         6:02       0.6       
7.4                         6:03       0.6       
7.4                         6:04       0.4       
7.4                         6:05       0.4       
7.4                         6:06       0.2       
7.4                         6:07       0.2       
7.4                         6:08       0.2       
7.4                         6:09       0.2       
7.4                         6:10       0.2       
7.4                         6:11       0         
7.4                         6:12       0.2       
7.4                         6:13       0         
7.4                         6:14       0.2       
7.4                         6:15       0         
7.4                         6:16       0         
7.4                         6:17       0.2       
7.4                         6:18       0.4       
7.4                         6:19       0.2       
7.4                         6:20       0         
7.4                         6:21       0.2       
7.4                         6:22       0         
7.4                         6:23       0         
7.4                         6:24       0.2       
7.4                         6:25       0         
7.4                         6:26       0         
7.4                         6:27       0         
7.4                         6:28       0.2       
7.4                         6:29       0         
7.4                         6:30       0         
7.4                         6:31       0         
7.4                         6:32       0         
7.4                         6:33       0         
7.4                         6:34       0         
7.4                         6:35       0         
7.4                         6:36       0         
7.4                         6:37       0         
7.4                         6:38       0         
7.4                         6:39       0         
7.4                         6:40       0         
7.4                         6:41       0         
7.4                         6:42       0         
7.4                         6:43       0         
7.4                         6:44       0         
7.4                         6:45       0         
7.4                         6:46       0         
7.4                         6:47       0.2       
7.4                         6:48       0         
7.4                         6:49       0         
7.4                         6:50       0         
7.4                         6:51       0         
7.4                         6:52       0         
7.4                         6:53       0         
7.4                         6:54       0         
7.4                         6:55       0         
7.4                         6:56       0         
7.4                         6:57       0         
7.4                         6:58       0         
7.4                         6:59       0         
7.4                         7:00       0         
7.4                         7:01       0.2       
7.4                         7:02       0         
7.4                         7:03       0         
7.4                         7:04       0         
7.4                         7:05       0         
7.4                         7:06       0         
7.4                         7:07       0         
7.4                         7:08       0         
7.4                         7:09       0         
7.4                         7:10       0         
7.4                         7:11       0         
7.4                         7:12       0.2       
7.4                         7:13       0         
7.4                         7:14       0         
7.4                         7:15       0         
7.4                         7:16       0         
7.4                         7:17       0.2       
7.4                         7:18       0         
7.4                         7:19       0         
7.4                         7:20       0         
7.4                         7:21       0         
7.4                         7:22       0         
7.4                         7:23       0         
7.4                         7:24       0         
7.4                         7:25       0         
7.4                         7:26       0         
7.4                         7:27       0         
7.4                         7:28       0         
7.4                         7:29       0         
7.4                         7:30       0         
7.4                         7:31       0         
7.4                         7:32       0         
7.4                         7:33       0         
7.4                         7:34       0         
7.4                         7:35       0         
7.4                         7:36       0.2       
7.4                         7:37       0         
7.4                         7:38       0         
7.4                         7:39       0         
7.4                         7:40       0         
7.4                         7:41       0         
7.4                         7:42       0         
7.4                         7:43       0         
7.4                         7:44       0         
7.4                         7:45       0         
7.4                         7:46       0         
7.4                         7:47       0         
7.4                         7:48       0         
7.4                         7:49       0         
7.4                         7:50       0         
7.4                         7:51       0         
7.4                         7:52       0         
7.4                         7:53       0         
7.4                         7:54       0         
7.4                         7:55       0         
7.4                         7:56       0         
7.4                         7:57       0         
7.4                         7:58       0         
7.4                         7:59       0         
7.4                         8:00       0         
7.4                         8:01       0         
7.4                         8:02       0         
7.4                         8:03       0         
7.4                         8:04       0         
7.4                         8:05       0         
7.4                         8:06       0         
7.4                         8:07       0         
7.4                         8:08       0         
7.4                         8:09       0         
7.4                         8:10       0         
7.4                         8:11       0         
7.4                         8:12       0         
7.4                         8:13       0         
7.4                         8:14       0         
7.4                         8:15       0         
7.4                         8:16       0         
7.4                         8:17       0         
7.4                         8:18       0.2       

[REPORT]
;;Reporting Options
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL

[TAGS]

[MAP]
DIMENSIONS 0.000 0.000 10000.000 10000.000
Units      None

[COORDINATES]
;;Node           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
2                144.804            4054.514          

[VERTICES]
;;Link           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------

[Polygons]
;;Subcatchment   X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
1                519.591            6967.632          
1                2802.385           6967.632          
1                2802.385           4872.232          
1                485.520            4872.232          
1                485.520            6967.632          

[SYMBOLS]
;;Gage           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
1                42.589             7427.598

**Comment by tianmaxingkong12** [comment]
from pyswmm import Simulation,LidControls,Subcatchments
with Simulation('7.4_2.inp') as sim:
    SC1 = Subcatchments(sim)["1"]
    print(SC1.area)
    sim.step_advance(60)
    print(SC1.runoff)
    print(SC1.slope)
    print(SC1.area)
    for step in sim:
        # runoff = SC1.runoff*60/(SC1.area)
        print(sim.current_time,SC1.rainfall,SC1.runoff)
        # print(runoff)

**Comment by tianmaxingkong12** [comment]
That's my model and code

**Comment by jennwuu** [comment]
Interesting. There is no runoff from the subcatchment because all the flow goes to the green roof (occupies 100% of the subcatchment).

In the .rpt file, the peak flow for Subcatchment 1 is also 0 L/s. I wonder if the .out file is storing run off data from the green roof.

**Comment by tianmaxingkong12** [comment]
But if I use SWMM software, I can get right result. Some runoff are not zero

**Comment by tianmaxingkong12** [comment]
![image](https://user-images.githubusercontent.com/29156524/127258732-7d4ea5c7-4913-4fbb-871f-766aaf2f3e67.png)

**Comment by jennwuu** [comment]
@tianmaxingkong12 you are probably seeing subcatchment runoff = green roof storage drain 

You can get the same values using pyswmm using the following code snippet.

```python
from pyswmm import Simulation, LidControls, LidGroups, Subcatchments

with Simulation('7.4_2.inp') as sim:
    SC1 = Subcatchments(sim)["1"]
    print(SC1.area)
    sim.step_advance(60)
    print(SC1.runoff)
    print(SC1.slope)
    print(SC1.area)
    lid_group = LidGroups(sim)["1"]
    lid = lid_group[0]
    print(lid.lid_control)
    for step in sim:
        # runoff = SC1.runoff*60/(SC1.area)
        area_factor = SC1.area * 10000 # m2/ha
        mm_factor = 0.001 # m/mm
        rate_factor = 1000 # l/m3
        time_factor = 1/3600 # hr/s
        inflow_rate = round(lid.surface.inflow * area_factor * mm_factor * rate_factor * time_factor, 5)
        drain_rate = round(lid.storage.drain * area_factor * mm_factor * rate_factor * time_factor, 5)
        print(sim.current_time,
             # f'{lid.surface.inflow} mm/hr {inflow_rate} l/s',
              f'{lid.storage.drain} mm/hr {drain_rate} l/s')


```

**Comment by tianmaxingkong12** [comment]
Thank you very much
