### ISSUE TITLE
Can pyswmm use external time series data?

### ISSUE THREAD

**Issue by dokyno** [OpenWaterAnalytics/pyswmm#289]
Can pyswmm use external time series data?
If possible. How would it be?

**Comment by bemcdonnell** [comment]
@dokyno, what are you hoping to accomplish? Are you asking if pyswmm can run a model with an external timeseries file references in the INP or if your script can read the timeseries file?

**Comment by dokyno** [comment]
When running a simulation, is it possible to load and apply the time series data without inputting the time series to the INP file?

**Comment by dokyno** [comment]
> @dokyno, what are you hoping to accomplish? Are you asking if pyswmm can run a model with an external timeseries file references in the INP or if your script can read the timeseries file?

When running a simulation, is it possible to load and apply the time series data without inputting the time series to the INP file?

**Comment by dokyno** [comment]
I want to check inflow using real-time data, so I'm looking for a way.

**Comment by jennwuu** [comment]
@dokyno Are you comparing model inflow versus measured flow during model simulation? Can you store model flow result and compare to measured data after?

**Comment by dokyno** [comment]
> @dokyno Are you comparing model inflow versus measured flow during model simulation? Can you store model flow result and compare to measured data after?

The first plan was to measure the inflow through pyswmm with real-time rainfall data stored in the db. But I wonder if it is possible to put external data into pyswmm.

**Comment by jennwuu** [comment]
@dokyno Please share some code snippet and example data and we can work through the code together to see if we can get what you need.

**Comment by floriandorre** [comment]
> > @dokyno Are you comparing model inflow versus measured flow during model simulation? Can you store model flow result and compare to measured data after?
> 
> The first plan was to measure the inflow through pyswmm with real-time rainfall data stored in the db. But I wonder if it is possible to put external data into pyswmm.

What you can for sure do is setting the RainGage total_precipitation using pyswmm, then your value can come from anywhere.

**Comment by dokyno** [comment]
> > > @dokyno Are you comparing model inflow versus measured flow during model simulation? Can you store model flow result and compare to measured data after?
> > 
> > 
> > The first plan was to measure the inflow through pyswmm with real-time rainfall data stored in the db. But I wonder if it is possible to put external data into pyswmm.
> 
> What you can for sure do is set the RainGage total_precipitation using pyswmm, then your value can come from anywhere.
> https://pyswmm.readthedocs.io/en/latest/reference/raingages.html

thx for reply, 
Isn't the value derived based on the time series data already in the inp file?

![swmm](https://user-images.githubusercontent.com/76770604/130378665-aac09044-aa21-42e6-ae82-83bd2810c911.png)

If I have only terrain data in the inp file, is there a way to apply the time series as above?

**Comment by dokyno** [comment]
with Simulation(inp_file) as sim:
        sim.step_advance(60) #simulate per 1 minute
        nodes = [node for node in Nodes(sim) if node.is_outfall()]
         for index,step in enumerate(sim):
            inflow.append(compute_inflow(nodes))

def compute_inflow(nodes):
    inflow = 0.0
    for node in nodes:
        inflow += node.total_inflow * 60
    else:
        return inflow

Currently I need the amount of water entering the reservoir as a simulation result. 
I understand that the simulation result is received as the time series of the .inp file, but is there a way to perform simulation by separately inputting time series data like in other swmm?

**Comment by jennwuu** [comment]
You can check out this function to add inflow manually per timestep: https://pyswmm.readthedocs.io/en/stable/reference/nodes.html#pyswmm.nodes.Node.generated_inflow
