### ISSUE TITLE
Problem with SWMM5 engine selector

### ISSUE THREAD

**Issue by openSourcerer9000** [OpenWaterAnalytics/pyswmm#290]
So I need to use SWMM v5.1.014, as this 5.3dev engine is giving me wildly different results. I created a new folder called windows and copied the swmm5.dll straight from C:\Program Files (x86)\EPA SWMM 5.1.014 into it  C:\Users\openSourcerer\anaconda3\envs\swmmenv\Lib\site-packages\pyswmm\lib\windows, renaming the DLL as swmm5.1.dll. Then tried to set it as my SWMM version with the imports in this order:

```
from pyswmm.lib import use
use('swmm5.1.dll')
from pyswmm import Simulation
```
as described in [https://github.com/OpenWaterAnalytics/pyswmm/pull/78](https://github.com/OpenWaterAnalytics/pyswmm/pull/78)

It sets the location just fine, but I get the following error when trying to run a sim:
```
~\anaconda3\envs\swmmenv\lib\site-packages\pyswmm\simulation.py in __init__(self, inputfile, reportfile, outputfile, swmm_lib_path)
     66                  outputfile=None,
     67                  swmm_lib_path=None):
---> 68         self._model = PySWMM(inputfile, reportfile, outputfile, swmm_lib_path)
     69         self._model.swmm_open()
     70         self._isOpen = True

~\anaconda3\envs\swmmenv\lib\site-packages\pyswmm\swmm5.py in __init__(self, inpfile, rptfile, binfile, swmm_lib_path)
    131         if os.name == 'nt':
    132             # Windows Support
--> 133             self.SWMMlibobj = ctypes.WinDLL(swmm_lib_path)
    134 
    135         if sys.platform == 'darwin':

~\anaconda3\envs\swmmenv\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    380 
    381         if handle is None:
--> 382             self._handle = _dlopen(self._name, mode)
    383         else:
    384             self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application
```

Not knowing how the how the swmm5.3dev dll was compiled and is being run, this is a seriously gnarly exercise to attempt just to use the normal version of SWMM. I'm assuming the issue is that the EPA version is 32 bit and I'm on a 64 bit computer, but I'm not positive. My feature request would be to just include the few most recent versions of SWMM and let the user toggle between them without things getting ugly. For now, how do I get this engine selector to work?

Thank you,

Windows 10 64 bit
python 3.9 64 bit
pyswmm 0.6.2 (the latest up on conda-forge)
anaconda env

**Comment by jennwuu** [comment]
Hey @openSourcerer9000, thanks for checking out pyswmm. Pyswmm does not support regular swmm.dll. PySWMM uses SWMM from OWA-SWMM repo: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model which has API features.

**Comment by michaeltryby** [comment]
@openSourcerer9000 You could use pyswmm dev. I think that is using SWMM v5.1.14.

**Comment by dickinsonre** [comment]
Will PySWMM dev use SWMM 5.1.15 soon?

**Comment by bemcdonnell** [comment]
@michaeltryby is SWMM5.1.14 x86 or x86-64?  @openSourcerer9000 is using 64bit python making me think that it's the 32 vs 64bit swmm issue.

**Comment by michaeltryby** [comment]
@bemcdonnell OWA/SWMM is exclusively 64bit.

**Comment by bemcdonnell** [comment]
@michaeltryby it Hasn’t been throughout our history. It is now. This user is on 0.6.2. But the user pulled it from Conda. Back then, we were not supporting 64bit. I think @goanpeca built that wheel before. No one had ported swmm to 64 but until recently. @michaeltryby #historylesson 🤣🤣🤣

**Comment by michaeltryby** [comment]
@bemcdonnell I see.  Last Call: Is there anyone out there who wants to maintain the conda package? 

Given that we have limited development resources and we don't maintain it, perhaps we should deprecate the Conda version?  That would help to eliminate a source of confusion for our users.

**Comment by bemcdonnell** [comment]
@goanpeca, do you mind if I delete those old engines from conda?  I just check and I still have access.  I think we bumped into the problem of maintainability which is why they were never updated. :)

**Comment by bemcdonnell** [comment]
> Will PySWMM dev use SWMM 5.1.15 soon?

@dickinsonre, I believe the dev team is hoping to learn from all the bugs from the PySWMM-v1.x release before performing an engine update.  OWA-SWMM is currently based on USEPA-SWMM-v5.1.14, I believe.

**Comment by dickinsonre** [comment]
Thanks, a wise approach.

**Comment by goanpeca** [comment]
> do you mind if I delete those old engines from conda? I just checked and I still have access. I think we bumped into the problem of maintainability which is why they were never updated. :)

Sounds good!
