### ISSUE TITLE
Get flooding nodes results from model using interface file

### ISSUE THREAD

**Issue by BenoitMFr** [OpenWaterAnalytics/pyswmm#292]
I'm trying to get flooding results for every nodes in model which using an interface file (for injecting results from french runoff method).
Python console return 
_Exception:
ERROR 351: cannot open routing interface file %s._

Is there a trick or other method to make it work ?

**Comment by abhiramm7** [comment]
Closing due to inactively.

**Comment by abhiramm7** [comment]
Seems like this is an issue with how the file is defined in ink file. Closing it for now.
