### ISSUE TITLE
Is there a way to convert the total_precip value of rainingage?

### ISSUE THREAD

**Issue by dokyno** [OpenWaterAnalytics/pyswmm#295]
https://github.com/OpenWaterAnalytics/pyswmm/blob/f6edd28f97a52b67018981f64f311d7a005e23e7/pyswmm/raingages.py#L170-L199

The percip value of rainage seems to be intensity.
If the value I have is cumulative rainfall data, is there any way to turn it into intensity?

**Comment by floriandorre** [comment]
You can either use Intensity or millimeters the setting of it can be done on the raingage itself

**Comment by dokyno** [comment]
>>> from pyswmm import Simulation, RainGages
        >>>
        >>> with Simulation('tests/data/TestModel1_weirSetting.inp') as sim:
        ...     rg1 = RainGages(sim)["Gage1"]
        ...     print(rg1.total_precip)
        ...     rg1.total_precip = 0.2
        ...     print(rg1.total_precip)
        >>> 1.0
        >>> 0.2

When I set the value of raingage as above, isn't the value going into intensity?

**Comment by dokyno** [comment]
> You can either use Intensity or millimeters the setting of it can be done on the raingage itself

    >>> from pyswmm import Simulation, RainGages
    >>>
    >>> with Simulation('tests/data/TestModel1_weirSetting.inp') as sim:
    ...     rg1 = RainGages(sim)["Gage1"]
    ...     print(rg1.total_precip)
    ...     rg1.total_precip = 0.2
    ...     print(rg1.total_precip)
    >>> 1.0
    >>> 0.2
When I set the value of raingage as above, isn't the value going into intensity?

**Comment by floriandorre** [comment]
I think this is done automatically by looking at what is set on the raingage object.
