### ISSUE TITLE
Pyswmm simulation error: ImportError: DLL load failed while importing _solver: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Husnain2244** [OpenWaterAnalytics/pyswmm#296]
Hi everyone, 

I am new to Python and Pyswmm. I am trying to simulate a test model in Spyder (Python 3.8, 64-bit) on a  64-bit  system.  Please find below error and let me know where I am wrong. I would really appreciate your suggestions. Many Thanks

runfile('E:/VARS_Research/pyswmm_master/pyswmm_master/pyswmm/tests/data/Test_code.py', wdir='E:/VARS_Research/pyswmm_master/pyswmm_master/pyswmm/tests/data')
Traceback (most recent call last):

  File "E:\VARS_Research\pyswmm_master\pyswmm_master\pyswmm\tests\data\Test_code.py", line 2, in <module>
    from pyswmm import Simulation

  File "C:\Users\Hydraulic Group\anaconda3\lib\site-packages\pyswmm\__init__.py", line 11, in <module>
    from pyswmm.links import Link, Links

  File "C:\Users\Hydraulic Group\anaconda3\lib\site-packages\pyswmm\links.py", line 12, in <module>
    from pyswmm.swmm5 import PYSWMMException

  File "C:\Users\Hydraulic Group\anaconda3\lib\site-packages\pyswmm\swmm5.py", line 20, in <module>
    from swmm.toolkit import solver

  File "C:\Users\Hydraulic Group\anaconda3\lib\site-packages\swmm\toolkit\solver.py", line 18, in <module>
    from . import _solver

ImportError: DLL load failed while importing _solver: %1 is not a valid Win32 application.

**Comment by jennwuu** [comment]
Hello @Husnain2244, this is a known issue with anaconda. This should be fixed in the next release.

In the meantime, you can only use pyswmm with regular Python 64 bit.

thanks,
Jenn

**Comment by Husnain2244** [comment]
Dear @jennwuu, Thanks for your prompt response. You saved my time and effort.

**Comment by michaeltryby** [comment]
Hey @jennwuu I this is different than the Anaconda issue we encountered before.

**Comment by jennwuu** [comment]
@michaeltryby oh you’re right. For the previous anaconda, it says DLL failed to import. This is saying that it is invalid 32 application. @michaeltryby is it caused by 32bit python? 

https://github.com/OpenWaterAnalytics/swmm-python/issues/79

@Husnain2244 can you confirm your anaconda python version?
