### ISSUE TITLE
Update List for Projects using PySWMM

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/pyswmm#297]
Update projects using PySWMM in documentation: https://pyswmm.readthedocs.io/en/stable/cite.html#projects-using-pyswmm

Please comment on this issue if you want like to include your project in this list.

**Comment by jennwuu** [comment]
Oberascher, M., Kinzel, C., Kastlunger, U., Kleidorfer, M., Zingerle, C., Rauch, W., Sitzenfrei, R., 2021. Integrated urban water management with micro storages developed as an IoT-based solution – the smart rain barrel. Environmental Modelling & Software, 105028. https://doi.org/10.1016/j.envsoft.2021.105028.

**Comment by dickinsonre** [comment]
Nice paper with a lot of PySWMM! The download is free as well.
