### ISSUE TITLE
Node coordinates

### ISSUE THREAD

**Issue by mattyd100** [OpenWaterAnalytics/pyswmm#300]
Is it possible to access the x, y coordinates of the nodes?

I saw a post from a few years ago related to this topic, but was not able to determine if this feature was incorporated.

**Comment by jennwuu** [comment]
If you're looking to access X,Y coordinates from model input file, you should check out [swmmio](https://github.com/aerispaha/swmmio). Super cool project where you can edit model .inp data easily before starting the simulation.
