### ISSUE TITLE
Deprecate swmm_lib_path in Simulation 

### ISSUE THREAD

**Issue by jennwuu** [OpenWaterAnalytics/pyswmm#303]
Since updating pyswmm to use swmm-python, swmm_lib_path is not useful.

**Comment by bemcdonnell** [comment]
RIP

**Comment by bemcdonnell** [comment]
@jennwuu has this been closed yet?

**Comment by jennwuu** [comment]
@bemcdonnell No not yet, oops

**Comment by abhiramm7** [comment]
Done and dusted. Kudos @jennwuu
