### ISSUE TITLE
Is it possible to define "LID USAGE" in the pyswmm itself ?

### ISSUE THREAD

**Issue by DINBOR** [OpenWaterAnalytics/pyswmm#304]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.  Good to place code here with support files.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - Python Version [e.g. Python 3.6-x86]
 - PySWMM Version [e.g. v0.4.8]

**Additional context**

**Comment by dickinsonre** [comment]
It might be interesting to add new LID Coverage during a run if you are running many runs.  Sort of like a quasi Sustain run - how is my LID flow and water quality changing as you add move units or mix of units.

**Comment by jennwuu** [comment]
@dickinsonre You might be able to do what you are describing by changing lid unit number after defining lid usage.
