### ISSUE TITLE
problem about lib module

### ISSUE THREAD

**Issue by dark957** [OpenWaterAnalytics/pyswmm#306]
When I tried to set the SWMM5 DLL,  I followed the steps in https://pyswmm.readthedocs.io/en/latest/reference/lib.html.
However, the system reported that module 'pyswmm' has no attribute 'lib'.
I wonder how to change the SWMM5 DLL.

**Comment by jennwuu** [comment]
Hello @dark957, this is a deprecated feature after release of version 1.0+

**Comment by bemcdonnell** [comment]
@dark957 based on the newer direction of the project, we have chosen a python-to-C strategy that is much more developer-friendly (we do not need CTypes anymore).  This is much faster.   Unfortunately, this came at the cost of no longer supporting the old linking process to a SWMM.DLL.   If you need this functionality, it will be best to revert back to PySWMM-v0.6
