### ISSUE TITLE
Pip install pyswmm does not install julian

### ISSUE THREAD

**Issue by magoorden** [OpenWaterAnalytics/pyswmm#312]
**Describe the bug**
When running ```pip install pyswmm```, the julian package is not installed. 

**To Reproduce**
Make sure to have a clean (virtual) environment to reproduce the bug.
1. Execute ```pip install pyswmm```.
2. Check that it is installing version 1.1.0 of pyswmm.
3. Try to run a python script using pyswmm.
4. Observe that it will throw an error: 
```
Traceback (most recent call last):
  File "scripts/swmm_stratego_control.py", line 3, in <module>
    from pyswmm import Simulation, Nodes, Links, RainGages, Subcatchments
  File "/home/tacas22/.local/lib/python3.8/site-packages/pyswmm/__init__.py", line 16, in <module>
    from pyswmm.output import Output
  File "/home/tacas22/.local/lib/python3.8/site-packages/pyswmm/output.py", line 15, in <module>
    from julian import from_jd
ModuleNotFoundError: No module named 'julian'
```

**Expected behavior**
The julian package is also automatically installed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Python Version 3.8
 - PySWMM Version 1.1.0

**Comment by bemcdonnell** [comment]
@magoorden sorry about that! Thanks for the bug report.  I’ll spin up and Ubuntu instance today to check what is going on with the install process. For now, did you simply run ‘pip install julian’ to get it working?

**Comment by magoorden** [comment]
Yes, manually installing julian does solve the problem. So that is my workaround for now (hopefully I don't forget to do that when I need to install pyswmm again).
