### ISSUE TITLE
What is the unit of total_periods for outfall statistics?

### ISSUE THREAD

**Issue by zxyzmbc1030** [OpenWaterAnalytics/pyswmm#334]

**Comment by zxyzmbc1030** [comment]
> `total_periods` is an integer value and the value represents the number of data points. This value should be the number of timesteps within your timeseries if all inflow values are greater than the minimum flow value.
> 
> Reference code: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/025337c026dc2b6d493fb23ab05016329f7547cb/src/solver/stats.c#L552-L568

**Comment by zxyzmbc1030** [comment]
@jennwuu thank you for the answer. What is the minimum flow value? Is it equal to 0 by default? I refer to the codes and line 556 there is a variable called "MIN_RUNOFF_FLOW" but it is not defined in "stats.c".

**Comment by dickinsonre** [comment]
MIN_RUNOFF_FLOW is used in the subcatchment runoff to define surface runoff - if the runoff is less than MIN_RUNOFF_FLOW the it is reported as zero (these are internal SWMM 5 engine changes)  - not PySWMM.

**Comment by jennwuu** [comment]
Like @dickinsonre explained `MIN_RUNOFF_FLOW` is an internal value in the SWMM C engine. You can find the value here: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/025337c026dc2b6d493fb23ab05016329f7547cb/src/solver/consts.h#L47

**Comment by zxyzmbc1030** [comment]
Thank you. But I still don't understand the meaning of total_periods for outfall. If it is compared to minimum flow value (or MIN_RUNOFF_FLOW), then does total_periods denote the duration when outfall has inflow? To say, can I multiply total_periods with time step to calculate outfall inflow duration?

**Comment by jennwuu** [comment]
Correct, I think it is fair to interpret `total_periods` as the duration when outfall has inflow. `total_periods` is only incremented when flow exceeds MIN_RUNOFF_FLOW.

**Comment by abhiramm7** [comment]
@zxyzmbc1030 closing this issue for now. Let us know if you have any additional questions.
