### ISSUE TITLE
Add plot helpers

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#34]
It would be super cool to have some plot subroutines based on matplotlib (optional dependency) and get ready to use plots with not so much work.

Thoughts @bemcdonnell?

**Comment by bemcdonnell** [comment]
I think passing a plot / axis handle with be very useful. One important first step is open of the functions in the SWMM5-API to pull the coordinates from an Input file.

**Comment by bemcdonnell** [comment]
that is... Assuming you meant maps and not hydraulic results. We could easily plot results now.  Could you pose a few ideas on layout?

**Comment by goanpeca** [comment]
Maps, results all :-p

**Comment by goanpeca** [comment]
For ideas I dont know.. if we have the `Network` object we could do soemhting like

```python
nwk = Network.from_file('some-file.inp')
nwk.plot()
```

And that would plot the network with some base labels identifying stuff. That would be very handy :-), don't you think?

We need access to the coordinates!

**Comment by bemcdonnell** [comment]
Whatever we decide to do, I feel that passing axis handles will be the best approach. Then we leave customization up to the user. Thoughts? Both?

**Comment by goanpeca** [comment]
you mean returning axes? sure sounds good

**Comment by bemcdonnell** [comment]
For example https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.drawing.nx_pylab.draw_networkx_nodes.html#networkx.drawing.nx_pylab.draw_networkx_nodes 

Pass an axis object to the function

**Comment by goanpeca** [comment]
Sure, but thats optional...

**Comment by abhiramm7** [comment]
@bemcdonnell I used networkx for a plotting a storm water network, with radius of each node representing relative volume. I have a adhoc way doing it from .inp file. Networkx seems to be a good way to plot swmm networks, they look visually better and are configurable. I tried using matplotlib and couldnt figure out a good way to do it. Here is a example. 
<img width="1307" alt="screen shot 2017-04-07 at 8 34 48 pm" src="https://cloud.githubusercontent.com/assets/14915561/24823902/b65eeb24-1bd1-11e7-9b07-e743050349ac.png">

**Comment by goanpeca** [comment]
Hi @abhiramm7 definitely something worth considering. Maybe post a gist ?

**Comment by aerispaha** [comment]
@abhiramm7 this is really cool. I'm working on a project [over here](https://github.com/aerispaha/trace) that is making heavy use of Networkx for the purpose of sewer design calculations. One of the outputs from the process is a visualization of the network to a Mapbox interface, that you may find interesting. Here's an example showing the upstream area and time of concentration path for a selected sewer:
![networkx_trace](https://cloud.githubusercontent.com/assets/6521360/24874453/b30d7b0c-1df2-11e7-9bc0-8ac33b2691dc.jpg)

Additionally, I've put a lot of time into visualization methods in the [swmmio](https://github.com/aerispaha/swmmio) project. There I use PILLOW to generate visualizations as PNG files based directly on data in inp and rpt SWMM files. I also use Pandas for convenience. Some of this could probably be adapted for pyswmm so we aren't reinventing the wheel. It was annoying, for example, to convert coordinates in SWMM inp files into pixel coordinates for drawing on a PNG canvas; no one should have to do that again.

**Comment by abhiramm7** [comment]
@aerispaha Wow swmmio is amazing ! I can definitely use for some of my stuff.  I had a hard time getting the coordinates from inp to networkx too. Thanks for sharing them. 

@goanpeca Sure thing, I'll clean it up and post it.

**Comment by bemcdonnell** [comment]
@abhiramm7 and @aerispaha,

Sorry for my delay here - I was on vacation.  For network plotting I wonder if a better strategy would be to develop a package that uses `pyswmm` as a dependency.  As for `pyswmm` and plot helpers, I think we should focus on passing simple axis handles that support post-processing as well as plotting results during simulation time.  

I think having a network plot utility is a great thing but I'm concerned about long term maintenance.  If it was a separate package but called `pyswmm`, I feel that strategically it would make the most sense.  Based on the example that @aerispaha, provided above, from my naive perspective I'm concerned that there are so many cases that need to be considered WRT style.  Those are my thoughts/concerns.  Don't get me wrong, however. I'm not opposed! 

I think @goanpeca had a good suggestion for clarification:

> Hi @abhiramm7 definitely something worth considering. Maybe post a gist ?

I have an example profile plotting tool that I wrote a long time ago (https://www.youtube.com/watch?v=YYZ6Of1RXzM&feature=youtu.be).  My plan is to develop this into a package that calls pyswmm.

**Comment by abhiramm7** [comment]
@goanpeca here is a crude network visualization using networkx and swmmio, with conduits and ponds. 
 https://gist.github.com/abhiramm7/3ff0eb3339b49ec17a943bcfe1f79d61. 
![figure_1](https://cloud.githubusercontent.com/assets/14915561/25649579/9e051a1c-2fa4-11e7-98ab-4eac046589d7.png)

@bemcdonnell yeah, you are right. It makes more sense to have these as  visualizations as a separate package. 

@aerispaha swmmio saved me a ton of time. Thanks for sharing it !
