### ISSUE TITLE
SWMM5.2 Features

### ISSUE THREAD

**Issue by LunarMilkman** [OpenWaterAnalytics/pyswmm#394]
Add support for SWMM5.2. Specifically, it added added new features such as streets and inlets. See [the new features on the SWMM github](https://github.com/USEPA/Stormwater-Management-Model/blob/develop/doc/New%20SWMM%205.2%20Features.md).

**Comment by bemcdonnell** [comment]
@LunarMilkman 

working on it!! :-)

https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/378

**Comment by lxciwhr** [comment]
Hello, when will Pyswmm, which supports version 5.2, be released?

**Comment by bemcdonnell** [comment]
@karosc - I think it’s very close, right?

**Comment by lxciwhr** [comment]
Thank you very much~

**Comment by karosc** [comment]
We have not released 5.2 into swmm-python yet. Still waiting on feedback in OWA SWMM with regards to versioning our api.

**Comment by LunarMilkman** [comment]
@bemcdonnell just checking on this again. Thanks for all your contributions!

**Comment by bemcdonnell** [comment]
@LunarMilkman we are wrapping up the work for incorporating 5.2.0 and 5.2.1 into the dependency libraires for pyswmm. Getting super close on all that.  Either 5.2.2 or 5.2.3 will mean releasing pyswmm-2.x. So a lot is happening! If you watch the pyswmm project, we should be making an announcement very soon.
