### ISSUE TITLE
No module error (Ho I do fix)

### ISSUE THREAD

**Issue by BilalKemal** [OpenWaterAnalytics/pyswmm#396]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14688\4056193279.py in <module>
      1 from pyswmm import Simulation
----> 2 import swmmio

ModuleNotFoundError: No module named 'swmmio'

**Comment by abhiramm7** [comment]
You can install swmmio with pip 🙂

**Comment by BilalKemal** [comment]
I have already installed and solved the problem

**Comment by BilalKemal** [comment]
Thanks
