### ISSUE TITLE
Non-Python user-friendly interface file.

### ISSUE THREAD

**Issue by swmm-js** [OpenWaterAnalytics/pyswmm#401]
I'd like to propose co-development of a schema for a text-based interface file for Pyswmm. This file will be capable of carrying a traditional .inp file as either a referenced link or an appended string.

The goal is to make the strengths of Pyswmm available to users that do not have Python skills while at the same time allowing for a safe way to make Pyswmm calls via networks.

For other library concerns, such as charting, mapping, result processing etc, these are external operations that would be abstracted from the user server-side. Any standard library needs would still be serviced using the current programming interface, this proposal doesn't intend to change any of the current pythonic interfacing system.

The basic structure of the file so far relies heavily on Timeseries-like tracking of object properties. This schema started as a way to track assets over long periods of time, but I realized Pyswmm would be perfect for meshing long-term and event-based asset analysis.

**Comment by bemcdonnell** [comment]
@swmm-js, do you mind sharing an architecture drawing of how you plan to integrate with pyswmm? Something that shows some more context would be helpful

**Comment by swmm-js** [comment]
I'm working on the parser now. The demo will operate on a modified model_rain.inp from the tests/data/ folder. This demo shows the asset tracking abilities of the file and since the time series is shortened, it shows off a chartable modification to demo the effects of a (somewhat large) liner on a system.

The system can be called like this:
`  with Simulation('tests/data/model_rain_liner.inp', pyswmmfile='tests/data/demo.psi') as sim:`

The very early demo version of the asset tracking file looks like this:

tests/data/demo.psi :
```
[XSECTIONS]
;;Link           Date       Time       Value     Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   
;;-------------- ---------- ---------- ---------------------- ---------------- ---------- ---------- ---------- ---------- ----------
C2               08/18/2017 01:00:00   1.0       CIRCULAR     2.9                0          0          0          1                    

```

**Comment by bemcdonnell** [comment]
@swmm-js the feature seems interesting. I think we can accomplish the same thing, however, if we expose **kwargs to the simulation init class. This way, the feature is agnostic of your particular solution and is inherently general. Does that make sense?

**Comment by swmm-js** [comment]
Yes, I can see this healthily existing as a wrapper outside of Pyswmm. That would make it so that Pyswmm won't need to be modified at all. For this particular use case, that would make the wrapper work like this:

psi_wrapper(file.psi, inp.inp) ->
  effectArray = parse(file.psi)
  Simulation(inp.inp) as sim ->
    for step in sim ->
      for effect in effectArray ->
        # parsing code would be more detailed that this
        if sim.current_time >= effect.time
          modify_target(effect.target, effect.effect, effect.value)

I'll close this up.

**Comment by swmm-js** [comment]
Works better as a separate system.
