### ISSUE TITLE
Implement swmmtoolbox into this repo

### ISSUE THREAD

**Issue by ghost** [OpenWaterAnalytics/pyswmm#5]
https://bitbucket.org/timcera/swmmtoolbox/

**Comment by bemcdonnell** [comment]
I just noticed this message.. My apologies. I will study the swmmtoolbox and see if there are elements that are in line with the goals of pyswmm. Conceptually we are hoping to have few dependencies. Furthermore, we are forecasting a newer SWMM API to more quickly parse and output files.
