### ISSUE TITLE
All dev on dev

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#50]
@goanpeca, Once we fix all the issues, from now on lets work off of a `dev` branch instead of master.

**Comment by goanpeca** [comment]
@bemcdonnell why?

We can leave master as dev.. if we need to keep track of the current version we make a branch when we make the release...

So we have master and v0.3.x

**Comment by goanpeca** [comment]
The thing is that master is not currently a stable release... that will only happen when we make the actual release... which should be in a couple of days I guess.
