### ISSUE TITLE
Packaging and Distribution

### ISSUE THREAD

**Issue by goanpeca** [OpenWaterAnalytics/pyswmm#6]
Great initiative, what I meant by this, was if at any time it has been given thought to provide an interface to swmm that is more pythonic on top of what swmm provides.

This can go from simple thing as naming conventions (SWMMSomething vs swmm_something) to higher level abstractions, that would appeal more to python developers (and possible contributors) and users.

**Comment by bemcdonnell** [comment]
@goanpeca Thank you for your interest in this tool.  Can you be a little more specific on what you are suggesting?

**Comment by goanpeca** [comment]
Disclaimer, I have not used this library yet, but I have used [this other wrapper](https://pypi.python.org/pypi/SWMM5) and based my comments with that in mind, however..

---

Something like what a python user would expect when working with python

```python

from pyswmm import Swmm

swmm = Swmm(path='some/path/input')

for node in swmm.nodes():
    print(node)   # Node is an object that exposes some useful properties, getters / setters

for node in swmm.pipes():
    print(pipe)   # Pipe is an object that exposes some useful properties, getters / setters
```

You see what I mean?

**Comment by bemcdonnell** [comment]
@goanpeca The library you referenced provides a nice interface with SWMM and is maybe ahead of our lib at least at the user end.  While the functionality is great, I have experienced a few limitations especially with respect to speed when parsing out large output files.  Likely, pyswmm (this repository) will be joined with another lib we are working on that can be found in my repositories  "bemcdonnell/SWMMOutputAPI".  

From a structural standpoint, pyswmm (and bemcdonnell/SWMMOutputAPI) directly call a linked library without the need to use simplified wrapper and interface generator (SWIG) or the like.  We are trying to keep a clean and simple interface that can to interpreted easily.  PySWMM is currently in a functional state (exclusively used for running a model) but we are intending to grow its capability as we work on developing a suitable Input API on SWMM5. Furthermore, we are going to evaluate pulling in the SWMM Output API into SWMM5 itself to replace the single function to get results from the binary output file (from bemcdonnell/SWMMOutputAPI).  

The idea here is that we are working to build a complete interface to the SWMM data model.  This will keep us from having to read and store hydraulic and hydrologic data in multiple places, as well as give us the ability to "get and set" new values.  The our ideal framework will provide a nice pythonic interface and allow optimization.  We're getting there :)

**Comment by goanpeca** [comment]
> While the functionality is great, I have experienced a few limitations especially with respect to speed when parsing out large output files.

Not sure I understand

>ikely, pyswmm (this repository) will be joined with another lib we are working on that can be found in my repositories "bemcdonnell/SWMMOutputAPI"

Agree it should :-)

>From a structural standpoint, pyswmm (and bemcdonnell/SWMMOutputAPI) directly call a linked library without the need to use simplified wrapper and interface generator (SWIG) or the like.

Is this a problem for cross platform work?

>The idea here is that we are working to build a complete interface to the SWMM data model. 

Yep, that is what I meant also with the pythonic interface... a python complete model for SWMM for setting input and getting output and running simulations.

---
I would like to help :-), Is there any roadmap or place where this work is described discussed?

**Comment by goanpeca** [comment]
On a separate topic, are you familiar with conda and anaconda?

I am creating packages for [open-epanet](https://github.com/OpenWaterAnalytics/EPANET) when I get some feedback, maybe you can provide some :-p

**Comment by bemcdonnell** [comment]
Great! Well lets get started! 

The input API issue has been raised under the SWMM Repo:

Check out OpenWaterAnalytics/Stormwater-Management-Model#2

**Comment by goanpeca** [comment]
Cool, reading now, need to brush up my C, I am almost a python dev these days :-p.

---

No comment on conda? :-p?

**Comment by bemcdonnell** [comment]
I certainly have no opposition to someone helping this project get on board with conda. However, I think there are quite a few steps that need to be taken beforehand before pyswmm is more useful to a large audience

**Comment by goanpeca** [comment]
@bemcdonnell I guess what I meant was more in line with, having SWMM and epanet as conda packages and then pyswmm use dlls from those packages, hence, pyswmm and epanet-python would depend on those packages compiled for the specific platforms, instead of providing this dlls within this package.

**Comment by michaeltryby** [comment]
@goanpeca Python package management is something I'm just now coming up to speed on. How is conda different than say setup? What sort of build system does conda use to compile the dll's?

**Comment by goanpeca** [comment]
Well python packaging its a loooooooong history, but [this post](http://technicaldiscovery.blogspot.com.co/2013/12/why-i-promote-conda.html) on this topic that gives a broad summary on the why of conda

> How is conda different than say setup?

I am assuming by setup, you mean setup.py (pip install something?), anyway setup.py only handles python dependencies whereas conda handles any type of package (python, R, C, C++, etc...). Conda also provides isolated development environments (like virtualenv if you have heard of it) but on the system level (unlike python level for virtual env).

Think of conda as a cross platform language agnostic package manager (written in python)

Conda was created to ease the pain of handling non python dependencies which were/are very common on scientific applications (numpy, scipy, cython, pandas) plus things that that are not python (Qt, libpng, etc etc...)

More info
http://conda.pydata.org/docs/intro.html

> What sort of build system does conda use to compile the dll's?

Conda defines a recipe (meta.yaml) and a set of scripts to be run on the target os (build.sh, build.bat), plus any set of patches needed to compile a given source on a given platform.

More info here, http://conda.pydata.org/docs/building/recipe.html

To see a complex recipe (The Qt framework) you can see [this](https://github.com/ContinuumIO/anaconda-recipes/tree/master/qt)

---

I would strongly advice to use this toolchain as it is becoming the de facto tool for data science (Python R and complementary tools).

**Comment by michaeltryby** [comment]
One thing we are wrestling with is packaging, deployment, and installation of our desktop applications now that we are transitioning to Python. What if anything does conda provide in that department?

**Comment by goanpeca** [comment]
Hi @michaeltryby, 

Well the toolchain would be:
1. **conda-recipes** are use with **conda-build** to build a conda package (conda packages are binaries essentially with some metadata) using a continuous integrations system (Travis: OSX, Circle-CI: Linux and Appveyor: Windows)

Some high level commands that are executed:
- `conda build conda.recipe`

2. Upload built packages to https://anaconda.org (the distribution system as part of the continuous integration system). Its free for public packages. If your needs include private stuff, there is a fee for that.

- `anaconda login`
- `anaconda upload <package>`

3. If your needs include self hosting the distribution system, anaconda.org is also offered on premises.

4. Create an environment and add conda packages to it
- `conda create --name my_new_env python=3.5`
- `conda install some-package --channel <user-on-anaconda-org>`

**Comment by bemcdonnell** [comment]
@goanpeca, I'd like to keep an open mind to your conda idea.  We've made a lot of progress recently on pyswmm and the SWMM5 toolkit api.  Would you still be interested in helping this come to life?

**Comment by goanpeca** [comment]
Sure @bemcdonnell what can I do :-) ?

**Comment by bemcdonnell** [comment]
@goanpeca You previously mentioned that pyswmm could depend on SWMM as a conda package. 

> @bemcdonnell I guess what I meant was more in line with, having SWMM and epanet as conda packages and then pyswmm use dlls from those packages, hence, pyswmm and epanet-python would depend on those packages compiled for the specific platforms, instead of providing this dlls within this package.

I have been making some major improvements to the SWMM Toolkit API.  Perhaps this issue is better raised in the SWMM Repo/branch: 

OpenWaterAnalytics/Stormwater-Management-Model/tree/toolkitapi 

I'm mostly interested in what the best practice would be for setting this framework up such that I would not need to distribute a linked library with pyswmm.

**Comment by bemcdonnell** [comment]
@goanpeca, I am looking to push this project to Python Package Index and I ran into a problem:

https://pypi.python.org/pypi/pyswmm/0.1.0 

It looks like you have registered the pyswmm project name.  Do you have plans to submit a pyswmm to PyPI? If not, would you mind removing it so then this pyswmm project could live there? I really appreciate it!

**Comment by goanpeca** [comment]
Hi @bemcdonnell, yes I registered the name a loooong time ago... just give me your pypi username so I can add you as a maintainer. No problem wth that. I think it is easier to do that that deleting and creating etc....

I would be very happy to help improve the package also :-) (My main gripe so far has been that packages out there dont feel pythonic) . I dont have time right now, but I will next year.

**Comment by bemcdonnell** [comment]
Here are my concerns and general thoughts.  You are absolutely entitled to keeping the name pyswmm in the pypi; I missed our chance to secure it while we were in beta testing.  My loss. 

My concerns are that, while this could be a good thing overall since it appears you have thousands of lines of code experience behind you, you may steer this into a direction that is not agreeable from the perspective of our team.  Maybe I am wrong about that but it's a concern of ours.  

According to this link https://libraries.io/pypi/pyswmm , you secured the name for ```pyswmm``` on 2015-03-16. 
You also locked in the name (https://libraries.io/pypi/swmmpy) ```swmmpy``` on 2015-03-19. 

Our project PySWMM as born in May 2014 ([pyswmm](https://github.com/OpenWaterAnalytics/pyswmm/tree/4f230ac3173014987462dc04271dba89df72d73e))

On PyPI, here's what it looks like when someone "owns" a package.  In the case below, you would be perceived as the true Author of this package when in fact you haven't contributed to it nor were you the founder.  I respect your invitation to be a maintainer but considering our team does not know your intentions with pyswmm, it's not a good enough scenario.  
![image](https://cloud.githubusercontent.com/assets/6105134/21075796/e5adc1ac-bee8-11e6-98e1-d8d323c52297.png)

As far as "deleting and creating" as you referenced above, the following figure shows what this might look like if you log into PyPI - There is 1 button. 

![image](https://cloud.githubusercontent.com/assets/6105134/21075810/708d30fa-bee9-11e6-8543-2a2944ed3c24.png)

I am very interested in collaborating with you but I'm concerned we might be starting this project out in a less than desirable way.

**Comment by goanpeca** [comment]
Lets have a hangout. you have my email right?

**Comment by bemcdonnell** [comment]
@goanpeca, Thanks!  We really appreciate it. I will follow up with an email to setup a time for a Google Hangout.
