### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#7]
@abhiramm7 @mehmetbercan @aerispaha, Would any of you be up for the challenge?

**Comment by mehmetbercan** [comment]
I can do the support for Python 3.

Mehmet

**Comment by bemcdonnell** [comment]
@mehmetbercan Awesome! Do you want set some milestone goals? 

The best approach is if you fork the repo, and branch off of the dev branch.

**Comment by mehmetbercan** [comment]
Have heard about "https://travis-ci.org/? It tests the Github projects for every version of a programing language.

**Comment by bemcdonnell** [comment]
Indeed.  I started setting this up last night. 
[travis.yml](https://github.com/OpenWaterAnalytics/pyswmm/blob/InputAPIEnhancements/.travis.yml)

If you would like to take over and finish setting this up, that would be great too!

**Comment by aerispaha** [comment]
I'm interested in helping too! I've hobby-managed a handful of linux web servers which may be a starting point for me. I'm interested finding ways to put access swmm in a webapp - if that is somewhat along the lines of what you're looking for, I'd like to get involved.

**Comment by bemcdonnell** [comment]
@aerispaha, pyswmm will be a great foundation for a web application.  Support for Linux (and OSX) means we need to do a couple of things:

1. We need to build SWMM5 with the toolkitapi in Linux https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/tree/toolkitapi
2. Place that '*.dylib' or shared object (*.so) library into the pyswmm repo in here https://github.com/OpenWaterAnalytics/pyswmm/tree/master/pyswmm/swmmLinkedLibs
3. Update platform detection in pyswmm and run some tests:
```python
#### windows
if 'win32' in sys.platform:
    from ctypes import CDLL
    dllname = 'swmm5.dll'
    libswmm = get_pkgpath() + '\\swmmLinkedLibs\\Windows\\' + dllname
    self.SWMMlibobj = CDLL(libswmm)
```

At one point I had support for OSX but that was in an older version of pyswmm.  These are all great things. Any contribution is fair game at the moment as long as the theme of pyswmm remains a low-level wrapper.

**Comment by aerispaha** [comment]
This sounds great. After I wrap my head around the structure these projects, I'd be happy to work on this.

**Comment by goanpeca** [comment]
@bemcdonnell I have experience wih travis ci, appveyor and cirlcle ci for testing osx, win and linux respectively. I am happy to help on that front.

**Comment by bemcdonnell** [comment]
Believe this has been addressed - It's now a function of what happens in the SWMM repo
