### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#71]
So far the tests check out **fine on Windows 10**.  

This Error has been noticed on older versions of windows:
```WindowsError: [Error 126] The specified module could not be found```

It seems prior Windows versions call for a couple support DLLs: including 

* msvcp120.dll
* msvcr120.dll
* vccorlib120.dll
* vcomp120.dll

These libraries should sit along side of your main python script

[vcomp120.zip](https://github.com/OpenWaterAnalytics/pyswmm/files/805656/vcomp120.zip)

**Comment by goanpeca** [comment]
We need to have the corresponding runtime installed for the respective python version (2008, 2014,  2015) we cannot rely on manual compilation of these packages on local machines, this just does not scale and would be error prone, this is where the whole conda/conda-forge toolchain shines.
