### ISSUE TITLE
Add SWMM-DLL picker

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#77]

**Comment by dickinsonre** [comment]
This sounds like a very good idea to me, it would be a nice way to have alternate engines.  Would you unload the default dll and then load an alternate dll based on user options?

**Comment by bemcdonnell** [comment]
We had a simple discussion on this point yesterday in PR #74. 

@michaeltryby's idea
> One idea would be to instantiate the pyswmm object with the path to the dll and then pass it to the Simulation constructor. So you would make the pyswmm object as argument of the simulation constructor instead of the dll path.

**Comment by bemcdonnell** [comment]
One point to consider is if the user-selected DLL does not contain the *extended* toolkit API functions.  In these cases, the functions to **open** and **run** the simulation will still work.
