### ISSUE TITLE
Test Models

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/pyswmm#8]
@abhiramm7 In response to your email, I have been adding a couple test models to the [InputAPIEnhancements branch](/OpenWaterAnalytics/pyswmm/tree/InputAPIEnhancements/test).  So far there are a couple very simple models that can be used to test the basic functionality (pulling data and adjust link settings).  I have a more complicated model that I will add after running some more controls tests. 
![testmodel1_weirsetting](https://cloud.githubusercontent.com/assets/6105134/20350850/702b40fc-abde-11e6-9847-e3ffad85f20f.PNG)

Also, I've put this test case up on YouTube to demo the "weir setting" adjustment with ```TestModel1_weirSetting.inp```. 
https://www.youtube.com/watch?v=U5Z0NXTEjHE 

@rkertesz, @michaeltryby, @mehmetbercan, @aerispaha <- If there are any models you guys would like to add for testing, please upload them to this issue.

**Comment by abhiramm7** [comment]
Thanks @bemcdonnell for the reply. I was thinking of couple of test cases, which not only demonstrate how SWMM can be used for simulation of control cases, but can act as a common test cases for people to test their control algorithms on. I am thinking in the lines of  (https://gym.openai.com/) for water systems control. May be we need have a discussion on  whether these test cases would be  part of pyswmm or a separate package altogether.

**Comment by bemcdonnell** [comment]
@abhiramm7, yes, I understand what you are looking to do. I agree that we need a collection of "standard models" for control cases. I don't think we have a good common place for these models to exist today. moreover, I don't think these really need to live with pyswmm. 

I am envisioning a controls wrapper that uses pyswmm as a dependency. This would be a good place for these models to live. What are your thoughts?

**Comment by bemcdonnell** [comment]
I just looked at  https://gym.openai.com/ .  It looks pretty cool, actually!
