### ISSUE TITLE
Anybody else facing issues when using in virtualenv?

### ISSUE THREAD

**Issue by rkertesz** [OpenWaterAnalytics/pyswmm#82]
I wanted to set up pyswmm in a virtualenv and have all the prerequisite modules installed in the virtual env (on windows BTW) but am getting a number of errors similar to this:

> Traceback (most recent call last):
  File "<_snip_>.py", line 44, in <module>
    Tank<_snip_>            = Links(sim)["Tank<_snip_"]
  File "<_snip_>\virtualenv\virtual_1\lib\site-packages\pyswmm\links.py", line 68, in __init__
    self._nLinks = self._model.getProjectSize(ObjectType.LINK.value)
AttributeError: 'int' object has no attribute 'value'

and

> Traceback (most recent call last):
  File "<_snip_>.py", line 36, in <module>
    sim.report_start = datetime(2015,6,1,0,0,0)#start_date
  File "<_snip_>\virtualenv\virtual_1\lib\site-packages\pyswmm\simulation.py", line 243, in report_start
    self._model.setSimulationDateTime(SimulationTime.ReportStart.value,
AttributeError: 'int' object has no attribute 'value'

I am wondering if you have any insight? Does this indicate that one of my packages is deficient or that a basic python package is not being utilized? I purposely set up the virtual env with "--no-site-packages" to be able to have a virgin sandbox to play in.

**Comment by rkertesz** [comment]
Just noting that this runs fine in my normal environment

**Comment by bemcdonnell** [comment]
If you're are using py2.7 you need to get the enum34 package. 

pip install enum34

**Comment by goanpeca** [comment]
@bemcdonnell that should have been handled by the installer

**Comment by bemcdonnell** [comment]
@goanpeca - I was noticing for some machines enum34 wasn't getting installed

**Comment by goanpeca** [comment]
we need to check what machines, OS python version how it was installed, etc
